function [Fc, Fp] = surface_flux_linearization(T_sfc, tair, Qsi, Qli, ...
      albedo, wspd, ppt, tppt, psfc, ea_atm, ro_atm, cv_atm, nu_air, ...
      H_h, H_e, hv_atm, br_coefs, liqflag, chi, ro_sfc, snow_depth, opts)
   %SURFACE_FLUX_LINEARIZATION Linearize the non-conductive surface flux.
   %
   %  [Fc, Fp] = icemodel.surface.surface_flux_linearization(...)
   %
   % This is the canonical Robin-boundary linearization contract for the
   % touched SEB stack. The bulk-Richardson path keeps an analytic
   % linearization, while `monin_obukhov` uses a dedicated numerical
   % linearization of the nonlinear atmospheric surface-flux closure.
   %
   % H_h  — sensible heat transport prefactor [W m-2 K-1] = cv_atm * De_h
   % H_e  — latent heat transport prefactor [W m-2 Pa-1] = hv_atm * De_e
   % cv_atm, hv_atm, ro_atm, nu_air — for MO scheme (precomputed per timestep)
   %
   % See also: icemodel.surface.numerical_surface_flux
   %
   %#codegen

   if strcmp(opts.turbulent_flux_scheme, 'monin_obukhov')
      [Fc, Fp] = ...
         icemodel.surface.turbulence.monin_obukhov.surface_flux_linearization( ...
         T_sfc, tair, Qsi, Qli, albedo, wspd, ppt, tppt, psfc, ea_atm, ...
         ro_atm, cv_atm, nu_air, H_h, H_e, hv_atm, liqflag, chi, ro_sfc, ...
         snow_depth, opts);

   elseif strcmp(opts.turbulent_flux_scheme, 'bulk_richardson')
      [Fc, Fp] = ...
         icemodel.surface.turbulence.bulk_richardson.surface_flux_linearization( ...
         T_sfc, tair, Qsi, Qli, albedo, wspd, ppt, tppt, ea_atm, H_h, H_e, ...
         br_coefs, liqflag, chi);
   else
      error( ...
         'icemodel:surface_flux_linearization:unknownScheme', ...
         'Unrecognized turbulent flux scheme: %s', ...
         opts.turbulent_flux_scheme);
   end
end
