function [Qe, Qh, diag] = turbulent_heat_flux_bulk_richardson(T_sfc, tair, ...
      wspd, psfc, ea_atm, De, br_coefs, roL, liqflag, z0_bulk)
   %TURBULENT_HEAT_FLUX_BULK_RICHARDSON Evaluate the explicit THF scheme.
   %
   %  [Qe, Qh] = icemodel.surface.turbulent_heat_flux_bulk_richardson(...)
   %  [Qe, Qh, diag] = icemodel.surface.turbulent_heat_flux_bulk_richardson(...)
   %
   % This is the existing bulk-Richardson surface-transfer scheme used by the
   % production SEB path. The formulation uses one aerodynamic roughness, one
   % exchange coefficient, and the Louis/Liston stability factor.
   %
   %#codegen

   % Saturation vapor pressure at the surface.
   es_sfc = VAPPRESS(T_sfc, liqflag);

   % Bulk-Richardson stability factor.
   stability = STABLEFN(T_sfc, tair, wspd, br_coefs);

   % Latent heat flux at the surface.
   Qe = LATENT(es_sfc, ea_atm, De, stability, psfc, roL);

   % Sensible heat flux at the surface. Keep as an optional second output for
   % callers like potential_surface_vapor_tendency that only require Qe.
   if nargout > 1
      Qh = SENSIBLE(T_sfc, tair, De, stability);
   end

   % Diagnostics for callers that request it.
   if nargout > 2
      diag = bulk_richardson_diag(T_sfc, es_sfc, tair, wspd, psfc, De, ...
         ea_atm, stability, roL, z0_bulk);
   end
end

function diag = bulk_richardson_diag(T_sfc, es_sfc, tair, wspd, psfc, De, ...
      ea_atm, stability, roL, z0_bulk)
   %BULK_RICHARDSON_DIAG Assemble optional diagnostics for test/debug use.

   diag_scalar = icemodel.surface.bulk_richardson_scalar_exchange(T_sfc, es_sfc, tair, ...
      wspd, psfc, De, ea_atm, stability, roL, z0_bulk);

   diag = struct( ...
      'scheme', 'bulk_richardson', ...
      'stability_factor', stability, ...
      'es_sfc', es_sfc, ...
      'z0m', z0_bulk, ...
      'z0h', diag_scalar.z0h, ...
      'z0q', diag_scalar.z0q, ...
      'u_star', diag_scalar.u_star, ...
      'L', NaN, ...
      'Re', diag_scalar.Re, ...
      'scalar_exchange_active', diag_scalar.active, ...
      'scalar_exchange_z_obs', diag_scalar.z_obs, ...
      'scalar_exchange_De_h', diag_scalar.De_h, ...
      'scalar_exchange_De_e', diag_scalar.De_e, ...
      'scalar_exchange_Qh', diag_scalar.Qh, ...
      'scalar_exchange_Qe', diag_scalar.Qe);
end
