function tf = promiceFilledVerificationMatches(opts, fileiter) %#codegen
   %PROMICEFILLEDVERIFICATIONMATCHES Match a prevalidated runtime identity.
   %
   % Generated loading cannot read the readiness ledger or producer manifest.
   % The MATLAB verifier therefore snapshots the exact forcing label, station,
   % requested window, calendar/model contract, simulation years, 15-minute
   % timestep, and met-file list it checked. A separate provenance flag keeps
   % options minted by the older manifest/coverage-only verifier out of the
   % generated path; this predicate also refuses reuse after any runtime input
   % changes.
   if nargin < 2 || isempty(fileiter)
      fileiter = 1:numel(opts.metfname);
   end
   met_files = opts.metfname(fileiter);

   tf = opts.promice_filled_readiness_verified ...
      && opts.promice_filled_manifest_verified ...
      && opts.promice_filled_provenance_verified ...
      && strcmpi(opts.promice_filled_verified_forcing, opts.forcings) ...
      && strcmpi(opts.promice_filled_verified_site, opts.sitename) ...
      && isequal(opts.promice_filled_verified_simyears(:), opts.simyears(:)) ...
      && isequal(opts.promice_filled_verified_metfname(:), met_files(:)) ...
      && isequal(opts.promice_filled_verified_startdate, opts.startdate) ...
      && isequal(opts.promice_filled_verified_enddate, opts.enddate) ...
      && strcmpi(opts.promice_filled_verified_calendar_type, ...
      opts.calendar_type) ...
      && strcmpi(opts.promice_filled_verified_smbmodel, opts.smbmodel) ...
      && opts.promice_filled_verified_dt == opts.dt;
end
