function codes = provenanceCodes()
   %PROVENANCECODES Return the per-sample reconstruction provenance registry.
   %
   %  codes = icemodel.forcing.reconstruct.provenanceCodes()
   %
   % Role
   %  Single named source of the uint8 per-sample provenance codes the
   %  engine stamps and the report decodes (DesignSpec Resolution 3,
   %  POLICY A7). Every filled product channel carries one code per
   %  sample; the segment audit table carries the donor/fit/uncertainty
   %  detail codes alone cannot. Codes are append-only: renumbering would
   %  silently re-label previously staged products.
   %
   % Returns
   %  codes : struct of named uint8 constants —
   %     observed (0), bounded_interp (1), station_transfer (2),
   %     spline_adjustment (3), mar (4), merra2 (5), racmo (6), modis (7),
   %     climatology (8), constant (9), empirical_estimator (10, the
   %     calibrated lwd vapor-pressure candidate), darkness (11, the
   %     policy's swd polar-night zero-fill — a known value, not an
   %     estimate), derived_shortwave (12, swu = albedo * swd after both
   %     operand channels finish reconstruction), raw_shortwave (13, the
   %     PROMICE raw pyranometer fallback), clamped_shortwave (14, a finite
   %     negative selected PROMICE source value clamped to physical zero),
   %     twilight_climatology (15, the D-44 native-supported one-posting
   %     civil-twilight estimate), missing (255).
   %
   % See also: icemodel.forcing.reconstruct.admissionGate

   % Keep the registry explicit and append-only; the legacy Origin scheme's
   % conflations (one code for HIRHAM/MAR/RACMO, one for MODIS/climatology/
   % constant) are precisely what this table exists to prevent.
   codes = struct( ...
      'observed', uint8(0), ...
      'bounded_interp', uint8(1), ...
      'station_transfer', uint8(2), ...
      'spline_adjustment', uint8(3), ...
      'mar', uint8(4), ...
      'merra2', uint8(5), ...
      'racmo', uint8(6), ...
      'modis', uint8(7), ...
      'climatology', uint8(8), ...
      'constant', uint8(9), ...
      'empirical_estimator', uint8(10), ...
      'darkness', uint8(11), ...
      'derived_shortwave', uint8(12), ...
      'raw_shortwave', uint8(13), ...
      'clamped_shortwave', uint8(14), ...
      'twilight_climatology', uint8(15), ...
      'missing', uint8(255));
end
