function f = fSEB(Ts, Ta, Qsi, Qli, albedo, wspd, Pa, De, ea, ...
      cv_air, emiss, SB, Tf, chi, roL, scoef, Qc, liqflag)
   %SFCTEMP Surface energy balance equation

   f = chi * (1.0 - albedo) * Qsi + emiss * (Qli - SB * Ts ^ 4) ...
      + Qc + cv_air * De * (Ta - Ts) * STABLEFN(Ta, Ts, wspd, scoef) ...
      + roL * De * 0.622 / Pa * (ea - VAPPRESS(Ts, Tf, liqflag)) ...
      * STABLEFN(Ta, Ts, wspd, scoef);
   % + cp_liq * ppt * Tppt; % ppt in kg/m2/s
end
