function [  Tsfc,                                                       ...
            surf_melt,                                                  ...
            surf_freeze,                                                ...
            surf_subl,                                                  ...
            surf_cond,                                                  ...
            surf_runoff,                                                ...
            ice_surf,                                                   ...
            h_ice,                                                      ...
            h_liq,                                                      ...
            h_air,                                                      ...
            h_melt,                                                     ...
            h_freeze,                                                   ...
            h_drain,                                                    ...
            T_old   ]   = RESET_VARS(ice1,ice2,n)

%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% reset vars for adaptive time stepping            
    Tfp             = 273.16;
    Tsfc            = ice1.Tsfc(n-1,1)+Tfp;
    T_old           = ice2.Tice(:,n-1)+Tfp;
    surf_melt       = ice1.surf_melt(n-1,1);
    surf_freeze     = ice1.surf_freeze(n-1,1);
    surf_subl       = ice1.surf_subl(n-1,1);
    surf_cond       = ice1.surf_cond(n-1,1);
    surf_runoff     = ice1.surf_runoff(n-1,1);      
    ice_surf        = ice1.ice_surf(n-1,1);
    h_ice           = ice2.h_ice(:,n-1);
    h_liq           = ice2.h_liq(:,n-1);
    h_air           = ice2.h_air(:,n-1);
    h_melt          = ice2.h_melt(:,n-1);
    h_freeze        = ice2.h_freeze(:,n-1);
    h_drain         = ice2.h_drain(:,n-1);
    
%     ice_surf+surf_subl+h_ice(1)
end

