function h = myerrorbar(c,varargin)
    %MYERRORBAR wraps some decent formatting around errorbar function
    
    h  =   errorbar(varargin{:});
    
    set(h,  ...
            'Marker',           'o',        ...
            'MarkerSize',       8,          ...
            'LineWidth',        1.5,        ...
            'LineStyle',        'none',     ...
            'Color',            c,          ...
            'MarkerFaceColor',  c,          ...
            'MarkerEdgeColor',  'none'      );    

end

