function out = varnames(whichdata)

   % Define the grid and time dimension names
   dimvars = {
      'latitude', ...
      'longitude', ...
      'x_easting', ...
      'y_northing', ...
      'elevation', ...
      'time', ...
      };

   assert(strcmp(dimvars{end}, 'time'));

   % Define the variable names
   switch whichdata

      case 'ice1'

         out = {
            'Tsfc', ...
            'runoff', ...
            'depth_melt', ...
            'depth_freeze', ...
            'surf_runoff', ...
            'column_runoff', ...
            };

      case 'ice2'

         out = {
            'Tice', ...
            'df_liq', ...
            'f_ice', ...
            'f_liq', ...
            };

      case 'met'

      case {'dimensions', 'dims'}
         out = dimvars;

      otherwise
         error('unrecognized icemodel data file name')
   end

   % Return as a column
   out = out(:);
end
