function [observations, metadata] = buildGcnetVandecruxFirnTemperature(station, kwargs)
   %BUILDGCNETVANDECRUXFIRNTEMPERATURE Read GC-Net firn temperatures.
   %
   %  observations = icemodel.forcing.buildGcnetVandecruxFirnTemperature(station)
   %  [observations, metadata] = ... buildGcnetVandecruxFirnTemperature( ...
   %     station, source_dir=..., startdate=..., enddate=...)
   %
   % Reads the Vandecrux/GC-Net firn-temperature observation product
   % (<station>_T_firn_obs.nc) into a structured observation payload. The source
   % variables `T_firn` and `Depth` are preserved in metadata while the returned
   % payload exposes canonical `subsurface_temperature` [K] and `depth` [m]
   % matrices shaped time x level.
   %
   % See also: icemodel.verification.setup.gcnetInventory,
   %  icemodel.forcing.buildGcnetVandecruxData

   arguments
      station (1, 1) string
      kwargs.source_dir (1, 1) string = ""
      kwargs.startdate = ""
      kwargs.enddate = ""
   end

   % Reject malformed public windows before resolving or reading any source file.
   % The shared mask validates again defensively when it applies the bounds.
   [window_start, window_end] = ...
      icemodel.internal.pairedWindow(kwargs.startdate, kwargs.enddate);

   [source_dir, station] = icemodel.forcing.helpers.gcnetVandecruxInputs( ...
      kwargs.source_dir, station);
   filename = locateFirnTemperatureFile(source_dir, station);

   info = ncinfo(filename);
   source_names = string({info.Variables.Name});
   requireVariables(source_names, ["time", "level", "T_firn", "Depth"], ...
      filename);

   Time = icemodel.forcing.helpers.gcnetTime(double(ncread(filename, 'time')), ...
      icemodel.forcing.helpers.readNetcdfAttribute(filename, "time", ...
      "units"));
   keep = icemodel.forcing.helpers.timeWindowMask( ...
      Time, window_start, window_end);
   if ~any(keep)
      error('icemodel:forcing:buildGcnetVandecruxFirnTemperature:emptyWindow', ...
         'requested window does not overlap %s', filename)
   end

   idx = find(keep);
   first_time = idx(1);
   n_time = numel(idx);
   Time = Time(keep);
   level = double(ncread(filename, 'level'));
   [temperature, temperature_policy] = convertTemperature( ...
      readLevelTimeVariable(filename, "T_firn", first_time, n_time), ...
      icemodel.forcing.helpers.readNetcdfAttribute(filename, "T_firn", ...
      "units"));
   depth = readLevelTimeVariable(filename, "Depth", first_time, n_time);

   metadata = icemodel.forcing.helpers.columnizeMetadata( ...
      sourceMetadata(source_dir, filename, station, info, Time, ...
      level, temperature_policy));
   observations = struct( ...
      'format', "gcnet_firn_temperature_observations", ...
      'source_family', "gcnet_vandecrux", ...
      'station', station, ...
      'time', Time(:), ...
      'level', level(:), ...
      'subsurface_temperature', temperature, ...
      'depth', depth, ...
      'variables', struct( ...
         'subsurface_temperature', "T_firn", ...
         'depth', "Depth", ...
         'level', "level", ...
         'time', "time"), ...
      'units', struct( ...
         'subsurface_temperature', "K", ...
         'depth', "m"));
end

%% Local functions
function filename = locateFirnTemperatureFile(source_dir, station)
   %LOCATEFIRNTEMPERATUREFILE Find flat or package-subfolder observation files.
   filename = icemodel.forcing.helpers.locateNormalizedFile(source_dir, ...
      station + "_T_firn_obs.nc", ...
      error_id="icemodel:forcing:buildGcnetVandecruxFirnTemperature:fileNotFound", ...
      error_label="GC-Net/Vandecrux firn-temperature file");
end

function requireVariables(source_names, required, filename)
   %REQUIREVARIABLES Fail early when a source file is not the expected product.
   missing = setdiff(required, source_names, 'stable');
   if ~isempty(missing)
      error('icemodel:forcing:buildGcnetVandecruxFirnTemperature:missingVariable', ...
         'GC-Net/Vandecrux firn-temperature file %s is missing %s', ...
         filename, strjoin(missing, ', '))
   end
end

function data = readLevelTimeVariable(filename, variable, first_time, n_time)
   %READLEVELTIMEVARIABLE Return one source variable as time x level.
   info = ncinfo(filename, variable);
   dims = string({info.Dimensions.Name});
   sizes = double([info.Dimensions.Length]);

   if isequal(dims, ["level", "time"])
      n_level = sizes(dims == "level");
      data = double(ncread(filename, variable, ...
         [1 first_time], [n_level n_time])).';
   elseif isequal(dims, ["time", "level"])
      n_level = sizes(dims == "level");
      data = double(ncread(filename, variable, ...
         [first_time 1], [n_time n_level]));
   else
      error('icemodel:forcing:buildGcnetVandecruxFirnTemperature:unsupportedDims', ...
         'variable %s must be dimensioned level,time or time,level in %s', ...
         variable, filename)
   end
end

function [temperature, policy] = convertTemperature(raw, units)
   %CONVERTTEMPERATURE Convert source firn temperatures to canonical Kelvin.
   units = lower(string(units));
   if ismember(units, ["degc", "c", "degree_celsius", "degrees_celsius"])
      temperature = raw + 273.15;
      policy = "source T_firn converted from degC to canonical K";
   elseif ismember(units, ["k", "kelvin"])
      temperature = raw;
      policy = "source T_firn already in canonical K";
   else
      temperature = raw;
      policy = "source T_firn units unknown; values preserved without conversion";
   end
end

function metadata = sourceMetadata(source_dir, filename, station, info, Time, ...
      level, temperature_policy)
   %SOURCEMETADATA Assemble compact observation provenance and variable maps.
   inventory = icemodel.verification.setup.gcnetInventory(source_dir, ...
      stations=station, products="firn_temperature");
   record = matchingRecord(inventory.records, station, filename);
   provenance = record.provenance;
   if ~isfield(provenance, 'doi') || provenance.doi == ""
      provenance.doi = "10.18739/A2833N00P";
   end

   metadata = struct( ...
      'source_file', filename, ...
      'source_family', "gcnet_vandecrux", ...
      'source_product', "firn_temperature", ...
      'station', station, ...
      'aliases', record.aliases, ...
      'site_location', icemodel.forcing.helpers.projectLocation(record.site_location), ...
      'provenance', provenance, ...
      'source_variables', string({info.Variables.Name})', ...
      'source_variable_attributes', ...
         icemodel.forcing.helpers.sourceVariableAttributes(info), ...
      'canonical_variables', ["subsurface_temperature", "depth"], ...
      'original_variables', ["T_firn", "Depth"], ...
      'variable_map', struct( ...
         'subsurface_temperature', "T_firn", ...
         'depth', "Depth"), ...
      'level', level(:), ...
      'period', struct('start', Time(1), 'end', Time(end)), ...
      'temperature_policy', temperature_policy, ...
      'depth_policy', "Depth is source measurement depth below the surface");
end

function record = matchingRecord(records, station, filename)
   %MATCHINGRECORD Find the inventory row for one station and file.
   filename = string(filename);
   keep = string({records.station}) == station ...
      & string({records.filename}) == filename;
   idx = find(keep, 1);
   if isempty(idx)
      record = struct('aliases', string(station), 'site_location', struct(), ...
         'provenance', struct('doi', "10.18739/A2833N00P"));
   else
      record = records(idx);
   end
end
