function [  H,                                                          ...
            T,                                                          ...
            errH,                                                       ...
            errT,                                                       ...
            OK    ]  =  ICEENBAL(T,f_ice,f_liq,k_liq,cv_ice,cv_liq,     ...
                        ro_ice,ro_liq,ro_sno,cp_liq,cp_sno,Ls,Lf,roLf,  ...
                        Rv,Tf,dz,delz,fn,dzdt,JJ_therm,Tsfc,Sc,fcp,TL,  ...
                        TH,flmin,flmax,fcpsq,ro_iwe,ro_wie)
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

% % liquid water fraction and the derivative of f_liq wrt to temperature
   [dFdT,f_wat] = FREEZECURVE(T,f_liq,f_ice,ro_iwe,Tf,fcpsq);


% [  f_liq,                                                               ...
%    f_ice,                                                               ...
%    f_wat,                                                               ...
%    T,                                                                   ...
%    dFdT ]   =  MELTCURVE(T,f_liq,f_ice,ro_wie,ro_iwe,Tf,fcp,fcpsq);
% 
% [  ~,                                                      ...
%    ro_sno,                                                     ...
%    cp_sno,                                                     ...
%    ~ ]      =  UPDATESTATE(T,f_ice,f_liq,ro_ice,ro_liq,1.275, ...
%                2102,cp_liq,k_liq,Ls,Rv,Tf);

% vapor diffusion heat
   H_vap    =  VAPORHEAT(T,f_liq,f_ice,Tf,Rv,Ls);

% total enthalpy (expressed in W/m2 for intuitive comparison with fluxes)
   H_old    =  TOTALHEAT(T,f_liq,f_ice,cv_liq,cv_ice,roLf,Tf,H_vap,dzdt);
                 
% solve the heat equation
[  H,                                                                   ...
   T,                                                                   ...
   errH,                                                                  ...
   errT,                                                                  ...
   OK  ]    =  HEATSOLVE(T,H_old,f_wat,f_ice,f_liq,k_liq,cv_ice,cv_liq, ...
               ro_ice,ro_liq,ro_sno,cp_liq,cp_sno,dFdT,Ls,Lf,roLf,Rv,Tf,...
               dz,delz,fn,dzdt,JJ_therm,Tsfc,Sc,fcp,TL,TH,flmin,flmax,fcpsq,  ...
               ro_iwe,ro_wie);