function diag = initialize_solver_diag()
   %INITIALIZE_SOLVER_DIAG Initialize forcing-step solver diagnostics.
   %
   %  diag = icemodel.couplers.initialize_solver_diag()
   %
   % Accepted-solve fields start at these values:
   %  - ok_seb, ok_ieb, ok_cpl: logical flags, false
   %  - n_iters: final inner Picard iteration count, NaN
   %  - cpl_iters: outer iteration count, 0
   %  - cpl_res: signed outer residual [K], NaN
   %  - seb_res: SEB residual magnitude [W m-2], NaN
   %
   % Forcing-step scalar counters start at zero:
   %  - cpl_recovery_count: accepted substeps that used recovery settings
   %  - n_failed_substeps: failures charged to the timestep controller
   %  - n_forced_advances: checkpoint-only advances without an accepted solve
   %
   % DIAG.SUBSTEP stores the latest raw attempt. It also has cpl_res_hist, a
   % 16-by-1 signed residual ring for failure dumps. Without an accepted
   % attempt, the accepted-solve fields keep their initial values. Counters can
   % still change.
   %
   % See also: icemodel.couplers.update_solver_diag,
   %  icemodel.timestepping.newtimestep
   %
   %#codegen

   substep_diag = struct( ...
      'ok_seb', false, ...
      'ok_ieb', false, ...
      'ok_cpl', false, ...
      'n_iters', nan, ...
      'cpl_iters', 0.0, ...
      'cpl_res', nan, ...
      'seb_res', nan, ...
      'cpl_res_hist', nan(16, 1));

   diag = struct( ...
      'ok_seb', false, ...
      'ok_ieb', false, ...
      'ok_cpl', false, ...
      'n_iters', nan, ...
      'cpl_iters', 0.0, ...
      'cpl_res', nan, ...
      'seb_res', nan, ...
      'cpl_recovery_count', 0.0, ...
      'n_failed_substeps', 0.0, ...
      'n_forced_advances', 0.0, ...
      'substep', substep_diag);
end
