function [settings, settings0] = initialize_solver_settings(opts)
   %INITIALIZE_SOLVER_SETTINGS Initialize solver and timestep settings.
   %
   %  [settings, settings0] = ...
   %     icemodel.couplers.initialize_solver_settings(opts)
   %
   % SETTINGS is active; SETTINGS0 keeps the default values. checksubstep
   % applies cpl_recovery_alpha and disables Aitken after an outer failure.
   % acceptsubstep restores SETTINGS0 after recovery. dt_full_step is the
   % forcing step [s]. maxsubstep makes the minimum substep one second.
   %
   % See also: icemodel, skinmodel
   %
   %#codegen

   settings = struct( ...
      'solver', opts.solver, ...
      'maxiter', opts.maxiter, ...
      'tol', opts.tol, ...
      'alpha', opts.alpha, ...
      'use_aitken', opts.use_aitken, ...
      'jumpmax', opts.jumpmax, ...
      'cpl_maxiter', opts.cpl_maxiter, ...
      'cpl_Ts_tol', opts.cpl_Ts_tol, ...
      'cpl_seb_tol', opts.cpl_seb_tol, ...
      'cpl_alpha', opts.cpl_alpha, ...
      'cpl_aitken', opts.cpl_aitken, ...
      'cpl_jumpmax', opts.cpl_jumpmax, ...
      'cpl_recovery_alpha', min(opts.cpl_alpha, ...
      icemodel.parameterLookup('cpl_recovery_alpha')), ...
      'cpl_recovery_active', false, ...
      'dt_full_step', opts.dt, ...
      'maxsubstep', opts.dt, ...
      'debug', opts.debug);
   settings0 = settings;
end
