function generateFinalFirnPreview()
%GENERATEFINALFIRNPREVIEW Build canonical firn QA and figure products.
% Reads the promoted RetMIP, IMAU, SUMup, and research-site artifacts, then
% writes only the canonical data/preview products consumed by the checked
% combined snow-and-firn Quarto report.

repo_root = string(icemodel.internal.fullpath());
data_root = fullfile(repo_root, "data");
eval_root = fullfile(data_root, "eval");
input_root = fullfile(data_root, "input");
preview_root = fullfile(data_root, "preview");
qa_root = fullfile(preview_root, "qa", "firn");
figure_root = fullfile(preview_root, "figures", "firn");
index_file = fullfile(preview_root, "qa", "firn_figure_index.csv");
evidence_root = fullfile(repo_root, "sandbox", "verification", ...
   "icemodel-hfc.2.26.8", "evidence");
complete_file = fullfile(evidence_root, "FINAL_FIRN_PREVIEW_COMPLETE.json");
failed_file = fullfile(evidence_root, "FINAL_FIRN_PREVIEW_FAILED.txt");

% Clear only this reproducible run marker before starting. The driver never
% changes staging, promotion, convergence, or source-repair evidence.
if ~isfolder(evidence_root)
   mkdir(evidence_root)
end
if isfile(complete_file)
   delete(complete_file)
end
if isfile(failed_file)
   delete(failed_file)
end

try
   started = datetime("now", TimeZone="UTC");
   % Resolve the repository package and plotting dependencies inside the
   % failure boundary so setup failures leave the same durable evidence.
   addpath(fullfile(repo_root, "icemodel"));
   icemodel.dependencies();
   families = ["retmip", "imau", "sumup", "research_site"];

   % Canonical manifests must exist and must not depend on an isolated stage.
   for family = families
      manifest_file = fullfile(eval_root, family, "manifest.json");
      assert(isfile(manifest_file), ...
         "icemodel:hfc2268:manifestMissing", ...
         "Missing canonical firn manifest: %s", manifest_file);
      manifest_text = fileread(manifest_file);
      assert(~contains(manifest_text, "/private/tmp") ...
         && ~contains(manifest_text, "/tmp/"), ...
         "icemodel:hfc2268:temporaryManifestPath", ...
         "Canonical firn manifest depends on a temporary root: %s", ...
         manifest_file);
   end

   % Quantitative QA runs before rendering so an artifact defect cannot waste
   % the complete 56-case figure pass.
   if ~isfolder(qa_root)
      mkdir(qa_root)
   end
   audit = icemodel.verification.auditArtifacts( ...
      evaluation_data_root=eval_root, input_data_root=input_root, ...
      families=families, report_dir=qa_root);
   assert(audit.summary.passed && audit.summary.error_count == 0 ...
      && audit.summary.blocker_count == 0 ...
      && audit.summary.family_count == 4 ...
      && audit.summary.case_count == 56 ...
      && audit.summary.artifact_count == 458, ...
      "icemodel:hfc2268:artifactAuditFailed", ...
      "Firn artifact audit failed or its 4-family/56-case/458-artifact scope drifted.");

   % Remove only the owned canonical firn figure tree and regenerate it with
   % the current shared reducers, colors, layouts, and source labels.
   if isfolder(figure_root)
      rmdir(figure_root, 's')
   end
   mkdir(figure_root)
   summary = icemodel.verification.plotVerificationArtifacts( ...
      evaluation_data_root=eval_root, input_data_root=input_root, ...
      dataset_family=families, figure_root=figure_root, ...
      save_figs=true, overwrite=true, visible=false);

   % The ledger is accepted only when it is a one-to-one inventory of nonempty,
   % unique canonical PNGs. This catches stale figures and incomplete renders.
   pngs = dir(fullfile(figure_root, "**", "*.png"));
   png_paths = fullfile(string({pngs.folder}), string({pngs.name}))';
   ledger_paths = string(summary.figure_file);
   ledger_families = unique(string(summary.dataset_family));
   ledger_cases = unique(string(summary.dataset_family) + "/" ...
      + string(summary.case_id));
   assert(istable(summary) && height(summary) == 702 ...
      && height(summary) == numel(pngs) ...
      && isequal(sort(ledger_families), sort(families(:))) ...
      && numel(ledger_cases) == 56 ...
      && numel(unique(png_paths)) == numel(png_paths) ...
      && all([pngs.bytes] > 0) ...
      && isequal(sort(ledger_paths), sort(png_paths)), ...
      "icemodel:hfc2268:figureInventoryMismatch", ...
      "Expected the validated 702-row firn ledger to equal its nonempty PNG tree.");
   writetable(summary, index_file);
   save(fullfile(qa_root, "final_firn_preview_summary.mat"), ...
      "summary", "audit");

   % Seal a small reproducibility record for the subsequent report build/check.
   completed = datetime("now", TimeZone="UTC");
   evidence = struct( ...
      'started_at', string(started), 'completed_at', string(completed), ...
      'elapsed_seconds', seconds(completed - started), ...
      'family_count', audit.summary.family_count, ...
      'case_count', audit.summary.case_count, ...
      'artifact_count', audit.summary.artifact_count, ...
      'channel_count', audit.summary.channel_count, ...
      'figure_count', numel(pngs), 'summary_rows', height(summary), ...
      'audit_error_count', audit.summary.error_count, ...
      'audit_blocker_count', audit.summary.blocker_count);
   writelines(string(jsonencode(evidence, PrettyPrint=true)), complete_file);
catch err
   % Failed runs may not retain a stale or partially written success marker.
   if isfile(complete_file)
      delete(complete_file)
   end
   writelines(string(getReport(err, "extended", "hyperlinks", "off")), ...
      failed_file);
   rethrow(err)
end
end
