function [summary, aligned, diagnostics, policy] = compareAblation( ...
      observations, model, kwargs)
   %COMPAREABLATION Compare PROMICE lowering with modeled solid-ice loss.
   %
   %  [summary, aligned, diagnostics, policy] = ...
   %     icemodel.verification.compareAblation(observations, model)
   %  [...] = icemodel.verification.compareAblation(..., ...,
   %     window_start=t0, window_end=t1,
   %     endpoint_deficit_kg_m2=[lower central upper])
   %
   % OBSERVATIONS is a staged PROMICE timetable or a bundle whose data field is
   % that timetable. MODEL is a postprocessed diagnostic IceModel timetable or
   % an equivalent data bundle. PROMICE ablation is geometric positive-down
   % lowering [m]. The modeled primary is positive solid-ice loss
   % -sum(P_S + V_S) [m w.e.]; remeshing is never added to it.
   % Each diagnostic model row is a forcing-step ledger stamped at the interval
   % start, so observations at t0 and t1 consume model rows on [t0,t1).
   % Paired values additionally require finite snow depth at or below the fixed
   % exposed-ice threshold; trace-snow rows remain inside the cumulative span
   % but are censored from alignment.
   % ENDPOINT_DEFICIT_KG_M2 supplies caller-provided sensitivity scenarios for
   % D(t1)-D(t0). This comparator cannot validate their observation provenance,
   % so they remain visible but never govern classification. Geometric
   % observations are also converted over the fixed 600--900 kg m^-3
   % porous-weathering-crust-to-intact sensitivity range; 600 kg m^-3 is the
   % porous endpoint, not necessarily the numeric lower bound when signed
   % lowering is negative and not an intact-ice density.

   arguments
      observations
      model
      kwargs.window_start (1, 1) datetime = NaT
      kwargs.window_end (1, 1) datetime = NaT
      kwargs.endpoint_deficit_kg_m2 double = double.empty(1, 0)
   end

   policy = icemodel.verification.namelists.promiceAblationPolicy();
   obs_tt = comparisonTimetable(observations, "observation");
   model_tt = comparisonTimetable(model, "model");

   % Validate the staged and diagnostic schemas before selecting a window so a
   % missing physical term cannot be mistaken for unavailable temporal support.
   requireVariables(obs_tt, policy.required_observation_fields, ...
      'icemodel:verification:compareAblation:missingObservationField');
   requireVariables(model_tt, policy.required_model_fields, ...
      'icemodel:verification:compareAblation:missingModelField');
   obs_tt = normalizeTimetable(obs_tt, "observation");
   model_tt = normalizeTimetable(model_tt, "model");

   endpoint_deficit = kwargs.endpoint_deficit_kg_m2(:);
   if any(~isfinite(endpoint_deficit))
      error('icemodel:verification:compareAblation:badEndpointDeficit', ...
         'endpoint_deficit_kg_m2 must contain only finite scenarios')
   end

   % The requested bounds are explicit in every result; omitted bounds mean the
   % full overlap, not a hidden calendar or site-specific study window.
   [window_start, window_end] = comparisonWindow(obs_tt.Time, model_tt.Time, ...
      kwargs.window_start, kwargs.window_end);
   [common_time, obs_idx, model_idx] = intersect( ...
      obs_tt.Time, model_tt.Time, 'stable');
   in_window = common_time >= window_start & common_time <= window_end;

   obs_values = numericValues(obs_tt, obs_idx, ...
      policy.required_observation_fields, "observation");
   model_values = numericValues(model_tt, model_idx, ...
      policy.required_model_fields, "model");
   observation_fields = policy.required_observation_fields;
   target_values = obs_values(:, ...
      observation_fields == policy.observation_field);
   snow_values = obs_values(:, ...
      observation_fields == policy.snow_variable);
   support_values = obs_values(:, ismember( ...
      observation_fields, policy.support_flag_fields));
   direct_values = obs_values(:, ismember( ...
      observation_fields, policy.direct_zero_flag_fields));
   datum_values = obs_values(:, ismember( ...
      observation_fields, policy.datum_break_flag_fields));
   gap_values = obs_values(:, ismember( ...
      observation_fields, policy.ordinary_gap_flag_fields));
   metadata_values = obs_values(:, ismember( ...
      observation_fields, policy.metadata_only_flag_fields));
   obs_finite = isfinite(target_values);
   model_finite = all(isfinite(model_values), 2);
   quality_finite = all(isfinite(support_values), 2);
   gap_bridged = all(isfinite(gap_values), 2) ...
      & any(gap_values ~= 0, 2);
   station_transition = isfinite(datum_values(:, 1)) ...
      & datum_values(:, 1) ~= 0;
   unresolved_step = isfinite(datum_values(:, 2)) ...
      & datum_values(:, 2) ~= 0;
   direct = quality_finite & all(direct_values == 0, 2);
   [ice_exposed, snow_censored, unknown_snow] = ...
      icemodel.verification.helpers.classifySnowDepth( ...
      snow_values, policy.ice_exposure_threshold_m);
   eligible = in_window & obs_finite & model_finite & direct & ice_exposed;

   if nnz(eligible) < 2
      error('icemodel:verification:compareAblation:insufficientSupport', ...
         ['the requested window has %d direct finite exact-common samples; ' ...
         'at least two are required'], nnz(eligible))
   end

   eligible_time = common_time(eligible);
   actual_start = eligible_time(1);
   actual_end = eligible_time(end);

   % The comparator uses cumulative levels at exact direct endpoints, so an
   % ordinary surface-height gap may remain between plotted markers. A station
   % transition or unresolved/unknown step changes the cumulative datum and
   % therefore invalidates any window that crosses it.
   observation_window = obs_tt(obs_tt.Time >= actual_start ...
      & obs_tt.Time <= actual_end, :);
   observation_values = numericValues(observation_window, ...
      (1:height(observation_window))', ...
      policy.required_observation_fields, "observation");
   observation_datum = observation_values(:, ismember( ...
      observation_fields, policy.datum_break_flag_fields));
   datum_intact = all(isfinite(observation_datum) ...
      & observation_datum == 0, 2);
   if any(~datum_intact)
      error('icemodel:verification:compareAblation:observationDatumBreak', ...
         ['comparison endpoints cannot cross a station transition or an ' ...
         'unresolved/unknown observation step'])
   end

   ledger = model_tt(model_tt.Time >= actual_start ...
      & model_tt.Time < actual_end, :);
   expected_step = seconds(policy.model_output_cadence_seconds);
   model_support_time = [ledger.Time; actual_end];
   model_day_start = dateshift(model_support_time, 'start', 'day');
   model_elapsed_seconds = seconds(model_support_time - model_day_start);
   if any(mod(model_elapsed_seconds, ...
         policy.model_output_cadence_seconds) ~= 0)
      error('icemodel:verification:compareAblation:offGridModelTime', ...
         'model diagnostic rows must lie on native UTC output boundaries')
   end
   if isempty(ledger) || ledger.Time(1) ~= actual_start ...
         || ledger.Time(end) + expected_step ~= actual_end ...
         || any(diff(ledger.Time) ~= expected_step)
      error('icemodel:verification:compareAblation:noncontiguousModelSupport', ...
         ['model diagnostics must contain every %g-second interval-start ' ...
         'row on [t0,t1)'], policy.model_output_cadence_seconds)
   end
   ledger_values = numericValues(ledger, (1:height(ledger))', ...
      policy.required_model_fields, "model");
   if any(~isfinite(ledger_values), 'all')
      error('icemodel:verification:compareAblation:nonfiniteModelWindow', ...
         'every required diagnostic must be finite throughout the model window')
   end
   throughput_fields = policy.required_model_fields(contains( ...
      policy.required_model_fields, "_throughput_"));
   throughput_values = numericValues(ledger, (1:height(ledger))', ...
      throughput_fields, "model");
   if any(throughput_values < 0, 'all')
      error('icemodel:verification:compareAblation:negativeThroughput', ...
         'diagnostic throughput fields must be nonnegative')
   end

   % Independently rebase observation geometry and model cumulative loss at the
   % first direct common point. Prefix zero is the state at t0; each subsequent
   % value includes rows strictly before its state-observation timestamp.
   physical_increment = -(ledger.mass_budget_phase_solid_mwe ...
      + ledger.mass_budget_vapor_solid_mwe);
   model_prefix = [0; cumsum(physical_increment)];
   [~, eligible_model_idx] = ismember(eligible_time, model_tt.Time);
   start_model_idx = eligible_model_idx(1);
   model_aligned = model_prefix(eligible_model_idx - start_model_idx + 1);
   cumulative_idx = eligible_model_idx - 1;
   if any(cumulative_idx < 1) || any( ...
         model_tt.Time(cumulative_idx) + expected_step ~= eligible_time)
      error('icemodel:verification:compareAblation:missingBoundaryState', ...
         ['cumulative diagnostics require the preceding hourly endpoint ' ...
         'state at every eligible observation time'])
   end
   cumulative_fields = string( ...
      icemodel.column.cumulative_output_fields());
   cumulative_values = numericValues(model_tt, cumulative_idx, ...
      cumulative_fields, "model cumulative boundary");
   if any(~isfinite(cumulative_values), 'all')
      error('icemodel:verification:compareAblation:nonfiniteBoundaryState', ...
         'every cumulative diagnostic boundary state must be finite')
   end
   model_melt = cumulative_values(:, cumulative_fields == "melt");
   model_runoff = cumulative_values(:, cumulative_fields == "runoff");
   model_freeze = cumulative_values(:, cumulative_fields == "freeze");
   % dlayer is the mass remeshing removed, in metres water equivalent. Note
   % that merge_layers does not conserve mass, so this is a numerical term and
   % not an ablation flux. See icemodel-4nv.
   model_layer_change = cumulative_values(:, cumulative_fields == "dlayer");
   model_melt = model_melt - model_melt(1);
   model_runoff = model_runoff - model_runoff(1);
   model_freeze = model_freeze - model_freeze(1);
   model_layer_change = model_layer_change - model_layer_change(1);
   % Surface mass loss is the mass a top removal actually exported. Deleting a
   % cell never removes all of its mass, so the quantized deletion height is not
   % convertible to mass and is retained only as a separate geometry counter.
   model_surface_loss = [0; cumsum( ...
      ledger.mass_budget_top_export_solid_mwe ...
      + ledger.mass_budget_top_export_liquid_mwe)];
   model_surface_loss = model_surface_loss( ...
      eligible_model_idx - start_model_idx + 1);

   % Sublimation removes ice without ever becoming liquid, so runoff cannot see
   % it. Adding the SOLID vapor loss to runoff gives a continuous ablation
   % proxy: melt that actually left under the runoff residence-time limit, plus
   % sublimation, minus deposition.
   %
   % Liquid vapor exchange is deliberately excluded from this proxy. Evaporation
   % removes pore water that runoff has already counted as melt that left, so
   % adding it would double count the same mass. Condensation adds pore liquid
   % rather than ice, so crediting it would wrongly reduce the inferred surface
   % lowering; it belongs in the liquid-water budget, not in an ice-loss proxy.
   solid_vapor_loss = -ledger.mass_budget_vapor_solid_mwe;
   model_vapor_loss = [0; cumsum(solid_vapor_loss)];
   model_vapor_loss = model_vapor_loss( ...
      eligible_model_idx - start_model_idx + 1);
   model_ablation_proxy = model_runoff + model_vapor_loss;
   obs_raw = obs_tt.(policy.observation_field)(obs_idx(eligible));
   obs_lowering = obs_raw - obs_raw(1);
   [Ls, Lv, ro_ice, ro_liq] = icemodel.physicalConstant( ...
      'Ls', 'Lv', 'ro_ice', 'ro_liq');
   obs_intact_mwe = obs_lowering * ro_ice / ro_liq;
   density = policy.effective_density_kg_m3(:);
   obs_density_mwe = obs_lowering .* density.' / ro_liq;
   % Pointwise extrema keep lower/upper field names numerically truthful when
   % signed lowering is negative and the density-endpoint order reverses.
   obs_density_lower_mwe = min(obs_density_mwe, [], 2);
   obs_density_upper_mwe = max(obs_density_mwe, [], 2);

   % The reference density is the representative bubbly near-surface ice value
   % drawn inside the band, so a reader sees one best estimate rather than only
   % an envelope.
   obs_reference_mwe = obs_lowering ...
      * policy.effective_density_reference_kg_m3 / ro_liq;

   aligned = timetable(obs_raw, obs_lowering, obs_intact_mwe, ...
      obs_density_lower_mwe, obs_density_upper_mwe, obs_reference_mwe, ...
      model_melt, ...
      model_runoff, model_freeze, model_aligned, model_layer_change, ...
      model_surface_loss, model_ablation_proxy, ...
      model_aligned - obs_intact_mwe, ...
      'RowTimes', eligible_time, ...
      'VariableNames', {'observation_ablation_m', ...
      'observation_lowering_m', 'observation_intact_mwe', ...
      'observation_lower_mwe', 'observation_upper_mwe', ...
      'observation_reference_mwe', ...
      'model_melt_mwe', 'model_runoff_mwe', 'model_freeze_mwe', ...
      'model_solid_loss_mwe', 'model_layer_change_mwe', ...
      'model_surface_mass_loss_mwe', 'model_ablation_proxy_mwe', ...
      'model_minus_observation_mwe'});

   % Evaluate the checkpoint, phase, mixed-latent-heat, and B/O remesh
   % identities over exactly the interval represented by the rebased series.
   diagnostics.identities = closureIdentities( ...
      ledger, policy, Ls, Lv, ro_liq);
   diagnostics.physical_comparable = all(diagnostics.identities.passed);

   a_model = model_aligned(end);
   h_obs = obs_lowering(end);
   a_obs = obs_intact_mwe(end);
   signal = max([abs(a_model), abs(a_obs), ...
      policy.scientific.signal_floor_mwe]);

   % Retain signed and non-cancelling ratios for each accounting channel. A
   % large positive and negative exchange must not disappear by cancellation.
   diagnostics.materiality = materialityDiagnostics( ...
      ledger, endpoint_deficit, signal, policy, Ls, ro_liq);
   [diagnostics.scenarios, non_identifiable_reasons] = ...
      scenarioDiagnostics(a_model, a_obs, endpoint_deficit, ...
      diagnostics.materiality, ledger, policy, Ls, ro_liq);

   % Effective-density conversions are always labeled sensitivities and never
   % promoted to rigorous endpoint bounds or identifiability evidence.
   density_mwe = h_obs .* density ./ ro_liq;
   diagnostics.effective_density = table(density, density_mwe, ...
      false(numel(density), 1), ...
      'VariableNames', {'effective_density_kg_m3', ...
      'observation_sensitivity_mwe', 'rigorous_bound'});
   diagnostics.excluded = exclusionCounts(in_window, eligible, obs_finite, ...
      model_finite, quality_finite, gap_bridged, station_transition, ...
      unresolved_step, metadata_values, unknown_snow, snow_censored);
   diagnostics.top_deletion = struct( ...
      'count', sum(ledger.mass_budget_top_deletion_count), ...
      'height_m', sum(ledger.mass_budget_top_deletion_height_m), ...
      'export_solid_mwe', sum(ledger.mass_budget_top_export_solid_mwe), ...
      'export_liquid_mwe', sum(ledger.mass_budget_top_export_liquid_mwe), ...
      'interior_merge_count', sum(ledger.mass_budget_interior_merge_count), ...
      'role', "count and height are quantized grid geometry and are never " + ...
      "mass; export_* is the mass a surface removal actually removed");

   % Closure failure takes precedence over scientific classification. Otherwise
   % a credible material-accounting alternative that changes the result makes
   % the comparison non-identifiable instead of forcing a directional claim.
   difference = a_model - a_obs;
   base_classification = classifyDifference(difference, a_model, a_obs, policy);
   if ~diagnostics.physical_comparable
      classification = "not_physically_comparable";
   elseif ~isempty(non_identifiable_reasons)
      classification = "non_identifiable";
   else
      classification = base_classification;
   end

   summary = struct( ...
      'classification', classification, ...
      'base_classification', base_classification, ...
      'physical_comparable', diagnostics.physical_comparable, ...
      'requested_window_start', window_start, ...
      'requested_window_end', window_end, ...
      'window_start', actual_start, ...
      'window_end', actual_end, ...
      'common_sample_count', nnz(in_window), ...
      'eligible_sample_count', nnz(eligible), ...
      'observation_lowering_m', h_obs, ...
      'observation_intact_mwe', a_obs, ...
      'model_solid_loss_mwe', a_model, ...
      'model_minus_observation_mwe', difference, ...
      'relative_difference', abs(difference) / signal, ...
      'endpoint_deficit_scenario_count', numel(endpoint_deficit), ...
      'non_identifiable_reasons', non_identifiable_reasons, ...
      'policy_version', policy.version);
end

function tt = comparisonTimetable(value, role)
   %COMPARISONTIMETABLE Unwrap a timetable or verification data bundle.
   if istimetable(value)
      tt = value;
   elseif isstruct(value) && isfield(value, 'data') ...
         && istimetable(value.data)
      tt = value.data;
   else
      error('icemodel:verification:compareAblation:badInput', ...
         '%s input must be a timetable or a struct with timetable data', role)
   end
end

function requireVariables(tt, required, error_id)
   %REQUIREVARIABLES Reject incomplete physical contracts with a stable ID.
   missing = setdiff(required, string(tt.Properties.VariableNames), 'stable');
   if ~isempty(missing)
      error(error_id, 'missing required field(s): %s', strjoin(missing, ', '))
   end
end

function tt = normalizeTimetable(tt, role)
   %NORMALIZETIMETABLE Normalize timestamps and reject ambiguous duplicates.
   if ~isdatetime(tt.Properties.RowTimes) || any(isnat(tt.Properties.RowTimes))
      error('icemodel:verification:compareAblation:badTime', ...
         '%s row times must be finite datetimes', role)
   end
   tt.Properties.RowTimes = icemodel.verification.setup.ensureUtc( ...
      tt.Properties.RowTimes);
   tt = sortrows(tt);
   if numel(unique(tt.Time)) ~= height(tt)
      error('icemodel:verification:compareAblation:duplicateTime', ...
         '%s timetable must have unique timestamps', role)
   end
end

function [window_start, window_end] = comparisonWindow( ...
      obs_time, model_time, requested_start, requested_end)
   %COMPARISONWINDOW Resolve explicit bounds against the available overlap.
   overlap_start = max(obs_time(1), model_time(1));
   overlap_end = min(obs_time(end), model_time(end));
   if isnat(requested_start)
      window_start = overlap_start;
   else
      window_start = icemodel.verification.setup.ensureUtc(requested_start);
   end
   if isnat(requested_end)
      window_end = overlap_end;
   else
      window_end = icemodel.verification.setup.ensureUtc(requested_end);
   end
   if window_start > window_end || window_end < overlap_start ...
         || window_start > overlap_end
      error('icemodel:verification:compareAblation:invalidWindow', ...
         'the requested comparison window does not overlap both inputs')
   end
end

function values = numericValues(tt, rows, names, role)
   %NUMERICVALUES Extract numeric comparison fields with one stable failure.
   try
      values = double(tt{rows, cellstr(names)});
   catch
      error('icemodel:verification:compareAblation:nonNumericField', ...
         '%s comparison fields must be numeric or logical', role)
   end
end

function identities = closureIdentities(ledger, policy, Ls, Lv, ro_liq)
   %CLOSUREIDENTITIES Evaluate mass, vapor-energy, and remesh identities.
   p_s = ledger.mass_budget_phase_solid_mwe;
   p_l = ledger.mass_budget_phase_liquid_mwe;
   v_s = ledger.mass_budget_vapor_solid_mwe;
   v_l = ledger.mass_budget_vapor_liquid_mwe;
   r_s = ledger.mass_budget_remesh_solid_mwe;
   r_l = ledger.mass_budget_remesh_liquid_mwe;
   d_s = ledger.mass_budget_solid_end_mwe(end) ...
      - ledger.mass_budget_solid_start_mwe(1);
   d_l = ledger.mass_budget_liquid_end_mwe(end) ...
      - ledger.mass_budget_liquid_start_mwe(1);

   % Preserve native substep/event flux throughput while testing every output
   % row. The window normalizer uses its endpoint change, not storage or net
   % remesh throughput, exactly as the accepted closure policy requires.
   p_s_q = ledger.mass_budget_phase_solid_throughput_mwe;
   p_l_q = ledger.mass_budget_phase_liquid_throughput_mwe;
   v_s_q = ledger.mass_budget_vapor_solid_throughput_mwe;
   v_l_q = ledger.mass_budget_vapor_liquid_throughput_mwe;
   r_s_q = ledger.mass_budget_remesh_solid_throughput_mwe;
   r_l_q = ledger.mass_budget_remesh_liquid_throughput_mwe;
   step_d_s = ledger.mass_budget_solid_end_mwe ...
      - ledger.mass_budget_solid_start_mwe;
   step_d_l = ledger.mass_budget_liquid_end_mwe ...
      - ledger.mass_budget_liquid_start_mwe;

   % Four checkpoint mass identities retain solid, liquid, phase, and total
   % storage views even though the total identity is intentionally redundant.
   rows(1) = identityRow("solid_storage", "mwe", ...
      d_s, step_d_s, p_s + v_s + r_s, p_s_q + v_s_q + r_s_q, ...
      policy, 1);
   rows(2) = identityRow("liquid_storage", "mwe", ...
      d_l, step_d_l, p_l + v_l + r_l, p_l_q + v_l_q + r_l_q, ...
      policy, 1);

   % Treat solid phase change as the increment and its liquid counterpart as
   % the opposing transfer. Their combined per-row residual must close; equal
   % and opposite residuals in different forcing rows cannot cancel.
   rows(3) = identityRow("phase_mass", "mwe", sum(p_s), p_s, -p_l, ...
      p_l_q, policy, 1);
   rows(4) = identityRow("total_storage", "mwe", ...
      d_s + d_l, step_d_s + step_d_l, ...
      p_s + p_l + v_s + v_l + r_s + r_l, ...
      p_s_q + p_l_q + v_s_q + v_l_q + r_s_q + r_l_q, policy, 1);

   % Vapor energy keeps solid sublimation/deposition on Ls and liquid vapor or
   % overflow on Lv; signed unapplied energy remains an explicit remainder.
   potential = ledger.mass_budget_vapor_potential_j_m2;
   overflow = ledger.mass_budget_condensation_overflow_mwe;
   unapplied = ledger.mass_budget_unapplied_vapor_j_m2;
   accepted = ro_liq .* (Ls .* v_s + Lv .* v_l + Lv .* overflow) + unapplied;
   energy_scale = ro_liq * Lv;
   vapor_q = ro_liq .* ( ...
      Ls .* ledger.mass_budget_vapor_solid_throughput_mwe ...
      + Lv .* ledger.mass_budget_vapor_liquid_throughput_mwe ...
      + Lv .* ledger.mass_budget_condensation_overflow_throughput_mwe) ...
      + ledger.mass_budget_unapplied_vapor_throughput_j_m2;
   rows(5) = identityRow("vapor_energy", "J m-2", ...
      sum(potential), potential, accepted, vapor_q, policy, energy_scale);

   % B/O decomposition is checked independently for solid, liquid, and the
   % documented mixture-enthalpy ledger.
   b_s = ledger.mass_budget_cloned_bottom_solid_mwe;
   b_l = ledger.mass_budget_cloned_bottom_liquid_mwe;
   b_h = ledger.mass_budget_cloned_bottom_enthalpy_j_m2;
   o_s = ledger.mass_budget_collapse_export_solid_mwe;
   o_l = ledger.mass_budget_collapse_export_liquid_mwe;
   o_h = ledger.mass_budget_collapse_export_enthalpy_j_m2;
   r_h = ledger.mass_budget_remesh_enthalpy_j_m2;
   rows(6) = identityRow("remesh_solid", "mwe", ...
      sum(r_s), r_s, b_s - o_s, ...
      ledger.mass_budget_cloned_bottom_solid_throughput_mwe ...
      + ledger.mass_budget_collapse_export_solid_throughput_mwe, policy, 1);
   rows(7) = identityRow("remesh_liquid", "mwe", ...
      sum(r_l), r_l, b_l - o_l, ...
      ledger.mass_budget_cloned_bottom_liquid_throughput_mwe ...
      + ledger.mass_budget_collapse_export_liquid_throughput_mwe, policy, 1);
   rows(8) = identityRow("remesh_enthalpy", "J m-2", ...
      sum(r_h), r_h, b_h - o_h, ...
      ledger.mass_budget_cloned_bottom_enthalpy_throughput_j_m2 ...
      + ledger.mass_budget_collapse_export_enthalpy_throughput_j_m2, ...
      policy, energy_scale);
   identities = struct2table(rows);
end

function row = identityRow(name, units, window_delta, step_delta, step_flux, ...
      step_flux_throughput, policy, scale)
   %IDENTITYROW Apply exact window and per-forcing-step closure acceptance.
   residual = window_delta - sum(step_flux);
   normalization = max(policy.numerical.q_floor_mwe * scale, ...
      abs(window_delta) + sum(step_flux_throughput));
   tolerance = policy.numerical.atol_mwe * scale ...
      + policy.numerical.rtol * normalization;

   % A signed window residual can vanish even when individual forcing rows do
   % not close. Test every row with the same absolute-plus-relative policy.
   step_residual = step_delta - step_flux;
   step_normalization = max(policy.numerical.q_floor_mwe * scale, ...
      abs(step_delta) + step_flux_throughput);
   step_tolerance = policy.numerical.atol_mwe * scale ...
      + policy.numerical.rtol .* step_normalization;
   window_passed = abs(residual) <= tolerance;
   step_passed = all(abs(step_residual) <= step_tolerance);
   row = struct('identity', name, 'units', units, 'residual', residual, ...
      'normalization', normalization, 'tolerance', tolerance, ...
      'window_passed', window_passed, 'step_passed', step_passed, ...
      'failed_step_count', nnz(abs(step_residual) > step_tolerance), ...
      'passed', window_passed && step_passed);
end

function materiality = materialityDiagnostics(ledger, endpoint_deficit, ...
      signal, policy, Ls, ro_liq)
   %MATERIALITYDIAGNOSTICS Preserve signed and non-cancelling channel ratios.
   d_l = ledger.mass_budget_liquid_end_mwe(end) ...
      - ledger.mass_budget_liquid_start_mwe(1);
   rows = [ ...
      materialityRow("endpoint_liquid_storage", d_l, ...
         ledger.mass_budget_liquid_storage_throughput_mwe, signal, policy); ...
      materialityRow("remesh_solid", ...
         ledger.mass_budget_remesh_solid_mwe, ...
         ledger.mass_budget_remesh_solid_throughput_mwe, signal, policy); ...
      materialityRow("remesh_liquid", ...
         ledger.mass_budget_remesh_liquid_mwe, ...
         ledger.mass_budget_remesh_liquid_throughput_mwe, signal, policy); ...
      materialityRow("merge_delete_solid", ...
         ledger.mass_budget_collapse_export_solid_mwe, ...
         ledger.mass_budget_collapse_export_solid_throughput_mwe, ...
         signal, policy); ...
      materialityRow("merge_delete_liquid", ...
         ledger.mass_budget_collapse_export_liquid_mwe, ...
         ledger.mass_budget_collapse_export_liquid_throughput_mwe, ...
         signal, policy); ...
      materialityRow("cloned_bottom_solid", ...
         ledger.mass_budget_cloned_bottom_solid_mwe, ...
         ledger.mass_budget_cloned_bottom_solid_throughput_mwe, ...
         signal, policy); ...
      materialityRow("cloned_bottom_liquid", ...
         ledger.mass_budget_cloned_bottom_liquid_mwe, ...
         ledger.mass_budget_cloned_bottom_liquid_throughput_mwe, ...
         signal, policy); ...
      materialityRow("condensation_overflow", ...
         ledger.mass_budget_condensation_overflow_mwe, ...
         ledger.mass_budget_condensation_overflow_throughput_mwe, ...
         signal, policy); ...
      materialityRow("unapplied_vapor_solid_equivalent", ...
         ledger.mass_budget_unapplied_vapor_j_m2 ./ (ro_liq * Ls), ...
         ledger.mass_budget_unapplied_vapor_throughput_j_m2 ...
         ./ (ro_liq * Ls), ...
         signal, policy)];
   % The caller's deficit list has a known length, so size the array once
   % rather than growing it per iteration.
   n_deficit = numel(endpoint_deficit);
   if n_deficit > 0
      n_fixed = numel(rows);
      rows(n_fixed + n_deficit) = rows(n_fixed);
      for n = 1:n_deficit
         rows(n_fixed + n) = materialityRow( ...
            "endpoint_deficit_" + n, endpoint_deficit(n) / ro_liq, ...
            abs(endpoint_deficit(n)) / ro_liq, signal, policy);
      end
   end
   materiality = struct2table(rows);
end

function row = materialityRow(channel, values, throughput_values, signal, policy)
   %MATERIALITYROW Score one channel without cross-channel cancellation.
   signed_net = sum(values);
   throughput = sum(throughput_values);
   row = struct('channel', channel, 'signed_net_mwe', signed_net, ...
      'throughput_mwe', throughput, 'signed_ratio', signed_net / signal, ...
      'throughput_ratio', throughput / signal, ...
      'material', throughput / signal > policy.scientific.materiality_limit);
end

function [scenarios, reasons] = scenarioDiagnostics(a_model, a_obs, ...
      endpoint_deficit, materiality, ledger, policy, Ls, ro_liq)
   %SCENARIODIAGNOSTICS Test endpoint sensitivities and accounting alternatives.
   base_difference = a_model - a_obs;
   base_class = classifyDifference(base_difference, a_model, a_obs, policy);
   rows = scenarioRow("central_intact_ice", "central", a_model, a_obs, ...
      base_difference, base_class, policy, true, true);

   % The public numeric input has no validated observation-artifact provenance.
   % Preserve each sensitivity value, but mark it unverified and non-governing.
   n_deficit = numel(endpoint_deficit);
   if n_deficit > 0
      n_fixed = numel(rows);
      rows(n_fixed + n_deficit) = rows(n_fixed);
      for n = 1:n_deficit
         scenario_obs = a_obs + endpoint_deficit(n) / ro_liq;
         rows(n_fixed + n) = scenarioRow("endpoint_deficit_" + n, ...
            "endpoint", a_model, scenario_obs, base_difference, ...
            base_class, policy, ...
            isMaterial(materiality, "endpoint_deficit_" + n), false);
      end
   end

   % Only demonstrated solid-equivalent alternatives can adjust the solid-loss
   % comparator. Liquid storage, liquid domain exchange, and overflow remain
   % explicit materiality diagnostics because no observation operator maps
   % them one-for-one onto current-window solid loss.
   scenario_names = ["remesh_solid", ...
      "merge_delete_solid", "cloned_bottom_solid", ...
      "unapplied_vapor_solid_equivalent"];
   adjustments = [-sum(ledger.mass_budget_remesh_solid_mwe), ...
      sum(ledger.mass_budget_collapse_export_solid_mwe), ...
      -sum(ledger.mass_budget_cloned_bottom_solid_mwe), ...
      -sum(ledger.mass_budget_unapplied_vapor_j_m2) / (ro_liq * Ls)];
   n_fixed = numel(rows);
   rows(n_fixed + numel(scenario_names)) = rows(n_fixed);
   for n = 1:numel(scenario_names)
      rows(n_fixed + n) = scenarioRow(scenario_names(n), "accounting", ...
         a_model + adjustments(n), a_obs, base_difference, base_class, ...
         policy, isMaterial(materiality, scenario_names(n)), true);
   end
   scenarios = struct2table(rows);

   % Only credible material accounting can govern classification. Endpoint
   % sensitivities remain diagnostic until a validated runner-derived evidence
   % path exists; caller-supplied values cannot grant themselves provenance.
   changed = scenarios.changes_sign | scenarios.changes_classification;
   governs = scenarios.role == "accounting" & scenarios.material;
   reasons = scenarios.scenario(changed & governs & scenarios.credible);
end

function row = scenarioRow(name, role, a_model, a_obs, base_difference, ...
      base_class, policy, material, credible)
   %SCENARIOROW Classify one observation or accounting alternative.
   difference = a_model - a_obs;
   classification = classifyDifference(difference, a_model, a_obs, policy);
   signal = max([abs(a_model), abs(a_obs), ...
      policy.scientific.signal_floor_mwe]);
   row = struct('scenario', name, 'role', role, ...
      'model_mwe', a_model, 'observation_mwe', a_obs, ...
      'difference_mwe', difference, ...
      'relative_difference', abs(difference) / signal, ...
      'classification', classification, ...
      'changes_sign', sign(difference) ~= sign(base_difference), ...
      'changes_classification', classification ~= base_class, ...
      'material', material, 'credible', credible);
end

function classification = classifyDifference(difference, a_model, a_obs, policy)
   %CLASSIFYDIFFERENCE Assign a neutral bias class at the fixed threshold.
   signal = max([abs(a_model), abs(a_obs), ...
      policy.scientific.signal_floor_mwe]);
   if abs(difference) / signal <= policy.scientific.materiality_limit
      classification = "within_materiality";
   elseif difference > 0
      classification = "model_high";
   else
      classification = "model_low";
   end
end

function tf = isMaterial(materiality, channel)
   %ISMATERIAL Return the non-cancelling gate for one named channel.
   idx = materiality.channel == channel;
   tf = any(materiality.material(idx));
end

function counts = exclusionCounts(in_window, eligible, obs_finite, ...
      model_finite, quality_finite, gap_bridged, station_transition, ...
      unresolved_step, step_correctable, unknown_snow, snow_censored)
   %EXCLUSIONCOUNTS Report every primary-support exclusion independently.
   counts = struct( ...
      'gap_bridged', nnz(in_window & gap_bridged), ...
      'station_transition', nnz(in_window & station_transition), ...
      'unresolved_step', nnz(in_window & unresolved_step), ...
      'step_correctable_but_unresolved', ...
         nnz(in_window & unresolved_step & step_correctable > 0), ...
      'nonfinite_observation', nnz(in_window & ~obs_finite), ...
      'unknown_quality_flag', nnz(in_window & ~quality_finite), ...
      'unknown_snow_depth', nnz(in_window & unknown_snow), ...
      'snow_censored', nnz(in_window & snow_censored), ...
      'nonfinite_model', nnz(in_window & ~model_finite), ...
      'total_unique_excluded', nnz(in_window & ~eligible));
end
