function proplist = completions(funcname)
   %COMPLETIONS function completions
   switch lower(funcname)

      case 'completions'
         tmp = dir( ...
            fullfile(icemodel.projectpath, 'functions', '+icemodel', '*.m'));
         proplist = strrep({tmp.name}, '.m', '');

      case 'cvconvert'
         proplist = {'volumefraction', 'bulkdensity', 'mass', 'volume', ...
            'massfraction', 'totaldensity'}.';

      case 'physicalconstant'
         proplist = {'Lv', 'Lf', 'Ls', 'Tf', 'ro_air', 'ro_ice', 'ro_liq', ...
            'cp_air', 'cp_liq', 'cp_ice', 'k_liq', 'k_ice', 'Rv', 'emiss', 'SB', ...
            'gravity', 'kappa', 'one_atmos', 'epsilon', 'es0', 'S0', 'N0', ...
            'psychro', 'dalr', 'malr', 'cv_air', 'cv_ice', 'cv_liq', 'fcp', ...
            'scale_ht', 'hrsperday', 'roLv', 'roLs', 'roLf', 'ro_iwe', 'ro_wie', ...
            'emissSB', 'fcpsq'}.';
   end
end
