function catalog = gcnetVandecruxCatalog()
   %GCNETVANDECRUXCATALOG The nine Vandecrux/GC-Net stations, defined once.
   %
   %  catalog = icemodel.forcing.helpers.gcnetVandecruxCatalog()
   %
   % Role
   %  Single source of the Vandecrux station identity table: canonical
   %  name, every alias spelling (including the GEUS PROMICE continuation
   %  codes, so self-donor exclusion holds through every spelling —
   %  POLICY A8), and coordinates from the dataset's own Dataverse
   %  metadata (the station table repeated identically in the three
   %  sidecar XMLs under data/verification/gcnet/; the surface NetCDFs
   %  themselves carry no location attributes). Alias normalization and
   %  metadata lookup both derive from this table and must never restate
   %  it.
   %
   % Returns
   %  catalog : 1x9 struct with fields station, aliases, site_location.
   %
   % See also: icemodel.forcing.helpers.gcnetVandecruxStation,
   %  icemodel.forcing.helpers.gcnetVandecruxStationMetadata

   entry = @(name, aliases, lat, lon, elev) struct('station', name, ...
      'aliases', aliases, 'site_location', struct('lat_wgs84', lat, ...
      'lon_wgs84', lon, 'elev_m', elev));
   catalog = [ ...
      entry("DYE_2", ["DYE_2", "Dye_2", "DY2", "dye2_long", "dye2"], ...
         66.48, -46.28, 2165), ...
      entry("Summit", ["Summit", "SUM", "sum", "summit"], ...
         72.58, -38.50, 3254), ...
      entry("CP1", ["CP1", "cp1", "CrawfordPoint1"], ...
         69.88, -46.99, 2022), ...
      entry("NASA_E", ["NASA_E", "NASA-E", "nasae", "NAE", "nae"], ...
         75.00, -30.00, 2631), ...
      entry("NASA_SE", ["NASA_SE", "NASA-SE", "nasase", "NSE", "nse"], ...
         66.48, -42.50, 2425), ...
      entry("NASA_U", ["NASA_U", "NASA-U", "nasau", "NAU", "nau"], ...
         73.84, -49.50, 2369), ...
      entry("Saddle", ["Saddle", "saddle", "SDL", "sdl"], ...
         66.00, -44.50, 2559), ...
      entry("SouthDome", ["SouthDome", "South_Dome", "SDM", "sdm"], ...
         63.15, -44.82, 2922), ...
      entry("TUNU_N", ["TUNU_N", "Tunu_N", "TUNU-N", "tunun", ...
         "TUN", "tun"], 78.02, -33.99, 2113)];
end
