function proj = geusModisProjection()
   %GEUSMODISPROJECTION Native polar-stereographic projection of the GEUS grid.
   %
   %  proj = icemodel.forcing.helpers.geusModisProjection()
   %
   % Returns the projection in which the GEUS Greenland reflectivity (MODIS
   % albedo) 5 km grid is regular, as a projcrs usable with projfwd / projinv.
   %
   % The Greenland_Reflectivity_<YYYY>_5km_C6.nc files carry only 2-D lon/lat
   % coordinate grids (no native x/y vectors, no CRS attributes). The posting
   % is documented in the accompanying MapProjektion.txt: Polar Stereographic
   % on a sphere (radius 6 370 000 m), latitude of true scale 71N, central
   % meridian 39W, on a 301 x 561 grid of 5 km cells. There is no standard
   % EPSG code for this frame, so it is built from a WKT string.
   %
   % See also: icemodel.forcing.readGeusModis,
   %  icemodel.forcing.helpers.psnProjection, projfwd, projinv

   wkt = [ ...
      'PROJCRS["GEUS Greenland Reflectivity 5km PS",' ...
      'BASEGEOGCRS["Sphere",' ...
      'DATUM["Sphere",ELLIPSOID["Sphere",6370000,0,LENGTHUNIT["metre",1]]],' ...
      'PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]]],' ...
      'CONVERSION["Polar Stereographic",' ...
      'METHOD["Polar Stereographic (variant B)",ID["EPSG",9829]],' ...
      'PARAMETER["Latitude of standard parallel",71,' ...
      'ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8832]],' ...
      'PARAMETER["Longitude of origin",-39,' ...
      'ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8833]],' ...
      'PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],' ...
      'PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],' ...
      'CS[Cartesian,2],' ...
      'AXIS["easting (X)",north,ORDER[1],LENGTHUNIT["metre",1]],' ...
      'AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]]]'];
   proj = projcrs(wkt);
end
