function [data, metadata] = readImauHourlyTable(filename)
   %READIMAUHOURLYTABLE Parse one IMAU hourly PANGAEA AWS table.
   %
   %  [data, metadata] = icemodel.forcing.helpers.readImauHourlyTable(filename)
   %
   % Role
   %  Source-specific parser for the Van Tiggelen et al. PANGAEA hourly IMAU
   %  S21/S22/S23 files. The shared PANGAEA ingest skips the metadata block and
   %  reads positional rows; this parser maps corrected meteorological channels
   %  to icemodel-native names and preserves source metadata needed by
   %  staging/import manifests.

   arguments
      filename (1, 1) string
   end

   % Shared PANGAEA ingest: positional rows, source labels, and the citation /
   % DOI / Event(s) metadata. Keep this parser's established error id for a
   % missing tabular section.
   [raw, header, source] = icemodel.forcing.helpers.readPangaeaTab( ...
      filename, site_id_pattern='\((S[0-9]+)\)', ...
      missing_header_error_id='icemodel:forcing:readImauHourlyTable:missingHeader');

   % S22/S23 encode a missing derived surface temperature as -1273.05 degC.
   % Normalize that source sentinel before converting the physical values to K;
   % otherwise it makes metchecks misclassify the whole Kelvin series as Celsius.
   tsfc = raw.col26;
   tsfc(tsfc == -1273.05) = NaN;

   % Map duplicate PANGAEA column labels by stable position. The source tables
   % use repeated Height/Surface elevation names, so sanitized headers alone are
   % not enough to identify variables safely.
   time = datetime(raw.col1, 'InputFormat', "yyyy-MM-dd'T'HH:mm:ss", ...
      'TimeZone', 'UTC');
   data = timetable(time, ...
      raw.col2, raw.col3, ...
      raw.col5 + 273.15, ...
      raw.col9, ...
      raw.col11, ...
      raw.col12, ...
      raw.col13 * 100, ...
      raw.col14, raw.col15, raw.col16, raw.col17, ...
      raw.col18, raw.col19, raw.col20, raw.col21, raw.col22, ...
      raw.col23, raw.col24, raw.col25, tsfc + 273.15, ...
      'VariableNames', {'height_1', 'height_2', 'tair', 'rh', ...
      'wspd', 'wdir', 'psfc', 'swd', 'swu', 'lwd', 'lwu', ...
      'surface_elevation_raw', 'surface_elevation', ...
      'surface_height_change_sonic', 'surface_height_change', ...
      'boom_height', 'lat_wgs84', 'lon_wgs84', 'albedo', 'tsfc'});
   data.Properties.DimensionNames{1} = 'time';

   % S22/S23 include an ablation draw-wire length column; S21 does not.
   if width(raw) >= 27
      data.wire_length = raw.col27;
   end

   % Preserve source metadata and row-derived coordinate summaries for later
   % staging without pretending row-varying coordinates are one exact point.
   metadata = struct( ...
      'filename', source.filename, ...
      'site_id', source.site_id, ...
      'citation', source.citation, ...
      'doi', source.doi, ...
      'bundle_doi', source.bundle_doi, ...
      'raw_headers', header, ...
      'event', source.event, ...
      'row_summary', rowSummary(data), ...
      'variables', string(data.Properties.VariableNames));
end

function summary = rowSummary(data)
   %ROWSUMMARY Capture row-derived coordinate and period ranges.
   summary = struct( ...
      'period', struct('start', data.time(1), 'end', data.time(end)), ...
      'lat_min', min(data.lat_wgs84, [], 'omitnan'), ...
      'lat_median', median(data.lat_wgs84, 'omitnan'), ...
      'lat_max', max(data.lat_wgs84, [], 'omitnan'), ...
      'lon_min', min(data.lon_wgs84, [], 'omitnan'), ...
      'lon_median', median(data.lon_wgs84, 'omitnan'), ...
      'lon_max', max(data.lon_wgs84, [], 'omitnan'));
end
