function [ice1, ice2, opts] = icemodel(opts)
   % ICEMODEL Simulate the phase change process in glacier ice.
   %
   % This function models the phase change process in melting glacier ice. It
   % uses iterative processes to update the temperature, liquid and ice fraction
   % at each time step. This model considers both the surface and subsurface
   % energy balance to simulate the phase change.
   %
   % Syntax:
   % [ice1, ice2] = ICEMODEL(opts)
   % [ice1, ice2, opts] = ICEMODEL(opts)
   %
   % Inputs:
   % opts - A structure containing model options and parameters. Defined by the
   %        icemodel.setopts function. The fields include:
   %        * sitename         - Site name for the model simulation
   %        * smbmodel         - Simulation model identifier
   %        * simyears         - Years for which the simulation is done
   %        * forcings         - Type of forcing data used
   %        * userdata         - User-defined data type
   %        * uservars         - User-defined variables
   %        * saveflag         - Flag indicating if data should be saved
   %        * testname         - Name of the test (default: 'none')
   %        * ... (other parameters related to the model configuration)
   %
   % Outputs:
   % ice1  - 1-dimensional data storing variables defined at the ice surface or
   %         near-surface atmosphere. Contains one value per timestep.
   % ice2  - 2-dimensional data storing variables defined on the subsurface ice
   %         column control volume mesh. Contains one column per timestep.
   % opts  - Finalized runtime configuration after icemodel.configureRun() has
   %         applied the last non-negotiable pre-execution updates.
   %
   % See also: skinmodel, icemodel.setopts
   %
   %#codegen

   %% INITIALIZE THE MODEL

   % Runtime configuration
   assertF on
   opts = icemodel.configureRun(opts);
   opts = icemodel.prepareRunOutput(opts);

   TINY = 1e-8;

   % UNPACK SOLVER OPTS
   [solver, maxiter, tol, alpha, use_aitken, jumpmax, cpl_maxiter, ...
      cpl_Ts_tol, cpl_seb_tol, cpl_alpha, cpl_aitken, cpl_jumpmax] ...
      = icemodel.getopts(opts, ...
      'solver', 'maxiter', 'tol', 'alpha', 'use_aitken', 'jumpmax', ...
      'cpl_maxiter', 'cpl_Ts_tol', 'cpl_seb_tol', 'cpl_alpha', 'cpl_aitken', ...
      'cpl_jumpmax');

   % INITIALIZE THE FORCING DATA
   [tair, swd, lwd, albedo, wspd, rh, psfc, ppt, tppt, time, forcing_snow_depth] ...
      = icemodel.surface.initialize_surface_forcings(opts);

   % INITIALIZE THE SURFACE TURBULENT EXCHANGE MODEL (bulk Richardson)
   [De, br_coefs] ...
      = icemodel.surface.turbulence.bulk_richardson.exchange_coefficients( ...
      wspd, opts.z0_bulk, opts.z_tair, opts.z_wind);

   % INITIALIZE THE SPECTRAL MODEL
   [I0, dz_spect, z_nodes_spect, z_edges_spect, tau_N, tau_S, solar_dwavel, ...
      k_bulk_lookup, r_eff] = icemodel.radiation.initialize_spectral_model(opts);

   % INITIALIZE THE THERMAL MODEL
   [ice1, ice2, T_sfc, T_ice, f_ice, f_liq, r_eff, k_eff, fn, dz, delz, ...
      z_nodes, roL, liqflag, ~, ~, Sp, ~, ~, ~, ~, ~, ~, f_ice_min, ...
      f_liq_res] = icemodel.column.initialize_column_state( ...
      opts, tair, r_eff);

   % INITIALIZE TIMESTEPPING
   [metstep, substep, numsteps, maxsubstep, dt, dt_FULL_STEP, numyears, ...
      numspinup] = icemodel.timestepping.initialize_timesteps(opts, time);

   if ~opts.saveflag && (numyears - numspinup) > 1
      ice1_all = [];
      ice2_all = [];
   end

   % INITIALIZE PAST VALUES
   [xT_sfc, xT_ice, xf_ice, xf_liq] = icemodel.timestepping.resetsubstep( ...
      T_sfc, T_ice, f_ice, f_liq);
   force_advance_streak_dt = 0.0;

   %% START TIMESTEPS OVER YEARS
   for thisyear = 1:numyears

      for timestep = 1:numsteps

         % INITIALIZE NEW TIMESTEP
         [dt_sum, n_subfail, ok_seb, ok_ieb, d_liq, d_evp, d_lyr] ...
            = icemodel.timestepping.newtimestep(f_liq, solver);

         % SUBSURFACE SOLAR RADIATION SOURCE-TERM
         [Sc, chi] = icemodel.column.shortwave_source_term(swd(metstep), ...
            albedo(metstep), I0, dz_spect, tau_N, tau_S, solar_dwavel, ...
            dz, icemodel.column.bulk_density(f_ice, f_liq), z_nodes, ...
            z_nodes_spect, z_edges_spect, k_bulk_lookup);

         % SURFACE TERMS (atmospheric vapor pressure fixed over this full step)
         ea_atm = icemodel.surface.atmospheric_vapor_pressure( ...
            tair(metstep), rh(metstep), liqflag);

         snow_depth = icemodel.surface.resolve_forcing_snow_depth( ...
            forcing_snow_depth, metstep, opts.use_forcing_snow_depth_for_thf);

         while dt_sum + TINY < dt_FULL_STEP

            % Update surface density for the surface turbulent heat flux scheme.
            ro_sfc = icemodel.surface.surface_bulk_density(f_ice(1), f_liq(1));

            if solver == 1 % Coupled Dirichlet surface-subsurface solve

               % COUPLED DIRICHLET SURFACE-SUBSURFACE ENERGY BALANCE
               [T_sfc, T_ice, f_ice, f_liq, k_eff, ok_seb, ok_ieb, ok, n_iters] ...
                  = icemodel.couplers.solve_surface_column_dirichlet( ...
                  T_sfc, T_ice, f_ice, f_liq, dz, delz, fn, Sc, Sp, dt, ...
                  tair(metstep), swd(metstep), lwd(metstep), albedo(metstep), ...
                  wspd(metstep), ppt(metstep), tppt(metstep), psfc(metstep), ...
                  De(metstep), ea_atm, br_coefs, roL, liqflag, chi, solver, ...
                  tol, maxiter, alpha, use_aitken, jumpmax, cpl_Ts_tol, ...
                  cpl_seb_tol, cpl_maxiter, cpl_alpha, cpl_aitken, ...
                  cpl_jumpmax, ro_sfc, snow_depth, opts);

            elseif solver > 1 % Robin single-sweep and strong coupling modes

               % COUPLED ROBIN SURFACE-SUBSURFACE ENERGY BALANCE
               [T_sfc, T_ice, f_ice, f_liq, k_eff, ok_ieb, n_iters] ...
                  = icemodel.couplers.solve_surface_column_robin( ...
                  T_sfc, T_ice, f_ice, f_liq, dz, delz, fn, Sc, Sp, dt, ...
                  tair(metstep), swd(metstep), lwd(metstep), albedo(metstep), ...
                  wspd(metstep), ppt(metstep), tppt(metstep), psfc(metstep), ...
                  De(metstep), ea_atm, br_coefs, roL, liqflag, chi, solver, ...
                  tol, maxiter, alpha, use_aitken, jumpmax, cpl_Ts_tol, ...
                  cpl_seb_tol, cpl_maxiter, cpl_alpha, cpl_aitken, ...
                  cpl_jumpmax, ro_sfc, snow_depth, opts);
               ok = ok_seb && ok_ieb;
            end

            % CHECK SUBSTEP FAILURE (shorten dt and restart substep on failure)
            [T_sfc, T_ice, f_ice, f_liq, n_subfail, substep, dt, ok, ...
               forced_advance] ...
               = icemodel.timestepping.checksubstep(T_sfc, T_ice, f_ice, ...
               f_liq, xT_sfc, xT_ice, xf_ice, xf_liq, dt_sum, dt, ...
               dt_FULL_STEP, timestep, numsteps, substep, maxsubstep, ...
               n_subfail, opts.debug, eps, ok, force_advance_streak_dt, ...
               dt_FULL_STEP);

            if ~ok
               continue
            end

            force_advance_streak_dt = ...
               icemodel.timestepping.update_force_advance_guard( ...
               force_advance_streak_dt, forced_advance, dt, dt_FULL_STEP, ...
               timestep, numsteps, 'icemodel');

            % UPDATE POTENTIAL SURFACE NET VAPOR FLUX
            [d_pevp, ~, ~, ~] ...
               = icemodel.surface.potential_surface_vapor_tendency( ...
               T_sfc, tair(metstep), wspd(metstep), psfc(metstep), ...
               ea_atm, De(metstep), br_coefs, snow_depth, f_ice(1), f_liq(1), ...
               dt, dz(1), roL, liqflag, opts);

            % UPDATE THE SURFACE MASS-BALANCE BUDGETS
            [T_ice, f_ice, f_liq, d_liq, d_evp] = ...
               icemodel.column.budget_surface_mass_balance(T_ice, f_ice, ...
               f_liq, xf_liq, d_pevp, d_liq, d_evp, f_liq_res, f_ice_min);

            % REMESH THIN LAYERS AFTER THE MASS-BALANCE UPDATE
            [T_ice, f_ice, f_liq, Sc, Sp, d_lyr, ~] = ...
               icemodel.column.merge_thin_layers(T_ice, f_ice, f_liq, Sc, ...
               Sp, dz(1), d_pevp, d_lyr, f_ice_min);

            % CHECKPOINT STATE AND SUBSTEP TIME
            [xT_sfc, xT_ice, xf_ice, xf_liq, dt_sum, dt, liqflag, roL] ...
               = icemodel.timestepping.updatesubstep(T_sfc, T_ice, f_ice, ...
               f_liq, dt_FULL_STEP, dt_sum, dt, TINY);
         end

         % Error if dt accumulation exceeds full step
         assertF(@() dt_sum < dt_FULL_STEP + 2 * TINY)

         % UPDATE GRAIN SIZE VIA VAPOR MASS TRANSFER
         r_eff = icemodel.column.vapor_mass_transfer(T_ice, T_sfc, f_ice, ...
            f_liq, r_eff, dz, delz, fn, dt_FULL_STEP);

         % Update surface density for the surface turbulent heat flux scheme.
         ro_sfc = icemodel.surface.surface_bulk_density(f_ice(1), f_liq(1));

         % DIAGNOSE SURFACE ENERGY BALANCE
         [Qe, Qh, Qc, Qsn, Qln, Qa, Qm, Qf, Qbal] = ...
            icemodel.surface.diagnose_surface_energy_balance(T_sfc, ...
            tair(metstep), swd(metstep), lwd(metstep), albedo(metstep), ...
            wspd(metstep), ppt(metstep), tppt(metstep), psfc(metstep), ...
            De(metstep), ea_atm, T_ice, k_eff, dz, roL, chi, br_coefs, ...
            ro_sfc, snow_depth, liqflag, opts);

         if strcmp(opts.output_profile, 'diagnostic')
            [~, ~, thf_diag] = ...
               icemodel.surface.diagnose_turbulent_heat_fluxes( ...
               icemodel.surface.physical_surface_temperature(T_sfc), ...
               tair(metstep), wspd(metstep), psfc(metstep), ea_atm, ...
               De(metstep), br_coefs, ro_sfc, snow_depth, roL, liqflag, ...
               opts);
         else
            thf_diag = struct([]);
         end

         % SAVE OUTPUT IF SPINUP IS FINISHED
         if thisyear > numspinup

            surface_state = struct( ...
               'Tsfc', T_sfc, ...
               'Qm', Qm, ...
               'Qf', Qf, ...
               'Qe', Qe, ...
               'Qh', Qh, ...
               'Qc', Qc, ...
               'Qsn', Qsn, ...
               'Qln', Qln, ...
               'Qa', Qa, ...
               'chi', chi, ...
               'balance', Qbal, ...
               'dt_sum', dt_sum, ...
               'Tsfc_converged', ok_seb, ...
               'Tice_converged', ok_ieb, ...
               'Tice_numiter', n_iters, ...
               'n_subfail', n_subfail, ...
               'ea_atm', ea_atm, ...
               'De', De(metstep), ...
               'br_coefs_gamma', br_coefs(1), ...
               'br_coefs_b1_num', br_coefs(2), ...
               'br_coefs_b2_num', br_coefs(3), ...
               'roL', roL, ...
               'ro_sfc', ro_sfc);

            subsurface_state = struct( ...
               'Tice', T_ice, ...
               'f_ice', f_ice, ...
               'f_liq', f_liq, ...
               'df_liq', d_liq, ...
               'df_evp', d_evp, ...
               'df_lyr', d_lyr, ...
               'Sc', Sc, ...
               'r_eff', r_eff);

            [data1, data2] = icemodel.buildOutputPayload(opts, surface_state, ...
               subsurface_state, thf_diag);

            [ice1, ice2] = SAVEOUTPUT(timestep, ice1, ice2, ...
               opts.vars1, opts.vars2, data1, data2);
         end

         % MOVE TO THE NEXT TIMESTEP
         [metstep, substep, dt] = icemodel.timestepping.nexttimestep( ...
            metstep, substep, dt_FULL_STEP, maxsubstep, ok, n_subfail, n_iters);

      end % timesteps (one year)

      if isfield(opts, 'saverestart') && opts.saverestart
         icemodel.saveRestartState(opts, opts.simyears(thisyear), ...
            T_ice, f_ice, f_liq, T_sfc, r_eff);
      end

      % RESTART THE MET DATA STEP INDEX DURING SPIN UP
      if thisyear <= numspinup
         continue
      end

      % Concatenate yearly raw output when running multi-year simulations
      % without writing each year to disk.
      if ~opts.saveflag && numyears - numspinup > 1
         [ice1_all, ice2_all] = icemodel.concatoutput(ice1_all, ice2_all, ...
            ice1, ice2);
      end

      % WRITE TO DISK
      yridx = (thisyear-1)*numsteps+1:thisyear*numsteps;
      WRITEOUTPUT(ice1, ice2, opts, thisyear, ...
         time(yridx), swd(yridx), lwd(yridx), albedo(yridx))
   end

   if ~opts.saveflag && numyears - numspinup > 1
      ice1 = ice1_all;
      ice2 = ice2_all;
   end
end
