function [ice1, ice2, opts] = skinmodel(opts)
   %SKINMODEL Surface energy balance model for glacier ice.
   %
   % [ice1, ice2] = SKINMODEL(opts)
   % [ice1, ice2, opts] = SKINMODEL(opts)
   %
   % OPTS is returned so callers can inspect the finalized runtime
   % configuration after icemodel.configureRun() has resolved derived fields.
   % See also: icemodel, icemodel.setopts
   %
   %#codegen

   %% INITIALIZE THE MODEL

   assertF off
   opts = icemodel.configureRun(opts);
   opts = icemodel.prepareRunOutput(opts);

   % LOAD PHYSICAL CONSTANTS AND PARAMETERS
   [cv_air, cv_ice, cv_liq, SB, epsilon, k_liq, Ls, ro_air, ...
      ro_ice, ro_liq, roLs, roLv, Rv, Tf] = icemodel.physicalConstant( ...
      'cv_air', 'cv_ice', 'cv_liq', 'SB', 'epsilon', 'k_liq', ...
      'Ls', 'ro_air', 'ro_ice', 'ro_liq', 'roLs', 'roLv', 'Rv', 'Tf');
   emiss = icemodel.parameterLookup('emiss');
   TINY = 1e-8;
   chi = 1.0;

   % LOAD THE FORCING DATA
   [tair, swd, lwd, albedo, wspd, rh, psfc, ppt, tppt, De, scoef, time] ...
      = METINIT(opts);

   % INITIALIZE THE THERMAL MODEL
   r_eff = 0;
   [ice1, ice2, T_sfc, T_ice, f_ice, f_liq, r_eff, k_eff, fn, dz, delz, ...
      ~, roL, liqflag, JJ] = ICEINIT(opts, tair, r_eff);

   % INITIALIZE TIMESTEPPING
   [metstep, substep, numsteps, maxsubstep, dt, dt_FULL_STEP, ...
      numyears, numspinup] = INITTIMESTEPS(opts, time);
   if ~opts.saveflag && numyears - numspinup > 1
      ice1_all = [];
      ice2_all = [];
   end

   % INITIALIZE PAST VALUES
   [xT_sfc, xT_ice, xf_ice, xf_liq] = RESETSUBSTEP(T_sfc, T_ice, f_ice, f_liq);

   % UNPACK SOLVER OPTS
   [solver, seb_solver, cpl_maxiter, cpl_Ts_tol, cpl_seb_tol, ...
      cpl_alpha, cpl_aitken, cpl_jumpmax, maxiter, tol, alpha, ~, ~] ...
      = icemodel.getopts(opts, ...
      'solver', 'seb_solver', 'cpl_maxiter', 'cpl_Ts_tol', 'cpl_seb_tol', ...
      'cpl_alpha', 'cpl_aitken', 'cpl_jumpmax', 'maxiter', 'tol', 'alpha', ...
      'use_aitken', 'jumpmax');

   %% START TIMESTEPS OVER YEARS
   for thisyear = 1:numyears

      for timestep = 1:numsteps

         % INITIALIZE NEW TIMESTEP
         [dt_sum, n_subfail, ok_seb, ok_ieb] = NEWTIMESTEP(f_liq, solver);

         % SURFACE TERMS (atmospheric vapor pressure fixed over this full step)
         ea = icemodel.surface.atmospheric_vapor_pressure(tair(metstep), ...
            rh(metstep), liqflag);
         snow_depth = 0.0;

         while dt_sum + TINY < dt_FULL_STEP

            % Update surface density for the surface turbulent heat flux scheme.
            ro_sfc = icemodel.surface.surface_bulk_density(xf_ice(1), xf_liq(1));

            % COUPLED SURFACE-SUBSURFACE ENERGY BALANCE
            [T_sfc, T_ice, f_ice, f_liq, k_eff, ok_seb, ok_ieb, ok, n_iters] ...
               = SKINEBSOLVE(xT_sfc, xT_ice, xf_ice, xf_liq, dz, delz, fn, dt, JJ, ...
               ro_ice, k_liq, cv_ice, cv_liq, Ls, Tf, tair(metstep), ...
               swd(metstep), lwd(metstep), albedo(metstep), wspd(metstep), ...
               ppt(metstep), tppt(metstep), psfc(metstep), De(metstep), ...
               ea, cv_air, emiss, SB, chi, roL, scoef, liqflag, seb_solver, ...
               tol, maxiter, alpha, cpl_maxiter, cpl_Ts_tol, cpl_seb_tol, ...
               cpl_alpha, cpl_aitken, cpl_jumpmax, opts.debug, ...
               ro_sfc, snow_depth, opts);

            % CHECK SUBSTEP FAILURE (shorten dt and restart substep on failure)
            [T_sfc, T_ice, f_ice, f_liq, n_subfail, substep, dt, ok] = ...
               CHECKSUBSTEP(T_sfc, T_ice, f_ice, f_liq, xT_sfc, xT_ice, xf_ice, xf_liq, ...
               ro_ice, ro_liq, dt_sum, dt, dt_FULL_STEP, timestep, numsteps, ...
               substep, maxsubstep, n_subfail, opts.debug, eps, ok);
            if not(ok)
               continue
            end

            % CHECKPOINT STATE AND SUBSTEP TIME
            [xT_sfc, xT_ice, xf_ice, xf_liq, dt_sum, dt, liqflag, roL] ...
               = UPDATESUBSTEP(T_sfc, T_ice, f_ice, f_liq, dt_FULL_STEP, dt_sum, ...
               dt, TINY, ro_ice, ro_liq, ro_air, cv_ice, cv_liq, roLv, roLs);
         end

         % Error if dt accumulation exceeds full step
         assertF(@() dt_sum < dt_FULL_STEP + 2 * TINY)

         % DIAGNOSE SURFACE FLUXES
         ro_sfc = icemodel.surface.surface_bulk_density(f_ice(1), f_liq(1));
         if strcmp(opts.output_profile, 'diagnostic')
            [Qe, Qh, Qc, Qm, ~, Qbal, thf_diag] = SEBFLUX(T_ice, T_sfc, ...
               tair(metstep), swd(metstep), lwd(metstep), ...
               albedo(metstep), wspd(metstep), ppt(metstep), ...
               tppt(metstep), psfc(metstep), De(metstep), ea, Tf, k_eff, ...
               dz, roL, chi, scoef, liqflag, ro_sfc, snow_depth, opts);
         else
            [Qe, Qh, Qc, Qm, ~, Qbal] = SEBFLUX(T_ice, T_sfc, ...
               tair(metstep), swd(metstep), lwd(metstep), ...
               albedo(metstep), wspd(metstep), ppt(metstep), ...
               tppt(metstep), psfc(metstep), De(metstep), ea, Tf, k_eff, ...
               dz, roL, chi, scoef, liqflag, ro_sfc, snow_depth, opts);
            thf_diag = struct([]);
         end

         % SAVE OUTPUT IF SPINUP IS FINISHED
         if thisyear > numspinup

            surface_state = struct( ...
               'Tsfc', T_sfc, ...
               'Qm', Qm, ...
               'Qe', Qe, ...
               'Qh', Qh, ...
               'Qc', Qc, ...
               'chi', chi, ...
               'balance', Qbal, ...
               'dt_sum', dt_sum, ...
               'Tsfc_converged', ok_seb, ...
               'Tice_converged', ok_ieb, ...
               'Tice_numiter', n_iters, ...
               'n_subfail', n_subfail, ...
               'ea', ea, ...
               'De', De(metstep), ...
               'scoef_gamma', scoef(1), ...
               'scoef_b1_num', scoef(2), ...
               'scoef_b2_num', scoef(3), ...
               'roL', roL, ...
               'ro_sfc', ro_sfc);
            subsurface_state = struct( ...
               'Tice', T_ice, ...
               'f_ice', f_ice, ...
               'f_liq', f_liq);
            [data1, data2] = icemodel.buildOutputPayload(opts, surface_state, ...
               subsurface_state, thf_diag);
            [ice1, ice2] = SAVEOUTPUT(timestep, ice1, ice2, ...
               opts.vars1, opts.vars2, data1, data2);
         end

         % MOVE TO THE NEXT TIMESTEP
         [metstep, substep, dt] = NEXTSTEP(metstep, substep, dt_FULL_STEP, ...
            maxsubstep, ok, n_subfail, n_iters);

      end % timesteps (one year)

      if isfield(opts, 'saverestart') && opts.saverestart
         icemodel.saveRestartState(opts, opts.simyears(thisyear), ...
            T_ice, f_ice, f_liq, T_sfc, r_eff);
      end

      % RESTART THE MET DATA STEP INDEX DURING SPIN UP
      if thisyear <= numspinup
         continue
      end

      % Concatenate yearly raw output when running multi-year simulations
      % without writing each year to disk.
      if ~opts.saveflag && numyears - numspinup > 1
         [ice1_all, ice2_all] = icemodel.concatoutput(ice1_all, ice2_all, ...
            ice1, ice2);
      end

      % WRITE TO DISK
      yridx = (thisyear-1)*numsteps+1:thisyear*numsteps;
      WRITEOUTPUT(ice1, ice2, opts, thisyear, ...
         time(yridx), swd(yridx), lwd(yridx), albedo(yridx))
   end

   if ~opts.saveflag && numyears - numspinup > 1
      ice1 = ice1_all;
      ice2 = ice2_all;
   end
end
