function [ice1, ice2, opts] = skinmodel(opts)
   %SKINMODEL Surface energy balance model for glacier ice.
   %
   % [ice1, ice2] = SKINMODEL(opts)
   % [ice1, ice2, opts] = SKINMODEL(opts)
   %
   % OPTS is returned so callers can inspect the finalized runtime
   % configuration after icemodel.configureRun() has resolved derived fields.
   % See also: icemodel, icemodel.setopts
   %
   %#codegen

   %% INITIALIZE THE MODEL

   assertF off
   opts = icemodel.configureRun(opts);
   opts = icemodel.prepareRunOutput(opts);

   TINY = 1e-8;
   chi = 1.0;

   % UNPACK SOLVER OPTS
   [solver, ~, cpl_maxiter, cpl_Ts_tol, cpl_seb_tol, ...
      cpl_alpha, cpl_aitken, cpl_jumpmax, maxiter, tol, alpha, ~, ~] ...
      = icemodel.getopts(opts, ...
      'solver', 'seb_solver', 'cpl_maxiter', 'cpl_Ts_tol', 'cpl_seb_tol', ...
      'cpl_alpha', 'cpl_aitken', 'cpl_jumpmax', 'maxiter', 'tol', 'alpha', ...
      'use_aitken', 'jumpmax');

   % INITIALIZE THE FORCING DATA
   [tair, swd, lwd, albedo, wspd, ...
      rh, psfc, ppt, tppt, time, forcing_snow_depth] ...
      = icemodel.surface.initialize_surface_forcings(opts);

   % INITIALIZE THE THERMAL MODEL
   r_eff = 0;
   [ice1, ice2, T_sfc, T_ice, f_ice, f_liq, ~, ~, r_eff, k_eff, fn, dz, delz] ...
      = icemodel.column.initialize_column_state(opts, tair, r_eff);

   % INITIALIZE THE SURFACE STATE
   [ea_atm, ro_atm, cv_atm, nu_air, H_h, De_e, br_coefs] ...
      = icemodel.surface.initialize_surface_state(opts, tair, wspd, rh, psfc);

   % INITIALIZE TIMESTEPPING
   [metstep, substep, numsteps, ...
      maxsubstep, dt, dt_FULL_STEP, numyears, numspinup] ...
      = icemodel.timestepping.initialize_timesteps(opts, time);

   if ~opts.saveflag && numyears - numspinup > 1
      ice1_all = [];
      ice2_all = [];
   end

   % INITIALIZE PAST VALUES
   [xT_sfc, xT_ice, xf_ice, xf_liq] ...
      = icemodel.timestepping.resetsubstep(T_sfc, T_ice, f_ice, f_liq);

   force_advance_streak_dt = 0.0;

   %% START TIMESTEPS OVER YEARS
   for thisyear = 1:numyears

      for timestep = 1:numsteps

         % INITIALIZE NEW TIMESTEP
         [dt_sum, n_subfail, ok_seb, ok_ieb] ...
            = icemodel.timestepping.newtimestep(f_liq, solver);

         snow_depth = icemodel.surface.resolve_forcing_snow_depth( ...
            forcing_snow_depth, metstep, opts.use_forcing_snow_depth_for_thf);

         while dt_sum + TINY < dt_FULL_STEP

            % UPDATE SURFACE STATE FOR CURRENT FORCING AND COLUMN STATE
            [liqflag, ro_sfc, hv_atm, H_e, ~] = ...
               icemodel.surface.update_surface_state( ...
               f_ice(1), f_liq(1), ro_atm(metstep), ...
               De_e(metstep), snow_depth, opts);

            % COUPLED SURFACE-SUBSURFACE ENERGY BALANCE
            [T_sfc, T_ice, f_ice, f_liq, k_eff, ok_seb, ok_ieb, ok_cpl, n_iters] ...
               = icemodel.couplers.solve_skin_surface_column( ...
               xT_sfc, xT_ice, xf_ice, xf_liq, dz, delz, fn, dt, ...
               tair(metstep), swd(metstep), lwd(metstep), ...
               albedo(metstep), wspd(metstep), ppt(metstep), ...
               tppt(metstep), psfc(metstep), ea_atm(metstep), ...
               ro_atm(metstep), cv_atm(metstep), nu_air(metstep), ...
               H_h(metstep), H_e, hv_atm, br_coefs, liqflag, chi, ...
               tol, maxiter, alpha, cpl_maxiter, cpl_Ts_tol, ...
               cpl_seb_tol, cpl_alpha, cpl_aitken, cpl_jumpmax, ...
               ro_sfc, snow_depth, opts);

            % Hitting max coupling iterations without ok_cpl is a substep fail.
            ok = ok_seb && ok_ieb && ok_cpl;

            % CHECK SUBSTEP FAILURE (shorten dt and restart substep on failure)
            [T_sfc, T_ice, f_ice, f_liq, n_subfail, substep, dt, ok, ...
               ~, force_advance_streak_dt] ...
               = icemodel.timestepping.checksubstep(T_sfc, T_ice, f_ice, f_liq, ...
               xT_sfc, xT_ice, xf_ice, xf_liq, dt_sum, dt, dt_FULL_STEP, ...
               timestep, numsteps, substep, maxsubstep, n_subfail, ...
               opts.debug, eps, ok, force_advance_streak_dt, dt_FULL_STEP, ...
               'skinmodel');

            if ~ok
               continue
            end

            % CHECKPOINT STATE AND SUBSTEP TIME
            [xT_sfc, xT_ice, xf_ice, xf_liq, dt_sum, dt] = ...
               icemodel.timestepping.updatesubstep( ...
               T_sfc, T_ice, f_ice, f_liq, ...
               dt_FULL_STEP, dt_sum, dt, TINY);
         end

         % Error if dt accumulation exceeds full step
         assertF(@() dt_sum < dt_FULL_STEP + 2 * TINY)

         % DIAGNOSE SURFACE ENERGY BALANCE
         [Qe, Qh, Qc, Qsn, Qln, Qa, Qm, Qf, Qbal] ...
            = icemodel.surface.diagnose_surface_energy_balance(T_sfc, ...
            tair(metstep), swd(metstep), lwd(metstep), albedo(metstep), ...
            wspd(metstep), ppt(metstep), tppt(metstep), psfc(metstep), ...
            ea_atm(metstep), ro_atm(metstep), cv_atm(metstep), nu_air(metstep), ...
            H_h(metstep), H_e, hv_atm, br_coefs, liqflag, chi, T_ice, ...
            k_eff, dz, ro_sfc, snow_depth, opts);

         if strcmp(opts.output_profile, 'diagnostic')
            [~, ~, thf_diag] ...
               = icemodel.surface.diagnose_turbulent_heat_fluxes( ...
               icemodel.surface.physical_surface_temperature(T_sfc), ...
               tair(metstep), wspd(metstep), psfc(metstep), ea_atm(metstep), ...
               ro_atm(metstep), cv_atm(metstep), nu_air(metstep), H_h(metstep), ...
               H_e, hv_atm, br_coefs, liqflag, ro_sfc, snow_depth, opts);
         else
            thf_diag = struct([]);
         end

         % SAVE OUTPUT IF SPINUP IS FINISHED
         if thisyear > numspinup

            surface_state = struct( ...
               'Tsfc', T_sfc, ...
               'Qm', Qm, ...
               'Qf', Qf, ...
               'Qe', Qe, ...
               'Qh', Qh, ...
               'Qc', Qc, ...
               'Qsn', Qsn, ...
               'Qln', Qln, ...
               'Qa', Qa, ...
               'chi', chi, ...
               'balance', Qbal, ...
               'dt_sum', dt_sum, ...
               'Tsfc_converged', ok_seb, ...
               'Tice_converged', ok_ieb, ...
               'Tice_numiter', n_iters, ...
               'n_subfail', n_subfail, ...
               'ea_atm', ea_atm(metstep), ...
               'br_coefs_gamma', br_coefs(1), ...
               'br_coefs_b1_num', br_coefs(2), ...
               'br_coefs_b2_num', br_coefs(3), ...
               'hv_atm', hv_atm, ...
               'ro_sfc', ro_sfc);

            subsurface_state = struct( ...
               'Tice', T_ice, ...
               'f_ice', f_ice, ...
               'f_liq', f_liq);

            [data1, data2] = icemodel.buildOutputPayload(opts, ...
               surface_state, subsurface_state, thf_diag);

            [ice1, ice2] = icemodel.updateoutput(timestep, ice1, ice2, ...
               opts.vars1, opts.vars2, data1, data2);
         end

         % MOVE TO THE NEXT TIMESTEP
         [metstep, substep, dt] = icemodel.timestepping.nexttimestep( ...
            metstep, substep, dt_FULL_STEP, maxsubstep, ok, n_subfail, n_iters);

      end % timesteps (one year)

      if isfield(opts, 'saverestart') && opts.saverestart
         icemodel.saveRestartState(opts, opts.simyears(thisyear), ...
            T_ice, f_ice, f_liq, T_sfc, r_eff);
      end

      % RESTART THE MET DATA STEP INDEX DURING SPIN UP
      if thisyear <= numspinup
         continue
      end

      % Concatenate yearly raw output when running multi-year simulations
      % without writing each year to disk.
      if ~opts.saveflag && numyears - numspinup > 1
         [ice1_all, ice2_all] = icemodel.concatoutput(ice1_all, ice2_all, ...
            ice1, ice2);
      end

      % WRITE TO DISK
      yridx = (thisyear-1)*numsteps+1:thisyear*numsteps;

      icemodel.writeoutput(ice1, ice2, opts, thisyear, ...
         time(yridx), swd(yridx), lwd(yridx), albedo(yridx))
   end

   if ~opts.saveflag && numyears - numspinup > 1
      ice1 = ice1_all;
      ice2 = ice2_all;
   end
end
