function [ice1, ice2, opts] = skinmodel(opts)
   %SKINMODEL Surface energy balance model for glacier ice.
   %
   % [ice1, ice2] = SKINMODEL(opts)
   % [ice1, ice2, opts] = SKINMODEL(opts)
   %
   % This function returns OPTS so callers can inspect the finalized runtime
   % configuration after icemodel.configureRun() resolves the derived fields.
   %
   % See also: icemodel, icemodel.setopts
   %
   %#codegen

   %% INITIALIZE THE MODEL

   % Runtime configuration
   assertF on
   opts = icemodel.configureRun(opts);
   opts = icemodel.prepareRunOutput(opts);

   % Option to log thf/seb diagnostics.
   use_thf_diag = strcmp(opts.output_profile, 'diagnostic');

   % INITIALIZE SOLVER SETTINGS
   % 'settings' holds the primary solver settings, 'settings0' holds the
   % defaults. checksubstep switches settings to recovery mode (underrelaxation
   % with acceleration off) after a coupler failure, and acceptsubstep restores
   % settings0 after a recovery.
   [settings, settings0] = icemodel.couplers.initialize_solver_settings(opts);
   TINY = 1e-8;
   chi = 1.0;

   % INITIALIZE THE FORCING DATA
   [tair, swd, lwd, albedo, wspd, ...
      rh, psfc, ppt, tppt, time, forcing_snow_depth, opts] ...
      = icemodel.surface.initialize_surface_forcings(opts);

   % INITIALIZE THE THERMAL MODEL
   r_eff = 0;
   [ice1, ice2, T_sfc, T_ice, ...
      f_ice, f_liq, ~, ~, r_eff, k_eff, fn, dz, delz] ...
      = icemodel.column.initialize_column_state(opts, tair, r_eff);

   % INITIALIZE THE SURFACE STATE
   [ea_atm, ro_atm, cv_atm, nu_air, H_h, De_e, br_coefs] ...
      = icemodel.surface.initialize_surface_state(opts, tair, wspd, rh, psfc);

   % INITIALIZE TIMESTEPPING
   [metstep, substep, numsteps, dt, ...
      numyears, numspinup, force_advance_streak_dt] ...
      = icemodel.timestepping.initialize_timesteps(opts, time);

   if ~opts.saveflag && (numyears - numspinup) > 1
      ice1_all = [];
      ice2_all = [];
   end

   % INITIALIZE PAST VALUES
   [xT_sfc, xT_ice, xf_ice, xf_liq, xk_eff] ...
      = icemodel.timestepping.resetsubstep(T_sfc, T_ice, f_ice, f_liq, k_eff);

   %% START TIMESTEPS OVER YEARS
   for thisyear = 1:numyears

      for timestep = 1:numsteps

         % INITIALIZE NEW TIMESTEP
         [dt_sum, ~, ~, ~, ~, ~, ~, diag] ...
            = icemodel.timestepping.newtimestep(f_liq);

         % Get the forcing observation heights and corresponding
         % bulk-Richardson coefficients for this forcing step.
         step_opts = icemodel.surface.step_observation_heights(opts, metstep);
         br_coefs_step = br_coefs(min(metstep, size(br_coefs, 1)), :);

         snow_depth = icemodel.surface.resolve_forcing_snow_depth( ...
            forcing_snow_depth, metstep, opts.use_forcing_snow_depth_for_thf);

         while dt_sum + TINY < settings.dt_full_step

            % UPDATE SURFACE STATE FOR CURRENT FORCING AND COLUMN STATE
            [liqflag, ro_sfc, hv_atm, H_e, ~] = ...
               icemodel.surface.update_surface_state( ...
               f_ice(1), f_liq(1), ro_atm(metstep), ...
               De_e(metstep), snow_depth, step_opts);

            % COUPLED SURFACE-SUBSURFACE ENERGY BALANCE
            [T_sfc, T_ice, f_ice, f_liq, k_eff, diag.substep] ...
               = icemodel.couplers.solve_skin_surface_column( ...
               xT_sfc, xT_ice, xf_ice, xf_liq, dz, delz, fn, dt, ...
               tair(metstep), swd(metstep), lwd(metstep), ...
               albedo(metstep), wspd(metstep), ppt(metstep), ...
               tppt(metstep), psfc(metstep), ea_atm(metstep), ...
               ro_atm(metstep), cv_atm(metstep), nu_air(metstep), ...
               H_h(metstep), H_e, hv_atm, br_coefs_step, liqflag, chi, ...
               ro_sfc, snow_depth, settings, step_opts);

            % CHECK SUBSTEP FAILURE
            % Retry the substep on failure using this decision tree:
            % On a coupler failure, retry once in recovery mode.
            % On any of the following, retry with shortened dt:
            % - a surface-solve failure;
            % - an inner-solve failure;
            % - a failed retry; or
            % - a coupler failure after a failed recovery-mode attempt.
            % After maxsubstep failures, force advance.
            [T_sfc, T_ice, f_ice, f_liq, k_eff, substep, dt, ...
               ok, ~, force_advance_streak_dt, settings, diag] ...
               = icemodel.timestepping.checksubstep(T_sfc, T_ice, f_ice, ...
               f_liq, k_eff, xT_sfc, xT_ice, xf_ice, xf_liq, xk_eff, ...
               dt_sum, dt, timestep, numsteps, substep, ...
               force_advance_streak_dt, 'skinmodel', settings, ...
               settings0, diag);

            if ~ok
               continue
            end

            % CHECKPOINT STATE AND SUBSTEP TIME
            % Unlike icemodel, skinmodel has no substep physics past here, so a
            % forced advance branch is not necessary.
            [xT_sfc, xT_ice, xf_ice, xf_liq, xk_eff, dt_sum, dt, ...
               settings, diag] = ...
               icemodel.timestepping.acceptsubstep( ...
               T_sfc, T_ice, f_ice, f_liq, k_eff, ...
               dt_sum, dt, TINY, settings, settings0, diag);
         end

         % Error if dt accumulation exceeds a full step.
         assertF(@() dt_sum < settings.dt_full_step + 2 * TINY)

         % DIAGNOSE SURFACE ENERGY BALANCE
         [Qe, Qh, Qc, Qsn, Qln, Qa, Qm, Qf, Qbal] ...
            = icemodel.surface.diagnose_surface_energy_balance(T_sfc, ...
            tair(metstep), swd(metstep), lwd(metstep), albedo(metstep), ...
            wspd(metstep), ppt(metstep), tppt(metstep), psfc(metstep), ...
            ea_atm(metstep), ro_atm(metstep), cv_atm(metstep), ...
            nu_air(metstep), H_h(metstep), H_e, hv_atm, br_coefs_step, ...
            liqflag, chi, T_ice, k_eff, dz, ro_sfc, snow_depth, step_opts);

         % Build the thf diagnostic struct if requested.
         if use_thf_diag
            [~, ~, thf_diag] ...
               = icemodel.surface.diagnose_turbulent_heat_fluxes( ...
               icemodel.surface.physical_surface_temperature(T_sfc), ...
               tair(metstep), wspd(metstep), psfc(metstep), ...
               ea_atm(metstep), ro_atm(metstep), cv_atm(metstep), ...
               nu_air(metstep), H_h(metstep), H_e, hv_atm, br_coefs_step, ...
               liqflag, ro_sfc, snow_depth, step_opts);
         else
            thf_diag = struct([]);
         end

         % SAVE OUTPUT IF SPINUP IS FINISHED
         if thisyear > numspinup

            surface_state = struct( ...
               'Tsfc', T_sfc, ...
               'Qm', Qm, ...
               'Qf', Qf, ...
               'Qe', Qe, ...
               'Qh', Qh, ...
               'Qc', Qc, ...
               'Qsn', Qsn, ...
               'Qln', Qln, ...
               'Qa', Qa, ...
               'chi', chi, ...
               'balance', Qbal, ...
               'dt_sum', dt_sum, ...
               'Tsfc_converged', diag.ok_seb, ...
               'Tice_converged', diag.ok_ieb, ...
               'Tice_numiter', diag.n_iters, ...
               'n_failed_substeps', diag.n_failed_substeps, ...
               'n_forced_advances', diag.n_forced_advances, ...
               'cpl_recovery_count', diag.cpl_recovery_count, ...
               'ea_atm', ea_atm(metstep), ...
               'br_coefs_gamma', br_coefs_step(1), ...
               'br_coefs_b1_num', br_coefs_step(2), ...
               'br_coefs_b2_num', br_coefs_step(3), ...
               'hv_atm', hv_atm, ...
               'ro_sfc', ro_sfc);

            subsurface_state = struct( ...
               'Tice', T_ice, ...
               'f_ice', f_ice, ...
               'f_liq', f_liq);

            % Assemble the outputs.
            [data1, data2] = icemodel.buildOutputPayload(opts, ...
               surface_state, subsurface_state, thf_diag);

            % Update the requested ice1 and ice2 outputs for this timestep.
            [ice1, ice2] = icemodel.updateoutput(timestep, ice1, ice2, ...
               opts.vars1, opts.vars2, data1, data2);
         end

         % MOVE TO THE NEXT TIMESTEP
         [metstep, substep, dt] = icemodel.timestepping.nexttimestep( ...
            metstep, substep, ok, settings, diag);

      end % timesteps (one year)

      if isfield(opts, 'saverestart') && opts.saverestart
         icemodel.saveRestartState(opts, opts.simyears(thisyear), ...
            T_ice, f_ice, f_liq, T_sfc, r_eff);
      end

      % RESTART THE MET DATA STEP INDEX DURING SPIN UP
      if thisyear <= numspinup
         continue
      end

      % Concatenate yearly output when a run spans multiple years.
      if ~opts.saveflag && numyears - numspinup > 1
         [ice1_all, ice2_all] = icemodel.concatoutput(ice1_all, ice2_all, ...
            ice1, ice2);
      end

      % WRITE TO DISK
      yridx = (thisyear-1)*numsteps+1:thisyear*numsteps;
      icemodel.writeoutput(ice1, ice2, opts, thisyear, ...
         time(yridx), swd(yridx), lwd(yridx), albedo(yridx))
   end

   if ~opts.saveflag && numyears - numspinup > 1
      ice1 = ice1_all;
      ice2 = ice2_all;
   end
end
