function policy = promiceAblationReadiness()
   %PROMICEABLATIONREADINESS Return the PROMICE ablation admission policy.
   %
   %  policy = ...
   %     icemodel.verification.namelists.promiceAblationReadiness()
   %
   % The policy identifies one longest summertime ice-ablation window from
   % staged surface data. Trace snow up to 0.05 m does not split the window.
   % A comparison row needs at most 0.01 m of snow. This censors the modeled
   % values wherever the observed height record may not show exposed ice.

   % Target and flag roles read by readiness, comparison, and reporting.
   target_field = "ablation";
   support_flag_fields = [ ...
      "surface_height_flag", "station_transition_flag", ...
      "step_detected_flag", "step_correctable_flag"];
   direct_zero_flag_fields = [ ...
      "surface_height_flag", "station_transition_flag", ...
      "step_detected_flag"];
   % Named separately because both consumers need to tell these two apart.
   % Indexing the list by position would make the meaning depend on its order.
   station_transition_flag_field = "station_transition_flag";
   unresolved_step_flag_field = "step_detected_flag";
   datum_break_flag_fields = [ ...
      station_transition_flag_field, unresolved_step_flag_field];
   ordinary_gap_flag_fields = "surface_height_flag";
   metadata_only_flag_fields = "step_correctable_flag";
   policy = struct( ...
      'target_field', target_field, ...
      'support_flag_fields', support_flag_fields, ...
      'direct_zero_flag_fields', direct_zero_flag_fields, ...
      'datum_break_flag_fields', datum_break_flag_fields, ...
      'station_transition_flag_field', station_transition_flag_field, ...
      'unresolved_step_flag_field', unresolved_step_flag_field, ...
      'ordinary_gap_flag_fields', ordinary_gap_flag_fields, ...
      'metadata_only_flag_fields', metadata_only_flag_fields, ...
      'target_variable', target_field, ...
      'snow_variable', "snow_depth", ...
      'target_units', "m", ...
      'target_positive_direction', "down", ...
      'timestamp_convention', "UTC interval_start", ...
      'interval_convention', "hourly cumulative level at posting time", ...
      'reference_semantics', ...
         "zero-referenced at the first finite station-record sample", ...
      'adjustment_semantics', ...
         "source-faithful PROMICE L3; no IceModel fill, smoothing, " ...
         + "or de-step; flags retained", ...
      'evaluation_season_start_month_day', [6, 1], ...
      'evaluation_season_end_month_day', [10, 1], ...
      'zero_reference_tolerance_m', 1e-9, ...
      'snow_continuity_threshold_m', 0.05, ...
      'ice_exposure_threshold_m', 0.01, ...
      'snow_free_sensitivity_thresholds_m', [0.01, 0.05, 0.10], ...
      'minimum_window_days', 30, ...
      'minimum_direct_samples', 2, ...
      'observation_cadence_seconds', 3600, ...
      'forcing_cadence_seconds', 900, ...
      'primary_exclusion_flags', direct_zero_flag_fields);
end
