function policy = promiceAblationPolicy
   %PROMICEABLATIONPOLICY Return the fixed PROMICE ablation comparison policy.
   %
   %  policy = icemodel.verification.namelists.promiceAblationPolicy()
   %
   % The values are declared before any KAN result is inspected. They must not
   % be tuned by site or after viewing evaluation outcomes.

   % Reuse the production diagnostic field registry so the comparator cannot
   % drift from the closure bookkeeping emitted by IceModel.
   readiness = ...
      icemodel.verification.namelists.promiceAblationReadiness();
   policy = struct( ...
      'version', "2026-08-04-seasonal-v2", ...
      'observation_field', readiness.target_field, ...
      'snow_variable', readiness.snow_variable, ...
      'support_flag_fields', readiness.support_flag_fields, ...
      'direct_zero_flag_fields', readiness.direct_zero_flag_fields, ...
      'datum_break_flag_fields', readiness.datum_break_flag_fields, ...
      'ordinary_gap_flag_fields', readiness.ordinary_gap_flag_fields, ...
      'metadata_only_flag_fields', readiness.metadata_only_flag_fields, ...
      'required_observation_fields', ...
         [readiness.target_field, readiness.snow_variable, ...
         readiness.support_flag_fields], ...
       'required_model_fields', string( ...
          [icemodel.column.budget_output_fields('all'), ...
          icemodel.column.cumulative_output_fields()]), ...
      'support', ...
         "exact observation endpoints with finite model diagnostics on [t0,t1)", ...
      'model_interval_convention', ...
         "a model row at Time contains the forcing-step ledger for [Time,Time+dt)", ...
      'rebase', "independent at first direct eligible common observation", ...
      'positive_direction', "loss or lowering", ...
      'observation_units', "m geometric positive-down", ...
      'model_units', "m water equivalent positive-loss", ...
      'model_substep_seconds', 900, ...
      'model_output_cadence_seconds', 3600, ...
      'observation_cadence_seconds', ...
         readiness.observation_cadence_seconds, ...
      'evaluation_season_start_month_day', ...
         readiness.evaluation_season_start_month_day, ...
      'evaluation_season_end_month_day', ...
         readiness.evaluation_season_end_month_day, ...
      'snow_continuity_threshold_m', ...
         readiness.snow_continuity_threshold_m, ...
      'ice_exposure_threshold_m', readiness.ice_exposure_threshold_m, ...
      'observation_rate_outlier_ratio', 0.5, ...
      'observation_rate_outlier_min_years', 3, ...
      'observation_rate_outlier_role', ...
         "cross-year plausibility check on the observed ablation rate. A " + ...
         "site-year is flagged when its observed melt-season rate falls " + ...
         "below observation_rate_outlier_ratio times the median rate of " + ...
         "the SAME station across its own admitted site-years, and only " + ...
         "when that station has at least " + ...
         "observation_rate_outlier_min_years completed site-years that " + ...
         "produced a finite rate, to form " + ...
         "a family. Comparing a station against itself avoids penalising " + ...
         "genuinely low-melt sites. The flag is a visible caveat and never " + ...
         "an exclusion: dropping inconvenient observations would improve " + ...
         "apparent model skill, which is the opposite of what this " + ...
         "evaluation is for. Deciding to exclude a site-year stays a human " + ...
         "decision", ...
      'nested_window_days', [30, 60, 90], ...
      'endpoint_perturbation_days', [1, 3, 7], ...
      'unresolved_step_definition', ...
         "step_detected_flag > 0; staged observations remain source-faithful " + ...
         "and compareAblation never applies an opt-in de-stepping correction", ...
      'numerical', struct( ...
         'atol_mwe', 1e-10, ...
         'rtol', 1e-8, ...
         'q_floor_mwe', 1e-12), ...
      'scientific', struct( ...
         'signal_floor_mwe', 0.025, ...
         'materiality_limit', 0.05, ...
         'endpoint_tolerance_fraction', 0.1), ...
      'effective_density_kg_m3', [600, 870, 900], ...
      'effective_density_reference_kg_m3', 870, ...
      'effective_density_role', ...
         "conversion of measured geometric lowering to water equivalent. " + ...
         "870 kg m^-3 is the reference, drawn as a solid line inside the " + ...
         "band. Two published sources adopt the same value: Hoffman et " + ...
         "al. (2014), doi:10.3189/2014JoG13J095, use 870 kg m^-3 for " + ...
         "Greenland bare ice, and Smedley et al. (2020), " + ...
         "doi:10.5194/tc-14-789-2020, obtain 870 kg m^-3 as a mean over " + ...
         "seven published Antarctic blue-ice densities. Antarctic blue ice " + ...
         "is a different setting, but an independent synthesis landing on " + ...
         "the same number is useful corroboration. The choice therefore " + ...
         "follows published precedent rather than being fitted here. It is " + ...
         "also " + ...
         "supported by direct measurement of bare ablating ice " + ...
         "on the Greenland Ice Sheet: Cooper et al. (2021), Spectral " + ...
         "attenuation coefficients from measurements of light transmission " + ...
         "in bare ice on the Greenland Ice Sheet, report depth-weighted " + ...
         "mean densities of 835 and 855 kg m^-3 for two cores roughly 1 m " + ...
         "deep, with individual segment densities from 801 to 888 kg m^-3. " + ...
         "Those values sit inside the 830-917 kg m^-3 glacier-ice range " + ...
         "given by Cuffey and Paterson, The Physics of Glaciers (2010). " + ...
         "900 kg m^-3 is the dense end; the band stops below ro_ice " + ...
         "(916.7 kg m^-3) because bubble-free ice is not the material that " + ...
         "ablates. 600 kg m^-3 is the porous end. Cooper et al. (2018), " + ...
         "doi:10.5194/tc-12-955-2018, cored bare ablating ice at 1215 m " + ...
         "a.s.l. in the Kangerlussuaq sector and measured near-surface " + ...
         "low-density ice at 0.43-0.91 g cm^-3 beneath a weathering crust " + ...
         "at 0.33-0.56 g cm^-3. Those cores are too site- and " + ...
         "time-specific to supply a canonical mean, so they are cited as " + ...
         "evidence that ablating ice REACHES densities near 600, which is " + ...
         "why 600 is the porous endpoint rather than the reference. " + ...
         "600 kg m^-3 is not an intact glacier-ice density. The band is " + ...
         "deliberately wide because the two measurement sets come from " + ...
         "different elevations on the same transect and disagree: the " + ...
         "dense 835-855 values are from near KAN_L, the porous " + ...
         "weathering-crust values from near KAN_M. Crust development " + ...
         "thins toward lower elevation, where longwave and turbulent " + ...
         "fluxes, melt rates, katabatic wind speeds, and lateral meltwater " + ...
         "flow across flat terrain are all larger. A single density " + ...
         "therefore cannot serve every site-year in the cohort, which is " + ...
         "why the conversion is reported as a band with a reference line " + ...
         "rather than as one number", ...
      'rationale', struct( ...
         'numerical', ...
            "The absolute tolerance resolves bookkeeping roundoff while the " + ...
            "relative tolerance scales with non-cancelling throughput; the " + ...
            "positive floor prohibits division by a near-zero net change.", ...
         'scientific', ...
            "The 0.025 m w.e. signal floor is the PROMICE pressure-transducer " + ...
            "uncertainty scale. A 5 percent channel limit separates material " + ...
            "accounting from numerical noise.", ...
         'density', ...
            "The 600--900 kg m^-3 range is a broad sensitivity envelope " + ...
            "from porous weathering-crust material to dense bubbly ice, " + ...
            "with a measured 870 kg m^-3 reference inside it; " + ...
            "600 kg m^-3 is not an intact glacier-ice density."));

   % These fields explain the policy; they do not govern any result. The
   % report validator compares saved against current policy to guarantee a
   % report never describes a run that used different VALUES, and rewording an
   % explanation must not invalidate a multi-hour cohort. Listed here so the
   % validator derives the set instead of restating it.
   policy.documentation_fields = ["effective_density_role", ...
      "observation_rate_outlier_role", "rationale"];
end
