function info = snowmipsite(sitename)
   %SNOWMIPSITE Canonical ESM-SnowMIP site catalog.
   %
   %  info = icemodel.verification.namelists.snowmipsite()
   %  info = icemodel.verification.namelists.snowmipsite("cdp")
   %
   %  Returns the canonical ESM-SnowMIP site catalog. With no arguments,
   %  returns a struct array covering all 10 reference sites; with one
   %  sitename argument returns the matching scalar struct.
   %
   %  Each entry has fields:
   %    sitename       3-letter site code (matches importer / file naming)
   %    long_name      Display-friendly name
   %    location       Country / region
   %    insitu_window  [start_year, end_year] for met_insitu / obs_insitu
   %    gswp3c_window  [start_year, end_year] for met_gswp3c reanalysis
   %
   %  Sources: Menard et al. 2019 (ESSD; in-situ description), Menard
   %  et al. 2020 (GMD; ESM-SnowMIP simulation protocol), and the file
   %  date stamps in the upstream PANGAEA bundle
   %  (https://doi.org/10.1594/PANGAEA.897575).
   %
   % See also: icemodel.verification.namelists.caseid,
   %  icemodel.verification.setup.importEsmSnowmip

   arguments
      sitename (1, 1) string = ""
   end

   % Canonical catalog. Order is alphabetical by sitename code so
   % namelists / case-id lists are stable across releases.
   catalog = struct( ...
      'sitename', { ...
      "cdp", "oas", "obs", "ojp", "rme", ...
      "sap", "snb", "sod", "swa", "wfj"}, ...
      'long_name', { ...
      "Col de Porte",            "Old Aspen",          ...
      "Old Black Spruce",        "Old Jack Pine",      ...
      "Reynolds Mountain East",  "Sapporo",            ...
      "Senator Beck",            "Sodankyla",          ...
      "Swamp Angel",             "Weissfluhjoch"}, ...
      'location', { ...
      "France",       "Saskatchewan, Canada", ...
      "Saskatchewan, Canada", "Saskatchewan, Canada", ...
      "Idaho, USA",   "Hokkaido, Japan", ...
      "Colorado, USA","Finland", ...
      "Colorado, USA","Switzerland"}, ...
      'insitu_window', { ...
      [1994, 2014], [1997, 2010], [1997, 2010], [1997, 2010], ...
      [1988, 2008], [2005, 2015], [2005, 2015], [2007, 2014], ...
      [2005, 2015], [1996, 2016]}, ...
      'gswp3c_window', { ...
      [1980, 2010], [1980, 2010], [1980, 2010], [1980, 2010], ...
      [1980, 2010], [1980, 2010], [1980, 2010], [1980, 2010], ...
      [1980, 2010], [1980, 2010]});

   if sitename == ""
      info = catalog;
      return
   end

   match = string({catalog.sitename}) == sitename;
   if ~any(match)
      valid = strjoin([catalog.sitename], ', ');
      error('icemodel:verification:snowmipsite:unknown', ...
         'unknown ESM-SnowMIP sitename %s. Valid: %s', sitename, valid);
   end
   info = catalog(match);
end
