function auditMarSemanticsAndGrid()
%AUDITMARSEMANTICSANDGRID Audit MAR semantics and point-grid mapping.
%
% Run from the repository root with:
%   matlab -batch "icemodel.verification.setup.auditMarSemanticsAndGrid()"
%
% The audit is intentionally read-only for staged artifacts. It writes only
% durable QA ledgers under data/preview/qa and fails if the current staged MAR
% point identity or permanent-ice/tundra sector disagrees with the independent
% source-grid reconstruction.

% Resolve repository-owned inputs and the documented MAR archive layout.
repo_root = string(icemodel.internal.fullpath());
manifest_file = fullfile(repo_root, "data", "eval", "promice", "manifest.json");
archive_root = string(getenv("ICEMODEL_MAR_DIR"));
if archive_root == ""
   archive_root = "/Volumes/S03/DATA/greenland/mar3p11/RUH2";
end
archive_readme = fullfile(fileparts(archive_root), "notes", "readme.txt");
source_files = string({dir(fullfile(archive_root, "MARv3.11-ERA5-15km-*.nc")).name})';
source_files = sort(fullfile(archive_root, source_files));
assert(numel(source_files) == 40, ...
   'Expected the complete 1980-2019 MAR RUH2 archive (40 yearly files).')
assert(isfile(manifest_file) && isfile(archive_readme), ...
   'PROMICE manifest or MAR archive mapping readme is unavailable.')

% Use one complete modern file for source schema, grid, and representative
% statistics while checking candidate-variable presence across every year.
source_file = source_files(endsWith(source_files, "-2019.nc"));
assert(isscalar(source_file), 'The MAR 2019 source file is not unique.')
source_info = ncinfo(source_file);
source_names = string({source_info.Variables.Name});
grid = icemodel.forcing.marGridInfo(source_file);
manifest = jsondecode(fileread(manifest_file));

% Source coordinates and sector axes carry the exact 15 km / two-subpixel
% dimension contract used by the independent selector.
x_axis = grid.Xnat(:, 1);
y_axis = grid.Ynat(1, :)';
assert(all(abs(diff(x_axis) - 15000) < 0.25) ...
   && all(abs(diff(y_axis) - 15000) < 0.25), ...
   'MAR native source axes are not the declared regular 15 km grid.')
assert(isscalar(ncread(source_file, 'SECTOR1_1')) ...
   && numel(ncread(source_file, 'SECTOR')) == 2, ...
   'MAR singleton/permanent-ice-tundra sector dimensions are malformed.')

% Reconstruct the oblique-stereographic grid independently. The archive readme
% specifies 70.5 N and 40 W for its 25 km native-grid example; this 15 km
% archive declares its own regular X/Y axes. MAR's standard spherical Earth
% radius closes every source LON/LAT cell onto those axes to metre precision.
earth_radius_m = 6371229;
origin_lat_rad = deg2rad(70.5);
origin_lon_rad = deg2rad(-40);
lat_rad = deg2rad(grid.LAT);
lon_rad = deg2rad(grid.LON);
delta_lon = lon_rad - origin_lon_rad;
denominator = 1 + sin(origin_lat_rad) .* sin(lat_rad) ...
   + cos(origin_lat_rad) .* cos(lat_rad) .* cos(delta_lon);
projected_x = 2 * earth_radius_m .* cos(lat_rad) .* sin(delta_lon) ...
   ./ denominator;
projected_y = 2 * earth_radius_m .* (cos(origin_lat_rad) .* sin(lat_rad) ...
   - sin(origin_lat_rad) .* cos(lat_rad) .* cos(delta_lon)) ./ denominator;
projection_residual_m = hypot(projected_x - grid.Xnat, projected_y - grid.Ynat);
assert(max(projection_residual_m, [], 'all') < 10, ...
   'The documented MAR projection does not close onto the source axes.')

% Prove every staged PROMICE MAR point against an independent projected-axis
% selection and the source coordinates stamped into the current artifact.
mapping_rows = cell(numel(manifest.cases), 18);
mapping_count = 0;
for n = 1:numel(manifest.cases)
   one_case = manifest.cases(n);
   if ~isfield(one_case.colocation, 'mar') || ~one_case.colocation.mar.staged
      continue
   end

   site_lat = double(one_case.site_location.lat_wgs84);
   site_lon = double(one_case.site_location.lon_wgs84);
   site_lat_rad = deg2rad(site_lat);
   site_lon_rad = deg2rad(site_lon);
   site_delta_lon = site_lon_rad - origin_lon_rad;
   site_denominator = 1 + sin(origin_lat_rad) * sin(site_lat_rad) ...
      + cos(origin_lat_rad) * cos(site_lat_rad) * cos(site_delta_lon);
   site_x = 2 * earth_radius_m * cos(site_lat_rad) * sin(site_delta_lon) ...
      / site_denominator;
   site_y = 2 * earth_radius_m * (cos(origin_lat_rad) * sin(site_lat_rad) ...
      - sin(origin_lat_rad) * cos(site_lat_rad) * cos(site_delta_lon)) ...
      / site_denominator;

   % Independent regular-axis selection avoids production interpolants and
   % verifies the native X/Y index convention directly.
   [~, expected_x_index] = min(abs(x_axis - site_x));
   [~, expected_y_index] = min(abs(y_axis - site_y));
   expected_linear_index = sub2ind(size(grid.LON), ...
      expected_x_index, expected_y_index);
   expected_sector = 1 + double(grid.srf(expected_linear_index) ~= 4);

   % Load only top-level provenance, never the large staged timetable.
   artifact_file = fullfile(repo_root, "data", "input", "userdata", ...
      string(one_case.colocation.mar.data_files));
   assert(isfile(artifact_file), ...
      'A manifest-staged PROMICE MAR artifact is missing: %s', artifact_file)
   artifact = load(artifact_file, 'artifact_metadata');
   metadata = artifact.artifact_metadata;
   assert(isfield(metadata, 'source_lat_wgs84') ...
      && isfield(metadata, 'source_lon_wgs84') ...
      && isfield(metadata, 'mar_qc_sector'), ...
      'MAR artifact lacks point/sector provenance: %s', artifact_file)

   % Recover the artifact cell from exact source coordinates, independent of
   % the production selector and of MATLAB linear-index orientation.
   source_distance = sind((grid.LAT - metadata.source_lat_wgs84) / 2).^2 ...
      + cosd(metadata.source_lat_wgs84) .* cosd(grid.LAT) ...
      .* sind((grid.LON - metadata.source_lon_wgs84) / 2).^2;
   [~, artifact_linear_index] = min(source_distance(:));
   [artifact_x_index, artifact_y_index] = ind2sub( ...
      size(grid.LON), artifact_linear_index);
   artifact_sector = double(metadata.mar_qc_sector);

   % Report great-circle station-to-cell distance for review, but use the
   % documented projected grid for the pass/fail identity.
   station_distance = sind((grid.LAT(expected_linear_index) - site_lat) / 2).^2 ...
      + cosd(site_lat) * cosd(grid.LAT(expected_linear_index)) ...
      * sind((grid.LON(expected_linear_index) - site_lon) / 2).^2;
   distance_km = 2 * 6371 * asin(sqrt(station_distance));
   cell_match = artifact_x_index == expected_x_index ...
      && artifact_y_index == expected_y_index;
   sector_match = artifact_sector == expected_sector;

   mapping_count = mapping_count + 1;
   mapping_rows(mapping_count, :) = { ...
      string(one_case.case_id), string(one_case.site_id), site_lat, site_lon, ...
      expected_x_index, expected_y_index, grid.LAT(expected_linear_index), ...
      grid.LON(expected_linear_index), distance_km, grid.srf(expected_linear_index), ...
      expected_sector, artifact_x_index, artifact_y_index, ...
      double(metadata.source_lat_wgs84), double(metadata.source_lon_wgs84), ...
      artifact_sector, cell_match, sector_match};
end
mapping_rows = mapping_rows(1:mapping_count, :);
mapping = cell2table(mapping_rows, 'VariableNames', { ...
   'case_id', 'site_id', 'site_lat_wgs84', 'site_lon_wgs84', ...
   'expected_x_index', 'expected_y_index', 'expected_source_lat_wgs84', ...
   'expected_source_lon_wgs84', 'station_to_cell_km', 'source_srf', ...
   'expected_sector', 'artifact_x_index', 'artifact_y_index', ...
   'artifact_source_lat_wgs84', 'artifact_source_lon_wgs84', ...
   'artifact_sector', 'cell_match', 'sector_match'});
assert(height(mapping) > 0 && all(mapping.cell_match) && all(mapping.sector_match), ...
   'One or more staged PROMICE MAR point or sector mappings are incorrect.')

% Inventory source-backed variables useful to seasonal-snow and later firn
% work. Decisions are explicit so later builders do not infer semantics from
% variable names alone.
candidate_names = [ ...
   "SHSN0"; "SHSN2"; "SHSN3"; "ZN4"; "ZN5"; "ZN6"; "SWSN"; ...
   "RO1"; "TI1"; "WA1"; "AG1"; "DZSN1"; "ROSN1"; "TISN1"; ...
   "WASN1"; "AGSN1"; "SMB"; "ME"; "RZ"; "SW"; "SF"; "RF"; "RU"; "SU"];
vertical_reference = [ ...
   "model bookkeeping thickness; reference not a surface datum"; ...
   "snow height above bare ice"; ...
   "total model snow/firn column thickness"; ...
   "column-height change from compaction"; ...
   "column-height change from melt"; ...
   "total column-height change"; ...
   "surface water specific mass"; ...
   "fixed positive-down OUTLAY depths (0-20 m)"; ...
   "fixed positive-down OUTLAY depths (0-20 m)"; ...
   "fixed positive-down OUTLAY depths (0-20 m)"; ...
   "fixed positive-down OUTLAY depths (0-20 m)"; ...
   repmat("native dynamic SNOLAY; vertical order not source-documented", 5, 1); ...
   repmat("surface mass-balance diagnostic", 8, 1)];
staging_decision = [ ...
   "do_not_stage; internal column bookkeeping only"; ...
   "keep_as_snowd; seasonal snow above bare ice"; ...
   "profile_QA_only; never alias to seasonal snow depth"; ...
   repmat("defer; diagnostic until source equations/reference are documented", 4, 1); ...
   "optional_public_density_profile_bundle"; ...
   "future_optional_temperature_profile_bundle"; ...
   "future_optional_liquid_water_profile_bundle"; ...
   "defer; snow-age encoding is not source-documented"; ...
   repmat("internal_profile_QA_only; do not publish dynamic layers", 5, 1); ...
   "already_staged_as_smb_daily"; ...
   "already_staged_as_melt_daily_reference"; ...
   "already_staged_as_refreeze_deposition"; ...
   "diagnostic_only; not a precipitation forcing"; ...
   "already_staged_as_snowfall"; ...
   "already_staged_as_rainfall"; ...
   "already_staged_as_runoff_daily"; ...
   "already_staged_as_sublimation_evaporation"];
intended_use = [ ...
   "reject as evaluation target"; "seasonal snow evaluation over ice"; ...
   "total-column/profile consistency diagnostic"; ...
   repmat("height-change diagnostic", 3, 1); ...
   "surface liquid-water diagnostic"; "density-profile evaluation"; ...
   "temperature-profile evaluation"; "liquid-water-profile evaluation"; ...
   "snow-age diagnostic"; repmat("dynamic-layer source QA", 5, 1); ...
   "surface mass balance"; "melt production"; "refreezing/deposition"; ...
   "surface water"; "snowfall forcing/diagnostic"; ...
   "rainfall forcing/diagnostic"; "runoff diagnostic"; ...
   "sublimation/evaporation diagnostic"];
assert(numel(candidate_names) == numel(vertical_reference) ...
   && numel(candidate_names) == numel(staging_decision) ...
   && numel(candidate_names) == numel(intended_use), ...
   'The MAR variable decision ledger columns are misaligned.')

% Read each yearly header once to prove temporal availability without loading
% the large field arrays.
availability = false(numel(source_files), numel(candidate_names));
years = nan(numel(source_files), 1);
for n = 1:numel(source_files)
   one_info = ncinfo(source_files(n));
   one_names = string({one_info.Variables.Name});
   availability(n, :) = ismember(candidate_names, one_names);
   token = regexp(source_files(n), '(\d{4})\.nc$', 'tokens', 'once');
   years(n) = str2double(token{1});
end

ledger_rows = cell(numel(candidate_names), 11);
for n = 1:numel(candidate_names)
   name = candidate_names(n);
   variable = source_info.Variables(source_names == name);
   assert(isscalar(variable), 'Candidate variable missing in MAR 2019: %s', name)
   dimensions = string(strjoin({variable.Dimensions.Name}, ','));
   dimension_sizes = string(strjoin(string([variable.Dimensions.Length]), ','));
   units = "";
   long_name = "";
   for a = 1:numel(variable.Attributes)
      if strcmp(variable.Attributes(a).Name, 'units')
         units = string(variable.Attributes(a).Value);
      elseif strcmp(variable.Attributes(a).Name, 'long_name')
         long_name = string(variable.Attributes(a).Value);
      end
   end
   support = years(availability(:, n));
   ledger_rows(n, :) = {name, long_name, units, dimensions, dimension_sizes, ...
      numel(support), min(support), max(support), vertical_reference(n), ...
      intended_use(n), staging_decision(n)};
end
ledger = cell2table(ledger_rows, 'VariableNames', { ...
   'variable', 'source_long_name', 'native_units', 'native_dimensions', ...
   'dimension_sizes', 'available_year_count', 'first_year', 'last_year', ...
   'vertical_reference', 'intended_use', 'staging_decision'});

% Quantify SHSN0/2/3 at accumulation and ablation sites. The two endpoint
% years demonstrate that conclusions are not a one-year reset artifact.
representative_sites = ["CEN"; "EGP"; "KAN_L"; "KAN_U"];
representative_years = [2000; 2019];
stat_rows = cell(numel(representative_years) * ...
   numel(representative_sites), 25);
stat_count = 0;
for y = representative_years'
   one_file = source_files(endsWith(source_files, "-" + string(y) + ".nc"));
   one_grid = icemodel.forcing.marGridInfo(one_file);
   for s = 1:numel(representative_sites)
      site_id = representative_sites(s);
      one_case = manifest.cases(strcmpi(string({manifest.cases.site_id}), site_id));
      site_lat = double(one_case.site_location.lat_wgs84);
      site_lon = double(one_case.site_location.lon_wgs84);

      % Use the same independently documented projection used by the all-site
      % mapping proof, not the production scattered interpolant.
      phi = deg2rad(site_lat);
      delta = deg2rad(site_lon) - origin_lon_rad;
      denominator = 1 + sin(origin_lat_rad) * sin(phi) ...
         + cos(origin_lat_rad) * cos(phi) * cos(delta);
      site_x = 2 * earth_radius_m * cos(phi) * sin(delta) / denominator;
      site_y = 2 * earth_radius_m * (cos(origin_lat_rad) * sin(phi) ...
         - sin(origin_lat_rad) * cos(phi) * cos(delta)) / denominator;
      [~, x_index] = min(abs(one_grid.Xnat(:, 1) - site_x));
      [~, y_index] = min(abs(one_grid.Ynat(1, :)' - site_y));

      [shsn0, ~, ~] = icemodel.forcing.readMar3p11(one_file, 'SHSN0', ...
         start=[x_index y_index], count=[1 1], sector=1);
      [shsn2, ~, ~] = icemodel.forcing.readMar3p11(one_file, 'SHSN2', ...
         start=[x_index y_index], count=[1 1], sector=1);
      [shsn3, ~, ~] = icemodel.forcing.readMar3p11(one_file, 'SHSN3', ...
         start=[x_index y_index], count=[1 1], sector=1);
      difference = shsn3 - shsn0;
      paired = isfinite(shsn2) & isfinite(shsn3);
      correlation = NaN;
      if nnz(paired) > 1 && std(shsn2(paired)) > 0 && std(shsn3(paired)) > 0
         coefficients = corrcoef(shsn2(paired), shsn3(paired));
         correlation = coefficients(1, 2);
      end
      stat_count = stat_count + 1;
      stat_rows(stat_count, :) = { ...
         site_id, string(one_case.surface_zone), y, x_index, y_index, ...
         one_grid.srf(x_index, y_index), min(shsn0), max(shsn0), ...
         shsn0(end) - shsn0(1), nnz(abs(diff(shsn0)) > 0.5), ...
         min(shsn2), max(shsn2), shsn2(end) - shsn2(1), ...
         mean(shsn2 == 0), min(shsn3), max(shsn3), ...
         shsn3(end) - shsn3(1), min(difference), max(difference), ...
         difference(end) - difference(1), mean(difference < 0), correlation, ...
         max(shsn3) <= 5, all(difference >= 0), string(one_file)};
   end
end
stat_rows = stat_rows(1:stat_count, :);
statistics = cell2table(stat_rows, 'VariableNames', { ...
   'site_id', 'surface_zone', 'year', 'x_index', 'y_index', 'source_srf', ...
   'shsn0_min_m', 'shsn0_max_m', 'shsn0_change_m', ...
   'shsn0_large_step_count', 'shsn2_min_m', 'shsn2_max_m', ...
   'shsn2_change_m', 'shsn2_zero_fraction', 'shsn3_min_m', ...
   'shsn3_max_m', 'shsn3_change_m', 'shsn3_minus_shsn0_min_m', ...
   'shsn3_minus_shsn0_max_m', 'shsn3_minus_shsn0_change_m', ...
   'shsn3_minus_shsn0_negative_fraction', 'shsn2_shsn3_correlation', ...
   'shsn3_plausible_seasonal_depth', 'difference_nonnegative', 'source_file'});
assert(any(~statistics.shsn3_plausible_seasonal_depth) ...
   && any(~statistics.difference_nonnegative), ...
   'Representative statistics did not expose the known SHSN3 ambiguities.')

% Write machine-readable ledgers plus concise, source-backed human summaries.
output_dir = fullfile(repo_root, "data", "preview", "qa");
if ~isfolder(output_dir)
   mkdir(output_dir)
end
writetable(mapping, fullfile(output_dir, "mar_grid_mapping_proof.csv"));
writetable(ledger, fullfile(output_dir, "mar_firn_variable_ledger.csv"));
writetable(statistics, fullfile(output_dir, "mar_firn_site_statistics.csv"));

grid_markdown = fullfile(output_dir, "mar_grid_mapping_proof.md");
fid = fopen(grid_markdown, 'w');
cleaner = onCleanup(@() fclose(fid));
fprintf(fid, '# MAR grid and sector mapping proof\n\n');
fprintf(fid, '- Source mapping: `%s`\n', archive_readme);
fprintf(fid, '- Source grid: `%s`\n', source_file);
fprintf(fid, ['- Documented oblique stereographic origin: 70.5 N, 40 W. ' ...
   'The readme''s offsets/resolution describe its 25 km example; this source ' ...
   'declares 15 km regular X/Y axes. MAR spherical radius: 6371.229 km.\n']);
fprintf(fid, ['- Source axes: X has %d points from %.0f to %.0f km; Y has %d ' ...
   'points from %.0f to %.0f km; both increase by 15 km.\n'], ...
   numel(x_axis), x_axis(1) / 1000, x_axis(end) / 1000, ...
   numel(y_axis), y_axis(1) / 1000, y_axis(end) / 1000);
fprintf(fid, '- Full-grid projection closure: maximum %.3f m.\n', ...
   max(projection_residual_m, [], 'all'));
fprintf(fid, ['- Sector rule: sector 1 is permanent ice; sector 2 is tundra. ' ...
   'Singleton `SECTOR1_1` has length 1; `SECTOR` has length 2.\n']);
fprintf(fid, '- Audited staged PROMICE MAR artifacts: %d.\n', height(mapping));
fprintf(fid, '- Cell mismatches: %d; sector mismatches: %d.\n', ...
   nnz(~mapping.cell_match), nnz(~mapping.sector_match));
fprintf(fid, '- Maximum station-to-selected-cell distance: %.3f km.\n\n', ...
   max(mapping.station_to_cell_km));
fprintf(fid, ['Conclusion: the current staged point identity and sector routing ' ...
   'match an independent implementation of the archive mapping. No production ' ...
   'selector or staged artifact requires repair.\n']);
clear cleaner

firn_markdown = fullfile(output_dir, "mar_firn_variable_ledger.md");
fid = fopen(firn_markdown, 'w');
cleaner = onCleanup(@() fclose(fid));
fprintf(fid, '# MAR snow and firn variable decision ledger\n\n');
fprintf(fid, '- Source grid/schema: `%s`\n', source_file);
fprintf(fid, '- Temporal header audit: 40 yearly RUH2 files, 1980-2019.\n');
fprintf(fid, ['- `SHSN2` is the source-defined snow-pack height above ice and ' ...
   'remains the scalar seasonal `snowd` product.\n']);
fprintf(fid, ['- `SHSN3` is total snow/firn-column thickness. It reaches tens ' ...
   'of metres and matches summed active `DZSN1` thickness; it is profile QA, ' ...
   'not scalar seasonal snow depth.\n']);
fprintf(fid, ['- `SHSN3-SHSN0` is not valid snow depth: representative ice ' ...
   'sites produce negative values and `SHSN0` has bookkeeping jumps.\n']);
fprintf(fid, ['- `RO1(OUTLAY)` is the authoritative optional fixed-depth density ' ...
   'profile. `TI1` and `WA1` are future optional profile candidates. Dynamic ' ...
   '`SNOLAY` variables remain internal QA until vertical ordering is documented.\n']);
fprintf(fid, ['- No high-level forcing contract changes. Existing mass channels ' ...
   'retain their current staged roles; precipitation still comes from `SF/RF`.\n\n']);
fprintf(fid, ['See `mar_firn_variable_ledger.csv` for source metadata/decisions ' ...
   'and `mar_firn_site_statistics.csv` for representative numeric evidence.\n']);
clear cleaner

fprintf(['MAR audit passed: %d staged sites, %d variables, %d site-years; ' ...
   'outputs in %s\n'], height(mapping), height(ledger), height(statistics), output_dir)
end
