function row = emptyFetchProductStatusRow()
   %EMPTYFETCHPRODUCTSTATUSROW Return the literal shared fetch-row prototype.
   %
   %  row = icemodel.verification.setup.emptyFetchProductStatusRow()
   %
   % Product fetchers use this value only for struct preallocation. Keeping the
   % prototype literal makes an empty product selection free of cache globbing,
   % callbacks, and filesystem mutation.

   row = struct( ...
      'product', "", ...
      'doi', "", ...
      'landing_url', "", ...
      'present', false, ...
      'cache_dir', "", ...
      'found_files', strings(1, 0));
end
