function row = emptyFetchProductStatusRow()
   %EMPTYFETCHPRODUCTSTATUSROW Return the literal shared fetch-row prototype.
   %
   %  row = icemodel.verification.setup.emptyFetchProductStatusRow()
   %
   % Product fetchers use this value only for struct preallocation. The
   % prototype is a literal, so an empty product selection does no cache
   % globbing, calls no callback, and changes no file.

   row = struct( ...
      'product', "", ...
      'doi', "", ...
      'landing_url', "", ...
      'present', false, ...
      'cache_dir', "", ...
      'found_files', strings(1, 0));
end
