function sites = imauSiteCatalog(site_ids)
   %IMAUSITECATALOG Return the IMAU hourly-AWS source-site catalog.
   %
   %  sites = icemodel.verification.setup.imauSiteCatalog()
   %  sites = icemodel.verification.setup.imauSiteCatalog("S21")
   %
   % Role
   %  The first IMAU verification inventory is the hourly PANGAEA S21/S22/S23
   %  collection. Coordinates are left unset until parsed from source files so
   %  this source catalog does not pretend to be a geodetic source of truth.
   %  Staged cases are normalized separately through
   %  icemodel.verification.setup.makeFirnCaseManifestEntry.

   arguments
      site_ids (1, :) string = strings(1, 0)
   end

   % Keep the hourly network separate from the daily 19-station SEB product.
   % PANGAEA identifies S21 as accumulation-zone and S22/S23 as ablation-zone;
   % the daily product remains QA/provenance input, not a first-pass case list.
   sites = [ ...
      one("S21", "accumulation", "RetMIP FA meteorological source")
      one("S22", "ablation", "")
      one("S23", "ablation", "")];

   % Reject unknown ids before staging and retain canonical catalog order. Keep
   % the established error id so callers can catch it across the API rename.
   sites = icemodel.verification.setup.selectSiteCatalogEntries(sites, ...
      site_ids, "icemodel:verification:imauSiteMetadata:unknownSite", ...
      "IMAU site");
end

function s = one(site_id, surface_zone, note)
   %ONE Build one metadata row with a stable association field.
   assoc = struct('family', "", 'source_id', "", 'relationship', "");
   if site_id == "S21"
      assoc = struct('family', "retmip", 'source_id', "fa", ...
         'relationship', "meteorological_source_for");
   end

   s = struct( ...
      'site_id', site_id, ...
      'case_id', lower(site_id), ...
      'site_name', "IMAU " + site_id, ...
      'surface_zone', surface_zone, ...
      'eval_target', "firn", ...
      'permafrost_zone', "none", ...
      'lat_wgs84', NaN, ...
      'lon_wgs84', NaN, ...
      'x_epsg3413', NaN, ...
      'y_epsg3413', NaN, ...
      'elev_m', NaN, ...
      'source_association', assoc, ...
      'note', note);
end
