function crosswalk = ktransectAliasCrosswalk()
   %KTRANSECTALIASCROSSWALK Return the K-transect station alias hypothesis table.
   %
   %  crosswalk = icemodel.verification.setup.ktransectAliasCrosswalk()
   %
   % Role
   %  Evidence ledger for the station-identity crosswalk required before any
   %  K-transect donor use: PANGAEA station names versus the literature
   %  S-numbers and the nearby PROMICE KAN-line stations (DesignSpec
   %  2026-07-23-promice-gap-filling-and-ktransect, recommendation R3).
   %  Rows carry their literature source, measured evidence from the staged
   %  coordinates (haversine distance and elevation delta between the
   %  per-year event medians and the pypromice L3 station locations), and a
   %  status. Crosswalk rows are human-approved for donor evaluation;
   %  a row reverting to "hypothesis" re-blocks donor use of that pairing.
   %  `promice_neighbor` rows relate distinct nearby stations for donor
   %  evaluation; they are not same-station aliases for self-donor exclusion.
   %
   % Returns
   %  crosswalk : struct array with one row per claimed alias. Fields:
   %     pangaea_id   PANGAEA.947483 station name (catalog site_id).
   %     alias_id     claimed alternate identifier.
   %     alias_kind   "literature_station" or "promice_neighbor".
   %     claim        plain-language statement of the claimed relationship.
   %     source       citation the claim comes from.
   %     status       "hypothesis" until evidence verifies or refutes it.
   %     evidence     verification evidence; "" until the evidence pass runs.
   %
   % See also: icemodel.verification.setup.ktransectSiteCatalog

   % Charalampidis et al. (2015, The Cryosphere 9, 2163-2181) reconstructs
   % KAN_U outages from a station "S10" and uses "S9" for additional missing
   % measurements; Smeets et al. (2022, PANGAEA.947483) publishes AWS5/AWS6/
   % AWS9/AWS10, which the K-transect literature names S5/S6/S9/S10;
   % Vandecrux et al. (2018, JGR Earth Surface) uses secondary stations for
   % KAN_U gap filling. Neither audited codebase implements the S10/S9
   % recovery, so identity rests on coordinates, elevations, and overlap
   % periods to be recorded in the evidence field.
   %
   % The promice_neighbor rows extend beyond the cited papers by user
   % direction: with only four K-transect stations, every
   % transect-to-PROMICE pairing is a donor hypothesis worth investigating,
   % including elevation-aware interpolation between bracketing stations
   % (e.g. KAN_M between S6 and S9).
   crosswalk = [ ...
      one("AWS5", "S5", "literature_station", ...
      "PANGAEA AWS5 is the lower-ablation station published as S5 in the K-transect literature", ...
      "Smeets et al. (2022) PANGAEA.947483", ...
      "staged elevation ~500 m matches the published S5 transect position; approved 2026-07-24")
      one("AWS6", "S6", "literature_station", ...
      "PANGAEA AWS6 is the ablation-area station published as S6 in the K-transect literature", ...
      "Smeets et al. (2022) PANGAEA.947483", ...
      "staged elevation ~1000 m matches the published S6 transect position; approved 2026-07-24")
      one("AWS9", "S9", "literature_station", ...
      "PANGAEA AWS9 is the equilibrium-line station published as S9 in the K-transect literature", ...
      "Smeets et al. (2022) PANGAEA.947483; Charalampidis et al. (2015)", ...
      "staged elevation 1500 m at the equilibrium line matches the published S9; approved 2026-07-24")
      one("AWS10", "S10", "literature_station", ...
      "PANGAEA AWS10 is the accumulation-area station published as S10 in the K-transect literature", ...
      "Smeets et al. (2022) PANGAEA.947483; Charalampidis et al. (2015)", ...
      "staged elevation ~1850 m and the 0.2 km KAN_U offset match the published S10; approved 2026-07-24")
      one("AWS5", "KAN_L", "promice_neighbor", ...
      "S5 sits near PROMICE KAN_L in the lower ablation zone", ...
      "user domain knowledge 2026-07-23", ...
      "measured 6.4 km, dElev -168 m (staged medians vs pypromice L3 location); approved 2026-07-24")
      one("AWS6", "KAN_L", "promice_neighbor", ...
      "S6 lies between PROMICE KAN_L and KAN_M along the transect", ...
      "user domain knowledge 2026-07-23", ...
      "measured 23.8 km, dElev +332 m; bracketing confirmed with the AWS6-KAN_M row; approved 2026-07-24")
      one("AWS6", "KAN_M", "promice_neighbor", ...
      "S6 lies between PROMICE KAN_L and KAN_M along the transect", ...
      "user domain knowledge 2026-07-23", ...
      "measured 24.4 km, dElev -269 m; bracketing confirmed with the AWS6-KAN_L row; approved 2026-07-24")
      one("AWS9", "KAN_M", "promice_neighbor", ...
      "S9 sits not far upslope of PROMICE KAN_M; KAN_M lies between S6 and S9, enabling elevation-aware bracketing", ...
      "user domain knowledge 2026-07-23", ...
      "measured 25.4 km, dElev +231 m; KAN_M (1269 m) bracketed by S6 (1000 m) and S9 (1500 m); approved 2026-07-24")
      one("AWS10", "KAN_U", "promice_neighbor", ...
      "S10 sits close enough to PROMICE KAN_U (literature: tens of meters) to serve as its reconstruction donor over 2010-2016", ...
      "Charalampidis et al. (2015)", ...
      "measured 0.2 km, dElev +10 m - essentially collocated at median-coordinate resolution; approved 2026-07-24")];
end

function row = one(pangaea_id, alias_id, alias_kind, claim, source, evidence)
   %ONE Build one verified crosswalk row.
   row = struct( ...
      'pangaea_id', string(pangaea_id), ...
      'alias_id', string(alias_id), ...
      'alias_kind', string(alias_kind), ...
      'claim', string(claim), ...
      'source', string(source), ...
      'status', "verified", ...
      'evidence', string(evidence));
end
