function sites = ktransectSiteCatalog(site_ids)
   %KTRANSECTSITECATALOG Return the K-transect AWS source-site catalog.
   %
   %  sites = icemodel.verification.setup.ktransectSiteCatalog()
   %  sites = icemodel.verification.setup.ktransectSiteCatalog("AWS9")
   %
   % Role
   %  The K-transect verification inventory is the Smeets et al. (2022)
   %  PANGAEA.947483 annual AWS5/AWS6/AWS9/AWS10 series. Coordinates are left
   %  unset until parsed from source files so this source catalog does not
   %  pretend to be a geodetic source of truth: the ablation-zone stations move
   %  with the ice flow and the staged point comes from the per-year event
   %  coordinates. Staged cases are normalized separately through
   %  icemodel.verification.setup.makeFirnCaseManifestEntry.
   %
   %  Station aliases (AWS9/S9, AWS10/S10, KAN_U proximity) are hypotheses
   %  tracked in icemodel.verification.setup.ktransectAliasCrosswalk, not
   %  associations baked into this catalog.

   arguments
      site_ids (1, :) string = strings(1, 0)
   end

   % Surface zones follow the PANGAEA series description: AWS5 sits in the
   % lower ablation area, AWS6 in the ablation area, AWS9 at the equilibrium
   % line (recorded in its note; the coarse zone vocabulary has no ELA entry),
   % and AWS10 in the accumulation area.
   sites = [ ...
      one("AWS5", "ablation", ["seasonal_snow", "bare_ice"], ...
      "lower ablation area; type-1 AWS from Aug 2016; draw-wire ice_melt channel")
      one("AWS6", "ablation", ["seasonal_snow", "bare_ice"], ...
      "ablation area; type-1 AWS from Aug 2015; draw-wire ice_melt channel")
      one("AWS9", "ablation", ["seasonal_snow", "firn"], ...
      "equilibrium line (~1500 m); type-1 AWS from Aug 2014; candidate literature S9")
      one("AWS10", "accumulation", "firn", ...
      "accumulation area; record 2010-2016; type-1 AWS from Aug 2014; candidate literature S10 donor for KAN_U")];

   % Reject unknown ids before staging and retain canonical catalog order.
   sites = icemodel.verification.setup.selectSiteCatalogEntries(sites, ...
      site_ids, "icemodel:verification:ktransectSiteCatalog:unknownSite", ...
      "K-transect site");
end

function s = one(site_id, surface_zone, eval_target, note)
   %ONE Build one metadata row with a stable association field.
   % No source association is asserted here: the AWS9/S9, AWS10/S10, and KAN_U
   % relationships stay in the alias crosswalk until verified and approved.
   assoc = struct('family', "", 'source_id', "", 'relationship', "");

   s = struct( ...
      'site_id', site_id, ...
      'case_id', lower(site_id), ...
      'site_name', "K-transect " + site_id, ...
      'surface_zone', surface_zone, ...
      'eval_target', {string(eval_target)}, ...
      'permafrost_zone', "none", ...
      'lat_wgs84', NaN, ...
      'lon_wgs84', NaN, ...
      'x_epsg3413', NaN, ...
      'y_epsg3413', NaN, ...
      'elev_m', NaN, ...
      'source_association', assoc, ...
      'note', note);
end
