function sites = researchSiteCatalog(site_ids)
   %RESEARCHSITECATALOG Return the catchall research source-site catalog.
   %
   %  sites = icemodel.verification.setup.researchSiteCatalog()
   %  sites = icemodel.verification.setup.researchSiteCatalog("humphrey")
   %
   % Role
   %  Catchall site catalog for high-value research targets that do not belong
   %  cleanly to a network family such as PROMICE, IMAU, or RetMIP. These sites
   %  are source-family anchors for colocation metadata, not a special SUMup
   %  subcategory. Staged cases are normalized separately through
   %  icemodel.verification.setup.makeFirnCaseManifestEntry.

   arguments
      site_ids (1, :) string = strings(1, 0)
   end

   % Start with Humphrey because it is the current standalone Meyer-Hewitt target
   % and should be represented by the generic research_site family.
   sites = one("humphrey", "Humphrey percolation thermistor network");

   % Reject unknown ids before staging and retain canonical catalog order. Keep
   % the established error id so callers can catch it across the API rename.
   sites = icemodel.verification.setup.selectSiteCatalogEntries(sites, ...
      site_ids, "icemodel:verification:researchSiteMetadata:unknownSite", ...
      "research_site");
end

function s = one(site_id, site_name)
   %ONE Build one research-site metadata row.
   % Humphrey is a multi-site thermistor network. Use the SUMup-weighted
   % centroid for nearest-anchor bookkeeping while retaining the network
   % provenance in the note.
   s = struct( ...
      'site_id', site_id, ...
      'case_id', site_id, ...
      'site_name', site_name, ...
      'family', "research_site", ...
      'source_id', site_id, ...
      'surface_zone', "percolation", ...
      'eval_target', "firn", ...
      'permafrost_zone', "none", ...
      'lat_wgs84', 69.725714, ...
      'lon_wgs84', -48.190512, ...
      'x_epsg3413', NaN, ...
      'y_epsg3413', NaN, ...
      'elev_m', 1645.1, ...
      'period', struct('start', '2007-01-01 00:00:00', ...
      'end', '2008-12-31 23:00:00'), ...
      'note', "SUMup Humphrey2012/Harper2011 thermistor-network centroid; use RCM forcing first.");
end
