function cases = retmipCaseMetadata(case_ids)
   %RETMIPCASEMETADATA Return canonical RetMIP case metadata.
   %
   %  cases = icemodel.verification.setup.retmipCaseMetadata()
   %  cases = icemodel.verification.setup.retmipCaseMetadata(["kanu","fa"])
   %
   % Role
   %  RetMIP case inventory used by fetch/import tests and staging helpers. The
   %  source associations are metadata only; they do not imply forcing has been
   %  staged or that protocol variables belong in a normal icemodel met file.

   arguments
      case_ids (1, :) string = strings(1, 0)
   end

   % Use filename-safe ids while preserving the protocol names, aliases, windows,
   % and source links needed to map RetMIP protocol products to real sources.
   cases = [ ...
      one("kanu", "kanu", "KAN_U", "KAN_U", "promice", "KAN_U", ...
         "2012-05-01 00:00:00", "2016-12-31 06:00:00", ...
         67.0003, -47.0243, 1840, ["kanu", "KAN_U"])
      one("dye2_long", "dye2", "Dye-2_long", "Dye-2_long", ...
         "gcnet", "DYE2", "1998-06-01 00:00:00", ...
         "2015-05-02 15:00:00", 66.48001, -46.27889, 2165, ...
         ["dye2_long", "dye2", "Dye-2_long"])
      one("dye2_2016", "dye2_16", "Dye-2_16", "Dye-2_16", ...
         "samimi", "Dye-2", "2016-05-02 00:00:00", ...
         "2016-10-28 09:00:00", 66.48001, -46.27889, 2165, ...
         ["dye2_2016", "dye2_16", "Dye-2_16"])
      one("summit", "sum", "Summit", "Summit", "gcnet", "Summit", ...
         "2000-07-02 00:00:00", "2015-03-08 12:00:00", ...
         72.57972, -38.50454, 3254, ["summit", "sum", "Summit"])
      one("fa", "fa", "Firn Aquifer (FA)", "Firn Aquifer (FA)", ...
         "imau", "S21", "2014-04-12 00:00:00", ...
         "2014-12-02 21:00:00", 66.1812, -39.0435, 1563, ...
         ["fa", "Firn Aquifer (FA)", "FA"])];

   % A caller can request a subset by canonical id or protocol alias; fail early
   % on unknown ids so manifests cannot silently drift from the protocol table.
   if ~isempty(case_ids)
      keep = false(size(cases));
      missing = strings(1, numel(case_ids));
      n_missing = 0;
      for k = 1:numel(case_ids)
         idx = find(arrayfun(@(c) any(strcmpi(case_ids(k), c.aliases)), ...
            cases), 1);
         if isempty(idx)
            n_missing = n_missing + 1;
            missing(n_missing) = case_ids(k);
         else
            keep(idx) = true;
         end
      end
      missing = missing(1:n_missing);
      if ~isempty(missing)
         error('icemodel:verification:retmipCaseMetadata:unknownCase', ...
            'unknown RetMIP case id(s): %s', strjoin(missing, ', '));
      end
      cases = cases(keep);
   end
end

function s = one(case_id, station_id, protocol_id, site_name, source_family, ...
   source_id, start_time, end_time, lat, lon, elev, aliases)
   %ONE Build one metadata row with the shared association schema.
   s = struct( ...
      'case_id', case_id, ...
      'retmip_station_id', station_id, ...
      'protocol_id', protocol_id, ...
      'site_id', protocol_id, ...
      'site_name', site_name, ...
      'surface_zone', "unknown", ...
      'eval_target', "firn", ...
      'permafrost_zone', "none", ...
      'source_association', struct( ...
         'family', source_family, ...
         'source_id', source_id, ...
         'relationship', "meteorological_source"), ...
      'site_location', struct('lat_wgs84', lat, 'lon_wgs84', lon, ...
         'x_epsg3413', NaN, 'y_epsg3413', NaN, 'elev_m', elev), ...
      'period', struct('start', start_time, 'end', end_time), ...
      'protocol_timestep', "3hr", ...
      'met_source_label', "retmip", ...
      'aliases', aliases);
end
