
% Note: these are pre-teardown of spectral_variant

% Defaults
results = run_spectral_study_bootstrap( ...
   simyear=2016, ...
   solver=2, ...
   smbmodel="all", ...
   smoke_sites="kanm", ...
   full_sites=["kanm"; "kanl"], ...
   spectral_variant="lookup", ...
   n_direct_runs=1, ...
   include_density_floor=true, ...
   include_spectral_perf=true, ...
   include_figures=true, ...
   include_regression_acceptance=false, ...
   include_perf_acceptance=false, ...
   include_benchmarks=false, ...
   rebuild_regression_baseline=false, ...
   rebuild_perf_baseline=false, ...
   output_root="", ...
   run_name="");
   
% Kernel Summary
report = summarize_spectral_perf( ...
    simyear=2016, ...
    include_full_model=false, ...
    include_direct_model=false, ...
    include_formal_perf=false);

% Profile Plots
report = plot_spectral_variant_profiles();

% Density-Floor Audit
report = summarize_spectral_density_floor();

% 2-Year Smoke Regression Acceptance
r_reg = run_regression_suite( ...
    tier="smoke", ...
    smbmodel="all", ...
    solver=2, ...
    baseline="rolling", ...
    spectral_variant="lookup");

% 2-Year Smoke Perf Acceptance
r_perf = run_perf_suite( ...
    tier="smoke", ...
    smbmodel="all", ...
    solver=2, ...
    baseline="rolling", ...
    n_runs=1, ...
    include_benchmarks=false, ...
    spectral_variant="lookup");

% Rebuild Rolling Regression Baseline
RegressionBaseline = build_regression_baseline( ...
    baseline="rolling", ...
    spectral_variant="lookup");

% Rebuild Rolling Perf Baseline
PerfBaseline = build_perf_baseline( ...
    baseline="rolling", ...
    spectral_variant="lookup");

% Postprocess Timing
report = summarize_postprocess_perf(simyear=2016);
