function ledger = accumulate_remesh_budget( ...
      ledger, remesh, solid_change, liquid_change)
   %ACCUMULATE_REMESH_BUDGET Add one substep's remeshing and closure channels.
   %
   %  ledger = icemodel.column.accumulate_remesh_budget( ...
   %     ledger, remesh, solid_change, liquid_change)
   %
   % Call this once per accepted substep, right after
   % icemodel.column.merge_thin_layers. Remeshing is a numerical grid operation,
   % not a physical flux. Its storage exchange stays in dedicated channels. The
   % scientific comparator excludes those channels from physical solid loss.
   %
   % Inputs
   %   ledger        - Forcing-step ledger carrying the phase and vapor channels.
   %   remesh        - Event ledger returned by icemodel.column.merge_thin_layers.
   %   solid_change  - Signed substep phase + vapor solid increment [m w.e.].
   %   liquid_change - Signed substep phase + vapor liquid increment [m w.e.].
   %
   % Outputs
   %   ledger        - Ledger with the remesh, domain-exchange, grid-translation,
   %                   and gross endpoint-storage channels accumulated.
   %
   % See also: icemodel.column.merge_thin_layers,
   %  icemodel.column.accumulate_vapor_budget
   %
   %#codegen

   % Net remeshing exchange: what the column gained or lost across the merge.
   ledger.mass_budget_remesh_solid_mwe = ...
      ledger.mass_budget_remesh_solid_mwe + remesh.solid_mwe;
   ledger.mass_budget_remesh_liquid_mwe = ...
      ledger.mass_budget_remesh_liquid_mwe + remesh.liquid_mwe;
   ledger.mass_budget_remesh_enthalpy_j_m2 = ...
      ledger.mass_budget_remesh_enthalpy_j_m2 + remesh.enthalpy_j_m2;

   % Domain exchange splits that net into two parts: the cloned bottom reservoir
   % the fixed-depth grid imports, and the merge export the grid discards. Every
   % event satisfies remesh = cloned_bottom - merge_export.
   ledger.mass_budget_cloned_bottom_solid_mwe = ...
      ledger.mass_budget_cloned_bottom_solid_mwe + remesh.cloned_bottom_solid_mwe;
   ledger.mass_budget_cloned_bottom_liquid_mwe = ...
      ledger.mass_budget_cloned_bottom_liquid_mwe ...
      + remesh.cloned_bottom_liquid_mwe;
   ledger.mass_budget_cloned_bottom_enthalpy_j_m2 = ...
      ledger.mass_budget_cloned_bottom_enthalpy_j_m2 ...
      + remesh.cloned_bottom_enthalpy_j_m2;
   ledger.mass_budget_merge_export_solid_mwe = ...
      ledger.mass_budget_merge_export_solid_mwe ...
      + remesh.merge_export_solid_mwe;
   ledger.mass_budget_merge_export_liquid_mwe = ...
      ledger.mass_budget_merge_export_liquid_mwe ...
      + remesh.merge_export_liquid_mwe;
   ledger.mass_budget_merge_export_enthalpy_j_m2 = ...
      ledger.mass_budget_merge_export_enthalpy_j_m2 ...
      + remesh.merge_export_enthalpy_j_m2;

   % Grid translation: only top removals lower the surface of the fixed grid.
   % The height is quantized grid geometry. The export is the mass that the
   % removal took out of the column. The export over-counts what the removed
   % cell held, so it is not a surface mass flux.
   ledger.mass_budget_top_deletion_count = ...
      ledger.mass_budget_top_deletion_count + remesh.top_deletion_count;
   ledger.mass_budget_top_deletion_height_m = ...
      ledger.mass_budget_top_deletion_height_m + remesh.top_deletion_height_m;
   ledger.mass_budget_top_export_solid_mwe = ...
      ledger.mass_budget_top_export_solid_mwe + remesh.top_export_solid_mwe;
   ledger.mass_budget_top_export_liquid_mwe = ...
      ledger.mass_budget_top_export_liquid_mwe + remesh.top_export_liquid_mwe;
   ledger.mass_budget_interior_merge_count = ...
      ledger.mass_budget_interior_merge_count + remesh.interior_merge_count;

   % Absolute event activity, retained so repeated opposite-signed merges within
   % one forcing step cannot cancel before temporal aggregation.
   ledger.mass_budget_remesh_solid_gross_mwe = ...
      ledger.mass_budget_remesh_solid_gross_mwe + remesh.solid_gross_mwe;
   ledger.mass_budget_remesh_liquid_gross_mwe = ...
      ledger.mass_budget_remesh_liquid_gross_mwe ...
      + remesh.liquid_gross_mwe;
   ledger.mass_budget_remesh_enthalpy_gross_j_m2 = ...
      ledger.mass_budget_remesh_enthalpy_gross_j_m2 ...
      + remesh.enthalpy_gross_j_m2;
   ledger.mass_budget_cloned_bottom_solid_gross_mwe = ...
      ledger.mass_budget_cloned_bottom_solid_gross_mwe ...
      + remesh.cloned_bottom_solid_gross_mwe;
   ledger.mass_budget_cloned_bottom_liquid_gross_mwe = ...
      ledger.mass_budget_cloned_bottom_liquid_gross_mwe ...
      + remesh.cloned_bottom_liquid_gross_mwe;
   ledger.mass_budget_cloned_bottom_enthalpy_gross_j_m2 = ...
      ledger.mass_budget_cloned_bottom_enthalpy_gross_j_m2 ...
      + remesh.cloned_bottom_enthalpy_gross_j_m2;
   ledger.mass_budget_merge_export_solid_gross_mwe = ...
      ledger.mass_budget_merge_export_solid_gross_mwe ...
      + remesh.merge_export_solid_gross_mwe;
   ledger.mass_budget_merge_export_liquid_gross_mwe = ...
      ledger.mass_budget_merge_export_liquid_gross_mwe ...
      + remesh.merge_export_liquid_gross_mwe;
   ledger.mass_budget_merge_export_enthalpy_gross_j_m2 = ...
      ledger.mass_budget_merge_export_enthalpy_gross_j_m2 ...
      + remesh.merge_export_enthalpy_gross_j_m2;

   % Gross endpoint-storage keeps the total storage change of each accepted
   % substep. It records that change before forcing-step or hourly aggregation
   % can cancel it.
   ledger.mass_budget_solid_storage_gross_mwe = ...
      ledger.mass_budget_solid_storage_gross_mwe ...
      + abs(solid_change + remesh.solid_mwe);
   ledger.mass_budget_liquid_storage_gross_mwe = ...
      ledger.mass_budget_liquid_storage_gross_mwe ...
      + abs(liquid_change + remesh.liquid_mwe);
end
