function fields = budget_output_fields(kind)
   %BUDGET_OUTPUT_FIELDS Return the canonical mass-budget output channels.
   %
   %  fields = icemodel.column.budget_output_fields()
   %  fields = icemodel.column.budget_output_fields(kind)
   %
   % KIND is 'all', 'first', 'last', or 'sum'. The aggregation classes are the
   % single source used by diagnostic output configuration and 15-minute to
   % hourly retiming. Start storage uses the first sample, end storage uses the
   % last sample, and signed step increments, energies, heights, and counts sum.
   % Storage, phase, vapor, and remesh changes are positive into the column.
   % MWE channels use physical intrinsic phase densities and physical
   % liquid-water density as their fixed solver and reference basis.
   % Condensation overflow and collapse export are positive out of the column;
   % unapplied vapor retains the sign of the rejected potential input.
   % Throughput channels are sums of absolute accepted substep/event values and
   % therefore remain nonnegative under later temporal aggregation.
   % mass_budget_unapplied_vapor_j_m2 is signed: positive is rejected
   % deposition energy and negative is unsatisfied sublimation demand.
   % mass_budget_interior_merge_count counts every non-top removal, including
   % a deepest-cell removal; only top removals contribute grid translation.
   % mass_budget_top_export_solid_mwe and mass_budget_top_export_liquid_mwe are
   % the mass a top removal actually exports from the column. They are the
   % physical surface-loss comparator; the quantized top-deletion height is a
   % grid-geometry counter and is never mass. Both export channels are
   % nonnegative by construction because a merge retains the mean of the two
   % cells, so they need no separate absolute-throughput channel.

   if nargin == 0
      kind = 'all';
   end

   % Endpoint storage and step-ledger channels require different aggregation.
   first_fields = { ...
      'mass_budget_solid_start_mwe', ...
      'mass_budget_liquid_start_mwe'};
   last_fields = { ...
      'mass_budget_solid_end_mwe', ...
      'mass_budget_liquid_end_mwe'};
   sum_fields = { ...
      'mass_budget_phase_solid_mwe', ...
      'mass_budget_phase_liquid_mwe', ...
      'mass_budget_vapor_solid_mwe', ...
      'mass_budget_vapor_liquid_mwe', ...
      'mass_budget_remesh_solid_mwe', ...
      'mass_budget_remesh_liquid_mwe', ...
      'mass_budget_remesh_enthalpy_j_m2', ...
      'mass_budget_cloned_bottom_solid_mwe', ...
      'mass_budget_cloned_bottom_liquid_mwe', ...
      'mass_budget_cloned_bottom_enthalpy_j_m2', ...
      'mass_budget_collapse_export_solid_mwe', ...
      'mass_budget_collapse_export_liquid_mwe', ...
      'mass_budget_collapse_export_enthalpy_j_m2', ...
      'mass_budget_vapor_potential_j_m2', ...
      'mass_budget_condensation_overflow_mwe', ...
      'mass_budget_unapplied_vapor_j_m2', ...
      'mass_budget_top_deletion_count', ...
      'mass_budget_top_deletion_height_m', ...
      'mass_budget_top_export_solid_mwe', ...
      'mass_budget_top_export_liquid_mwe', ...
      'mass_budget_interior_merge_count', ...
      'mass_budget_solid_storage_throughput_mwe', ...
      'mass_budget_liquid_storage_throughput_mwe', ...
      'mass_budget_phase_solid_throughput_mwe', ...
      'mass_budget_phase_liquid_throughput_mwe', ...
      'mass_budget_vapor_solid_throughput_mwe', ...
      'mass_budget_vapor_liquid_throughput_mwe', ...
      'mass_budget_remesh_solid_throughput_mwe', ...
      'mass_budget_remesh_liquid_throughput_mwe', ...
      'mass_budget_remesh_enthalpy_throughput_j_m2', ...
      'mass_budget_cloned_bottom_solid_throughput_mwe', ...
      'mass_budget_cloned_bottom_liquid_throughput_mwe', ...
      'mass_budget_cloned_bottom_enthalpy_throughput_j_m2', ...
      'mass_budget_collapse_export_solid_throughput_mwe', ...
      'mass_budget_collapse_export_liquid_throughput_mwe', ...
      'mass_budget_collapse_export_enthalpy_throughput_j_m2', ...
      'mass_budget_vapor_potential_throughput_j_m2', ...
      'mass_budget_condensation_overflow_throughput_mwe', ...
      'mass_budget_unapplied_vapor_throughput_j_m2'};

   switch char(kind)
      case 'all'
         fields = [first_fields, last_fields, sum_fields];
      case 'first'
         fields = first_fields;
      case 'last'
         fields = last_fields;
      case 'sum'
         fields = sum_fields;
      otherwise
         error('icemodel:column:budgetOutputFields:kind', ...
            'unrecognized mass-budget output aggregation: %s', char(kind))
   end
end
