function budget = initialize_budget_state(T, f_ice, f_liq, dz)
   %INITIALIZE_BUDGET_STATE Return the zeroed budget for one forcing step.
   %
   %  budget = icemodel.column.initialize_budget_state(T, f_ice, f_liq, dz)
   %
   % One budget struct carries the per-step mass and energy accounting on
   % every output profile. The driver calls this once per forcing step;
   % the producers (accumulate_phase_budget, budget_surface_mass_balance,
   % couple_vapor_step, merge_thin_layers) accumulate into it on accepted
   % substeps only, so a rejected or forced substep never writes and
   % failure needs no reset. finalize_budget_state records the end
   % endpoints. Output emission stays profile-filtered by vars1; the
   % accumulation itself never branches on the profile.
   %
   % The storage start endpoints are recorded here from the entry state,
   % so the per-phase storage closures anchor on the same state the first
   % substep's checkpoint holds.
   %
   % budget.substep carries the transient baselines the producers pass to
   % each other WITHIN one accepted substep: solid_p/liquid_p (storage
   % after the enthalpy solve, the vapor budget's baseline) and
   % solid_v/liquid_v (storage after the surface exchange, the transport
   % budget's baseline). They are scratch, not channels: budgetoutputs
   % does not name them and the output selector never emits them.
   %
   % Storage, phase, vapor, and remesh changes are positive into the
   % column. Overflow and merge export are positive out; unapplied vapor
   % retains rejected-input sign.
   %
   % Codegen builds the struct from the field list written out below, so
   % the order here is what the kernel compiles against. budgetoutputs
   % holds the same names for the output and retiming code, and a test
   % pins the two lists to each other.
   %
   %#codegen

   [solid_start, liquid_start] = ...
      icemodel.column.integrate_column_budget(T, f_ice, f_liq, dz);

   % Declare every field literally so MATLAB Coder never has to construct
   % or extend the budget from runtime field names.
   budget = struct( ...
      'mass_budget_solid_start_mwe', solid_start, ...
      'mass_budget_liquid_start_mwe', liquid_start, ...
      'mass_budget_solid_end_mwe', 0.0, ...
      'mass_budget_liquid_end_mwe', 0.0, ...
      'mass_budget_phase_solid_mwe', 0.0, ...
      'mass_budget_phase_liquid_mwe', 0.0, ...
      'mass_budget_vapor_solid_mwe', 0.0, ...
      'mass_budget_vapor_liquid_mwe', 0.0, ...
      'mass_budget_remesh_solid_mwe', 0.0, ...
      'mass_budget_remesh_liquid_mwe', 0.0, ...
      'mass_budget_cloned_bottom_solid_mwe', 0.0, ...
      'mass_budget_merge_export_solid_mwe', 0.0, ...
      'mass_budget_vapor_potential_j_m2', 0.0, ...
      'mass_budget_condensation_overflow_mwe', 0.0, ...
      'mass_budget_unapplied_vapor_j_m2', 0.0, ...
      'mass_budget_vapor_redistribution_solid_mwe', 0.0, ...
      'mass_budget_vapor_redistribution_liquid_mwe', 0.0, ...
      'mass_budget_top_deletion_count', 0.0, ...
      'mass_budget_top_deletion_height_m', 0.0, ...
      'mass_budget_top_export_solid_mwe', 0.0, ...
      'mass_budget_top_export_liquid_mwe', 0.0, ...
      'mass_budget_interior_merge_count', 0.0, ...
      'substep', struct( ...
      'solid_p', 0.0, 'liquid_p', 0.0, 'solid_v', 0.0, 'liquid_v', 0.0));
end
