function budget = initialize_budget_state(T, f_ice, f_liq, dz)
   %INITIALIZE_BUDGET_STATE Return the zeroed budget for one forcing step.
   %
   %  budget = icemodel.column.initialize_budget_state(T, f_ice, f_liq, dz)
   %
   % Initialize BUDGET at the start of one forcing step. The phase, surface
   % vapor, interior vapor, and remesh functions add each accepted substep to
   % this structure. solid_start and liquid_start are the initial
   % column-integrated stores. finalize_budget_state records the final stores.
   % opts.vars1 selects which budget channels the driver writes to disk.
   %
   % Storage, phase, vapor, and remesh changes are positive into the column.
   % Overflow and merge export are positive out.
   %
   % Codegen builds the struct from the field list defined below, so the order
   % here is what the kernel compiles against. budgetoutputs defines the same
   % fields for output and retiming code, and a test pins the two lists to each
   % other.
   %
   % See also: icemodel.column.finalize_budget_state,
   %  icemodel.column.accumulate_phase_budget,
   %  icemodel.column.accumulate_vapor_exchange,
   %  icemodel.column.accumulate_vapor_transport,
   %  icemodel.column.accumulate_remesh_budget
   %
   %#codegen

   % Integrate solid and liquid phase storage over the column [mwe].
   [solid_start, liquid_start] = ...
      icemodel.column.integrate_column_budget(T, f_ice, f_liq, dz);

   % Declare every field so MATLAB Coder doesn't have to construct
   % or extend the budget from runtime field names.
   budget = struct( ...
      'mass_budget_solid_start_mwe', solid_start, ...
      'mass_budget_liquid_start_mwe', liquid_start, ...
      'mass_budget_solid_end_mwe', 0.0, ...
      'mass_budget_liquid_end_mwe', 0.0, ...
      'mass_budget_phase_solid_mwe', 0.0, ...
      'mass_budget_phase_liquid_mwe', 0.0, ...
      'mass_budget_vapor_solid_mwe', 0.0, ...
      'mass_budget_vapor_liquid_mwe', 0.0, ...
      'mass_budget_remesh_solid_mwe', 0.0, ...
      'mass_budget_remesh_liquid_mwe', 0.0, ...
      'mass_budget_cloned_bottom_solid_mwe', 0.0, ...
      'mass_budget_merge_export_solid_mwe', 0.0, ...
      'mass_budget_vapor_potential_j_m2', 0.0, ...
      'mass_budget_condensation_overflow_mwe', 0.0, ...
      'mass_budget_vapor_transport_solid_mwe', 0.0, ...
      'mass_budget_vapor_transport_liquid_mwe', 0.0, ...
      'mass_budget_top_deletion_count', 0.0, ...
      'mass_budget_top_deletion_height_m', 0.0, ...
      'mass_budget_top_export_solid_mwe', 0.0, ...
      'mass_budget_top_export_liquid_mwe', 0.0, ...
      'mass_budget_interior_merge_count', 0.0);
end
