function remesh = initialize_remesh_ledger()
   %INITIALIZE_REMESH_LEDGER Zeroed remesh event ledger.
   %
   % One definition of the event schema, shared by merge_thin_layers and the
   % tests that assert its field list. merge_thin_layers is the only caller;
   % the solver receives this struct as that function's eighth output and does
   % not predeclare it.
   %
   %#codegen

   % Declare every field literally so MATLAB Coder never constructs or extends
   % the event ledger from runtime field names.
   remesh = struct( ...
      'top_deletion_count', 0, ...
      'top_deletion_height_m', 0.0, ...
      'top_export_solid_mwe', 0.0, ...
      'top_export_liquid_mwe', 0.0, ...
      'interior_merge_count', 0, ...
      'solid_mwe', 0.0, ...
      'liquid_mwe', 0.0, ...
      'enthalpy_j_m2', 0.0, ...
      'cloned_bottom_solid_mwe', 0.0, ...
      'cloned_bottom_liquid_mwe', 0.0, ...
      'cloned_bottom_enthalpy_j_m2', 0.0, ...
      'merge_export_solid_mwe', 0.0, ...
      'merge_export_liquid_mwe', 0.0, ...
      'merge_export_enthalpy_j_m2', 0.0, ...
      'solid_gross_mwe', 0.0, ...
      'liquid_gross_mwe', 0.0, ...
      'enthalpy_gross_j_m2', 0.0, ...
      'cloned_bottom_solid_gross_mwe', 0.0, ...
      'cloned_bottom_liquid_gross_mwe', 0.0, ...
      'cloned_bottom_enthalpy_gross_j_m2', 0.0, ...
      'merge_export_solid_gross_mwe', 0.0, ...
      'merge_export_liquid_gross_mwe', 0.0, ...
      'merge_export_enthalpy_gross_j_m2', 0.0);
end
