function remesh = initialize_remesh_ledger()
   %INITIALIZE_REMESH_LEDGER Zeroed remesh event ledger.
   %
   % Initialize the remesh ledger struct called by merge_thin_layers. The ledger
   % accumulates one substep's merge budget, then accumulate_remesh_budget folds
   % the events into the forcing-step budget at the end of merge_thin_layers.
   %
   % See also: icemodel.column.merge_thin_layers,
   %  icemodel.column.accumulate_remesh_budget
   %
   %#codegen

   % Declare every field literally so MATLAB Coder never constructs or extends
   % the event ledger from runtime field names.
   %
   % Solid and liquid terms are metres water equivalent. The per-event solid
   % closure is solid = cloned_bottom_solid - merge_export_solid; the liquid
   % export and clone are not tracked separately, only their net liquid_mwe.
   remesh = struct( ...
      'top_deletion_count', 0, ...
      'top_deletion_height_m', 0.0, ...
      'top_export_solid_mwe', 0.0, ...
      'top_export_liquid_mwe', 0.0, ...
      'interior_merge_count', 0, ...
      'solid_mwe', 0.0, ...
      'liquid_mwe', 0.0, ...
      'cloned_bottom_solid_mwe', 0.0, ...
      'merge_export_solid_mwe', 0.0);
end
