function ledger = initialize_budget_state()
   %INITIALIZE_BUDGET_STATE Return a zeroed fixed-schema diagnostic budget ledger.
   %
   %  ledger = icemodel.column.initialize_budget_state()
   %
   % The literal field layout is the code-generation source of truth used by
   % the core timestep kernel. MATLAB-side output and retiming consumers keep
   % their ordered field-name registry in budget_output_fields; tests require
   % that registry to match this compile-time schema exactly.
   %
   %#codegen

   % Declare every field literally so MATLAB Coder never has to construct or
   % extend the ledger from runtime field names.
   ledger = struct( ...
      'mass_budget_solid_start_mwe', 0.0, ...
      'mass_budget_liquid_start_mwe', 0.0, ...
      'mass_budget_solid_end_mwe', 0.0, ...
      'mass_budget_liquid_end_mwe', 0.0, ...
      'mass_budget_phase_solid_mwe', 0.0, ...
      'mass_budget_phase_liquid_mwe', 0.0, ...
      'mass_budget_vapor_solid_mwe', 0.0, ...
      'mass_budget_vapor_liquid_mwe', 0.0, ...
      'mass_budget_remesh_solid_mwe', 0.0, ...
      'mass_budget_remesh_liquid_mwe', 0.0, ...
      'mass_budget_remesh_enthalpy_j_m2', 0.0, ...
      'mass_budget_cloned_bottom_solid_mwe', 0.0, ...
      'mass_budget_cloned_bottom_liquid_mwe', 0.0, ...
      'mass_budget_cloned_bottom_enthalpy_j_m2', 0.0, ...
      'mass_budget_collapse_export_solid_mwe', 0.0, ...
      'mass_budget_collapse_export_liquid_mwe', 0.0, ...
      'mass_budget_collapse_export_enthalpy_j_m2', 0.0, ...
      'mass_budget_vapor_potential_j_m2', 0.0, ...
      'mass_budget_condensation_overflow_mwe', 0.0, ...
      'mass_budget_unapplied_vapor_j_m2', 0.0, ...
      'mass_budget_top_deletion_count', 0.0, ...
      'mass_budget_top_deletion_height_m', 0.0, ...
      'mass_budget_top_export_solid_mwe', 0.0, ...
      'mass_budget_top_export_liquid_mwe', 0.0, ...
      'mass_budget_interior_merge_count', 0.0, ...
      'mass_budget_solid_storage_throughput_mwe', 0.0, ...
      'mass_budget_liquid_storage_throughput_mwe', 0.0, ...
      'mass_budget_phase_solid_throughput_mwe', 0.0, ...
      'mass_budget_phase_liquid_throughput_mwe', 0.0, ...
      'mass_budget_vapor_solid_throughput_mwe', 0.0, ...
      'mass_budget_vapor_liquid_throughput_mwe', 0.0, ...
      'mass_budget_remesh_solid_throughput_mwe', 0.0, ...
      'mass_budget_remesh_liquid_throughput_mwe', 0.0, ...
      'mass_budget_remesh_enthalpy_throughput_j_m2', 0.0, ...
      'mass_budget_cloned_bottom_solid_throughput_mwe', 0.0, ...
      'mass_budget_cloned_bottom_liquid_throughput_mwe', 0.0, ...
      'mass_budget_cloned_bottom_enthalpy_throughput_j_m2', 0.0, ...
      'mass_budget_collapse_export_solid_throughput_mwe', 0.0, ...
      'mass_budget_collapse_export_liquid_throughput_mwe', 0.0, ...
      'mass_budget_collapse_export_enthalpy_throughput_j_m2', 0.0, ...
      'mass_budget_vapor_potential_throughput_j_m2', 0.0, ...
      'mass_budget_condensation_overflow_throughput_mwe', 0.0, ...
      'mass_budget_unapplied_vapor_throughput_j_m2', 0.0);
end
