function tests = test_surface_solver_kernels
   %TEST_SURFACE_SOLVER_KERNELS Verify local surface and column solver kernels.
   tests = functiontests(localfunctions);
end

function setup(testCase)
   % Build paired skinmodel and icemodel synthetic columns so the surface
   % and coupled column solvers can be exercised on matched states.

   % Setup workspace test data
   workspace = icemodel.test.fixtures.makeSyntheticWorkspace(2016, ...
      configure=true, nsteps=24, dt_seconds=900);
   testCase.TestData.workspace = workspace;

   % Setup skinmodel test data
   testCase.TestData.skin = icemodel.test.fixtures.makeSyntheticColumnState( ...
      workspace, 'skinmodel', solver=1, testname='skin_kernel');

   % Setup icemodel test data
   testCase.TestData.ice = icemodel.test.fixtures.makeSyntheticColumnState( ...
      workspace, 'icemodel', solver=3, testname='ice_kernel');
end

function teardown(testCase)
   % Remove the shared synthetic columns after the file-level tests end.

   icemodel.test.fixtures.cleanupSyntheticWorkspace( ...
      testCase.TestData.workspace);
end

function test_sfcflux_derivative_matches_finite_difference(testCase)
   % numerical_surface_flux_linearization should return a derivative consistent
   % with a centered finite difference about the same surface state.

   s = testCase.TestData.skin;
   Ts = s.Ts;

   % Compute SEB residual and numerical derivative for the bulk_richardson
   % scheme.
   [Q_sfc, dQ_sfc_dTs] = ...
      icemodel.surface.numerical_surface_flux( ...
      Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Recompute at a small positive perturbation for a centered difference check.
   h = 1e-5;
   Fplus = icemodel.surface.numerical_surface_flux( ...
      Ts + h, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Recompute at a small negative perturbation.
   Fminus = icemodel.surface.numerical_surface_flux( ...
      Ts - h, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Centered finite difference.
   dQ_sfc_dTs_fd = (Fplus - Fminus) / (2 * h);

   % Verify the derivative is finite and matches the centered difference value.
   testCase.verifyTrue(isfinite(Q_sfc));
   testCase.verifyEqual(dQ_sfc_dTs, dQ_sfc_dTs_fd, 'RelTol', 2e-4);
end

function test_sfctemp_finds_small_surface_residual(testCase)
   % solve_surface_temperature should converge to a T_sfc where
   % numerical_surface_flux_linearization returns a small residual.

   s = testCase.TestData.skin;

   % Solve for T_sfc using the analytical Newton-Raphson solver.
   % Pass s.Ts as the initial guess along with the column state (k_eff, T, dz).
   [Ts, ok] = icemodel.surface.solve_surface_temperature( ...
      s.Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, ...
      s.ea_atm, s.H_h, s.H_e, s.br_coefs, s.liqflag, s.chi, s.T, ...
      s.k_eff, s.dz);

   % Verify convergence using numerical_surface_flux_linearization, which
   % defines the residual that solve_surface_temperature minimizes.
   Q_sfc = icemodel.surface.numerical_surface_flux( ...
      Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   testCase.verifyTrue(ok);
   testCase.verifyLessThan(abs(Q_sfc), 1e-2);
end

function test_sfcflux_includes_precipitation_advection(testCase)
   % The explicit surface residual should include Qa so the analytic and
   % numerical SEB paths use the same forcing terms.

   s = testCase.TestData.skin;
   Ts = s.Ts;
   ppt = 2e-4;
   tppt = s.tair + 3.0;

   % Compute the SEB residual without Qa.
   Q_sfc_dry = icemodel.surface.numerical_surface_flux( ...
      Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, 0.0, tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Compute the SEB residual with Qa.
   Q_sfc_wet = icemodel.surface.numerical_surface_flux( ...
      Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, ppt, tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Verify the difference equals Qa.
   testCase.verifyEqual(Q_sfc_wet - Q_sfc_dry, ...
      icemodel.surface.advective_heat_flux(ppt, tppt, s.cv_liq), 'RelTol', 1e-12);
end

function test_sebsolve_converges_across_root_finders(testCase)
   % All standalone surface-energy-balance root-finder modes should converge
   % on the same synthetic forcing state.

   s = testCase.TestData.skin;

   % Solve for T_sfc using each seb_solver option and verify they are identical
   for seb_solver = 0:2
      opts_sv = s.opts;
      opts_sv.seb_solver = seb_solver;
      [Ts, ok] = icemodel.surface.solve_surface_energy_balance( ...
         s.Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, ...
         s.ppt, s.tppt, s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, ...
         s.H_h, s.H_e, s.hv_atm, s.br_coefs, ...
         s.liqflag, s.chi, s.T, s.k_eff, s.dz, s.ro_sfc, s.snow_depth, ...
         opts_sv);
      residual = icemodel.surface.surface_energy_balance_residual(Ts, ...
         s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
         s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
         s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
         s.dz, s.ro_sfc, ...
         s.snow_depth, s.opts);

      testCase.verifyTrue(ok);
      testCase.verifyTrue(isfinite(Ts));
      testCase.verifyTrue(isreal(Ts));
      testCase.verifyLessThan(abs(residual), 1.0);
   end
end

function test_sebsolve_monin_obukhov_converges_with_numeric_derivative(testCase)
   % The new bulk-MO scheme should converge through the shared SEB residual
   % path under the supported solver=1, seb_solver=2 contract.

   workspace = testCase.TestData.workspace;
   s = icemodel.test.fixtures.makeSyntheticColumnState(workspace, ...
      'icemodel', solver=1, seb_solver=2, ...
      turbulent_flux_scheme='monin_obukhov', z0_ice=0.02, ...
      testname='ice_kernel_bulk_mo');

   % Solve for T_sfc
   [Ts, ok] = icemodel.surface.solve_surface_energy_balance( ...
      s.Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Compute the residual
   residual = icemodel.surface.surface_energy_balance_residual( ...
      Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Verify valid solution and residual
   testCase.verifyTrue(ok);
   testCase.verifyTrue(isfinite(Ts));
   testCase.verifyTrue(isreal(Ts));
   testCase.verifyTrue(isfinite(residual));
   testCase.verifyLessThan(abs(residual), 1.0);
end

function test_one_sweep_coupled_dirichlet_excludes_node_vapor(testCase)
   % With one coupler sweep, the pre-coupler predictor supplies the only
   % boundary the accepted state sees, so the coupled mode must branch the
   % predictor to the vapor-free conductivity form. Mixing formulations
   % there would put the legacy node vapor term into the accepted surface
   % state. The oracle below replays the one-sweep sequence with the
   % vapor-free predictor built independently, so a predictor that
   % evaluated the node vapor term would move the trial surface
   % temperature and fail the exact comparison.

   s = testCase.TestData.ice;
   opts = s.opts;
   opts.use_coupled_vapor = true;

   [Ts, T, f_ice, f_liq, k_eff, ok_seb, ok_ieb, ok_cpl] = ...
      icemodel.couplers.solve_surface_column_dirichlet( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.Sc, s.Sp, s.dz, s.delz, s.fn, ...
      s.opts.dt, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, ...
      s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, ...
      s.hv_atm, s.br_coefs, s.liqflag, s.chi, ...
      s.seb_solver, s.tol, s.maxiter, s.alpha, s.use_aitken, s.jumpmax, ...
      s.cpl_Ts_tol, s.cpl_seb_tol, 1, s.cpl_alpha, ...
      s.cpl_aitken, s.cpl_jumpmax, s.ro_sfc, s.snow_depth, ...
      s.opts.f_res_pore_ice, opts);

   testCase.verifyTrue(ok_seb && ok_ieb && ok_cpl);
   testCase.verifyTrue(isfinite(Ts) && all(isfinite([T; f_ice; f_liq])));

   % The oracle: the same one-sweep sequence, with the predictor
   % conductivity built from the vapor-free form directly.
   k_pred = icemodel.column.bulk_thermal_conductivity( ...
      s.T, s.f_ice, s.f_liq, 0);
   Ts_trial = icemodel.surface.solve_surface_energy_balance( ...
      s.Ts, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, ...
      s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, ...
      s.hv_atm, s.br_coefs, s.liqflag, s.chi, s.T, k_pred, s.dz, ...
      s.ro_sfc, s.snow_depth, opts);
   [T_x, f_ice_x, f_liq_x, k_x] = icemodel.column.solve_column_enthalpy( ...
      Ts_trial, s.T, s.f_ice, s.f_liq, 0.0, 0.0, s.Sc, s.Sp, s.dz, ...
      s.delz, s.fn, s.opts.dt, s.seb_solver, s.tol, s.maxiter, ...
      s.alpha, s.use_aitken, s.jumpmax, opts.debug, true, ...
      s.opts.f_res_pore_ice);
   ro_sfc_x = icemodel.surface.surface_bulk_density( ...
      f_ice_x(1), f_liq_x(1));
   Ts_x = icemodel.surface.solve_surface_energy_balance( ...
      Ts_trial, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, ...
      s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, ...
      s.hv_atm, s.br_coefs, s.liqflag, s.chi, T_x, k_x, s.dz, ...
      ro_sfc_x, s.snow_depth, opts);

   testCase.verifyEqual(Ts, Ts_x, 'AbsTol', 0);
   testCase.verifyEqual(T, T_x, 'AbsTol', 0);
   testCase.verifyEqual(f_ice, f_ice_x, 'AbsTol', 0);
   testCase.verifyEqual(f_liq, f_liq_x, 'AbsTol', 0);
   testCase.verifyEqual(k_eff, k_x, 'AbsTol', 0);
end

function test_iceebsolvedirichlet_converges_on_synthetic_column(testCase)
   % The coupled Dirichlet solver should converge on the synthetic ice
   % column, keep phase fractions bounded, and reduce the accepted
   % updated-state SEB residual relative to the current one-pass pattern.

   s = testCase.TestData.ice;

   % Solve the coupled surface-column energy balance
   [Ts, T, f_ice, f_liq, k_eff, ok_seb, ok_ieb, ok_cpl, n_iters] = ...
      icemodel.couplers.solve_surface_column_dirichlet( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.Sc, s.Sp, s.dz, s.delz, s.fn, ...
      s.opts.dt, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, ...
      s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, ...
      s.hv_atm, s.br_coefs, s.liqflag, s.chi, ...
      s.seb_solver, s.tol, s.maxiter, s.alpha, s.use_aitken, s.jumpmax, ...
      s.cpl_Ts_tol, s.cpl_seb_tol, s.cpl_maxiter, s.cpl_alpha, ...
      s.cpl_aitken, s.cpl_jumpmax, s.ro_sfc, s.snow_depth, ...
      s.opts.f_res_pore_ice, s.opts);

   % Compute the coupled surface-column energy balance residual
   residual_coupled = icemodel.surface.surface_energy_balance_residual(Ts, ...
      s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, T, k_eff, s.dz, ...
      s.ro_sfc, s.snow_depth, s.opts);

   % Solve for T_sfc using the surface solver to mimic a one-pass solve
   [Ts_old, ok_seb_old] = icemodel.surface.solve_surface_energy_balance( ...
      s.Ts, s.tair, s.swd, s.lwd, s.albedo, ...
      s.wspd, s.ppt, s.tppt, s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, ...
      s.nu_air, s.H_h, s.H_e, s.hv_atm, s.br_coefs, ...
      s.liqflag, s.chi, s.T, s.k_eff, s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Solve for column T_ice using the subsurface column solver
   [T_old, ~, ~, k_eff_old, ok_ieb_old] = ...
      icemodel.column.solve_column_enthalpy(Ts_old, s.T, s.f_ice, s.f_liq, ...
      s.Fc, s.Fp, s.Sc, s.Sp, s.dz, s.delz, s.fn, s.opts.dt, 1, s.tol, ...
      s.maxiter, s.alpha, s.use_aitken, s.jumpmax, false);

   % Compute the one-pass residual
   residual_old = icemodel.surface.surface_energy_balance_residual(Ts_old, ...
      s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, T_old, k_eff_old, s.dz, ...
      s.ro_sfc, s.snow_depth, s.opts);

   % Verify the coupled solutions are valid
   testCase.verifyTrue(ok_seb);
   testCase.verifyTrue(ok_ieb);
   testCase.verifyTrue(ok_cpl);
   testCase.verifyTrue(isfinite(n_iters));
   testCase.verifyTrue(isreal(Ts));
   testCase.verifyTrue(all(isfinite([Ts; T; f_ice; f_liq; k_eff])));
   testCase.verifyLessThanOrEqual(max(f_ice + f_liq * s.ro_liq / s.ro_ice), ...
      1 + 1e-9);
   testCase.verifyLessThan(abs(residual_coupled), 1.0);

   % Verify the one-pass solutions are valid
   testCase.verifyTrue(ok_seb_old);
   testCase.verifyTrue(ok_ieb_old);

   % Verify the coupled solution residual is less than the one-pass residual
   testCase.verifyLessThanOrEqual(abs(residual_coupled), ...
      abs(residual_old) + 1e-6);
end

function test_surface_flux_diagnostics_match_energy_balance_residual(testCase)
   % The namespaced surface contracts should report the same residual as the
   % explicit ENBAL helper built from their returned component fluxes.

   s = testCase.TestData.skin;

   % Compute atmospheric vapor pressure
   rh = s.met.rh(s.metstep);
   ea_atm = icemodel.surface.atmospheric_vapor_pressure(s.tair, rh, s.liqflag);

   % Solve for T_sfc
   [Ts_raw, ok] = icemodel.surface.solve_surface_energy_balance(s.Ts, s.tair, ...
      s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ea_atm, ...
      s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, s.k_eff, s.dz, s.ro_sfc, ...
      s.snow_depth, s.opts);

   % Cap T_sfc at the melt temp
   Ts = icemodel.surface.physical_surface_temperature(Ts_raw);

   % Diagnose the full surface energy balance term set.
   [Qe, Qh, Qc, Qsn, Qln, Qa, Qm, ~, balance] = ...
      icemodel.surface.diagnose_surface_energy_balance(Ts, s.tair, s.swd, ...
      s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ea_atm, ...
      s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, s.T, ...
      s.k_eff, s.dz, s.ro_sfc, s.snow_depth, ...
      s.opts);

   % Verify the T_sfc solver worked
   testCase.verifyTrue(ok);

   % Verify the ea_atm calculation matches the test case setup
   testCase.verifyEqual(ea_atm, s.ea_atm, 'RelTol', 1e-12);

   % Verify the balance returned by diagnose_surface_energy_balance matches
   % the explicit SEB evaluation built from its diagnosed terms.
   testCase.verifyEqual(balance, icemodel.surface.evaluate_surface_energy_balance( ...
      Qsn, Qln, Qh, Qe, Qc, Qa, Qm), 'RelTol', 1e-12);

   % Verify the T_sfc solution matches the test case setup value.
   testCase.verifyLessThanOrEqual(Ts, s.Tf + 1e-12);
end

function test_skinsolve_returns_finite_bounded_state(testCase)
   % icemodel.column.solve_column_temperature should keep the skin column
   % finite and phase-bounded on the shared synthetic state.

   s = testCase.TestData.skin;

   % Solve for ice column temperature using the reduced-complexity solver
   [T, f_ice, f_liq, k_eff, ok, iter] = ...
      icemodel.column.solve_column_temperature(s.Ts, s.T, s.f_ice, ...
      s.f_liq, s.dz, s.delz, s.fn, s.opts.dt, s.tol, s.maxiter, ...
      s.alpha, false);

   % Verify the solution is valid
   testCase.verifyTrue(ok);
   testCase.verifyGreaterThan(iter, 0);
   testCase.verifyTrue(all(isfinite(T)));
   testCase.verifyTrue(all(isfinite(k_eff)));
   testCase.verifyLessThanOrEqual(max(f_ice + f_liq * s.ro_liq / s.ro_ice), ...
      1 + 1e-9);
end

function test_skinebsolve_converges_on_synthetic_column(testCase)
   % The coupled skin energy-balance solve should converge and keep the
   % phase fractions inside their physical bounds.

   s = testCase.TestData.skin;

   % Solve for T_sfc and T_ice using the coupled reduced-complexity solver
   [Ts, T, f_ice, f_liq, k_eff, ok_seb, ok_ieb, ok_cpl, n_iters] = ...
      icemodel.couplers.solve_skin_surface_column( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.dz, s.delz, s.fn, ...
      s.opts.dt, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, ...
      s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, ...
      s.hv_atm, s.br_coefs, s.liqflag, s.chi, ...
      s.tol, s.maxiter, s.alpha, s.cpl_maxiter, ...
      s.cpl_Ts_tol, s.cpl_seb_tol, s.cpl_alpha, s.cpl_aitken, ...
      s.cpl_jumpmax, s.ro_sfc, s.snow_depth, s.opts);

   % Verify the solution is valid
   testCase.verifyTrue(ok_seb);
   testCase.verifyTrue(ok_ieb);
   testCase.verifyTrue(ok_cpl);
   testCase.verifyGreaterThan(n_iters, 0);
   testCase.verifyTrue(isreal(Ts));
   testCase.verifyTrue(all(isfinite([Ts; T; k_eff])));
   testCase.verifyLessThanOrEqual(max(f_ice + f_liq * s.ro_liq / s.ro_ice), ...
      1 + 1e-9);
end

function test_iceenbal_and_iceebsolve_converge_on_synthetic_column(testCase)
   % The direct and coupled icemodel column solves should both converge on
   % the shared synthetic state and preserve phase bounds.

   s = testCase.TestData.ice;

   % Solve the ice column model using a direct call to
   % icemodel.column.solve_column_enthalpy (single sweep)
   solver = 1;
   [T_dir, f_ice_dir, f_liq_dir, k_eff_dir, ok_dir, iter_dir] = ...
      icemodel.column.solve_column_enthalpy(s.Ts, s.T, s.f_ice, s.f_liq, ...
      s.Fc, s.Fp, s.Sc, s.Sp, s.dz, s.delz, s.fn, s.opts.dt, solver, s.tol, ...
      s.maxiter, s.alpha, s.use_aitken, s.jumpmax, false);

   % Solve the ice column model using the fully coupled solver with robin bc
   solver = 3;
   [Ts, T_rob, f_ice_rob, f_liq_rob, k_eff_rob, ~, ok_rob, ~, n_iters_rob] = ...
      icemodel.couplers.solve_surface_column_robin( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.Sc, s.Sp, s.dz, s.delz, s.fn, ...
      s.opts.dt, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, ...
      s.tppt, s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, ...
      s.H_e, s.hv_atm, s.br_coefs, s.liqflag, s.chi, solver, s.tol, s.maxiter, ...
      s.alpha, s.use_aitken, s.jumpmax, s.cpl_Ts_tol, s.cpl_seb_tol, ...
      s.cpl_maxiter, s.cpl_alpha, s.cpl_aitken, s.cpl_jumpmax, ...
      s.ro_sfc, s.snow_depth, s.opts.f_res_pore_ice, s.opts);

   % Verify the single-sweep direct solve is valid
   testCase.verifyTrue(ok_dir);
   testCase.verifyGreaterThanOrEqual(iter_dir, 0);
   testCase.verifyTrue(all(isfinite([T_dir; k_eff_dir])));
   testCase.verifyLessThanOrEqual(max(f_ice_dir + f_liq_dir * ...
      s.ro_liq / s.ro_ice), 1 + 1e-9);

   % Verify the fully coupled robin bc solve is valid
   testCase.verifyTrue(ok_rob);
   testCase.verifyGreaterThan(n_iters_rob, 0);
   testCase.verifyTrue(isfinite(Ts));
   testCase.verifyTrue(isreal(Ts));
   testCase.verifyTrue(all(isfinite([T_rob; k_eff_rob])));
   testCase.verifyLessThanOrEqual(max(f_ice_rob + f_liq_rob * ...
      s.ro_liq / s.ro_ice), 1 + 1e-9);
end

function test_iceenbal_routes_exhausted_budget_to_substep_recovery(testCase)
   % A solve that uses its entire inner iteration budget must let the caller
   % restore the checkpoint and reduce dt instead of accepting that iterate.

   s = testCase.TestData.ice;
   [~, ~, ~, ~, ok, iter] = icemodel.column.solve_column_enthalpy( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.Fc, s.Fp, s.Sc, s.Sp, s.dz, ...
      s.delz, s.fn, s.opts.dt, 1, s.tol, 1, s.alpha, ...
      s.use_aitken, s.jumpmax, false);

   testCase.verifyFalse(ok);
   testCase.verifyEqual(iter, 1);
end

function test_secantscalar_finds_root_after_acceleration(testCase)
   % Residual pairs remain valid even when evaluated states are not a
   % consecutive unaccelerated Picard sequence.

   [x_next, ok] = icemodel.numerics.secantscalar( ...
      1.25, 0.375, 2.25, -0.125, 2.125, 10, true);

   testCase.verifyTrue(ok);
   testCase.verifyEqual(x_next, 2.0, 'AbsTol', 10 * eps);
end

function test_secantscalar_uses_safeguarded_fallbacks(testCase)
   % Each invalid or unsafe secant state must retain the caller's relaxed
   % fallback instead of emitting an unusable accelerated temperature.

   cases = [ ...
      struct('xprev', 0.25, 'rprev', 0.875, 'x', 1.25, 'r', 0.375, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', false); ...
      struct('xprev', nan, 'rprev', 0.875, 'x', 1.25, 'r', 0.375, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 0.25, 'rprev', nan, 'x', 1.25, 'r', 0.375, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 0.25, 'rprev', 0.875, 'x', nan, 'r', 0.375, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 0.25, 'rprev', 0.875, 'x', 1.25, 'r', nan, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 0.25, 'rprev', 0, 'x', 1.25, 'r', -0.375, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 0.25, 'rprev', 0.375, 'x', 1.25, 'r', 0, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 0.25, 'rprev', 0.375, 'x', 1.25, 'r', 0.375, ...
      'fallback', 1.625, 'jumpmax', 10, 'enabled', true); ...
      struct('xprev', 1, 'rprev', 1, 'x', 1 + eps, 'r', -1, ...
      'fallback', 3, 'jumpmax', 10, 'enabled', true)];

   for n = 1:numel(cases)
      c = cases(n);
      [x_next, ok] = icemodel.numerics.secantscalar(c.xprev, c.rprev, ...
         c.x, c.r, c.fallback, c.jumpmax, c.enabled);
      testCase.verifyFalse(ok, sprintf('case %d unexpectedly accelerated', n));
      testCase.verifyEqual(x_next, c.fallback, ...
         sprintf('case %d did not retain fallback', n));
   end
end

function test_secantscalar_keeps_bracket_when_fallback_is_outside(testCase)
   % Every endpoint orientation, exterior fallback side, and jump regime must
   % keep a sign-bracketed step inside the bracket and independent of fallback.

   endpoint_cases = [ ...
      struct('xprev', 0, 'rprev', 1, 'x', 2, 'r', -1); ...
      struct('xprev', 2, 'rprev', -1, 'x', 0, 'r', 1)];
   fallbacks = [-100, 100];
   jumpmax_cases = [realmax, 0.25];

   for n_endpoint = 1:numel(endpoint_cases)
      c = endpoint_cases(n_endpoint);
      for fallback = fallbacks
         for jumpmax = jumpmax_cases
            [x_next, ok] = icemodel.numerics.secantscalar( ...
               c.xprev, c.rprev, c.x, c.r, fallback, jumpmax, true);

            expected = c.x + sign(1 - c.x) * min(abs(1 - c.x), jumpmax);
            testCase.verifyTrue(ok);
            testCase.verifyEqual(x_next, expected, 'AbsTol', 10 * eps);
            testCase.verifyGreaterThan(x_next, 0);
            testCase.verifyLessThan(x_next, 2);
         end
      end
   end
end

function test_secantscalar_keeps_unsafe_interpolation_inside_bracket(testCase)
   % Ill-conditioned, overflowing, and endpoint-hugging interpolation should
   % take the finite interior midpoint rather than leave the root bracket.

   cases = [ ...
      struct('xprev', 0, 'rprev', realmin, 'x', 2, 'r', -realmin, ...
      'fallback', 1, 'expected', 1); ...
      struct('xprev', -realmax, 'rprev', -1, 'x', realmax, 'r', 1, ...
      'fallback', 0, 'expected', 0); ...
      struct('xprev', 0, 'rprev', 1, 'x', 2, 'r', -eps, ...
      'fallback', 1, 'expected', 1)];

   for n = 1:numel(cases)
      c = cases(n);
      [x_next, ok] = icemodel.numerics.secantscalar(c.xprev, c.rprev, ...
         c.x, c.r, c.fallback, realmax, true);
      testCase.verifyTrue(ok, sprintf('case %d rejected its bracket', n));
      testCase.verifyEqual(x_next, c.expected, ...
         sprintf('case %d did not use its bracket midpoint', n));
   end
end

function test_robin_debug_dump_handles_inner_failure(testCase)
   % The Robin debug path must preserve the failed solver flags instead of
   % masking the original inner-solve failure with an argument-count error.

   s = testCase.TestData.ice;
   debug_file = [tempname, '.mat'];
   old_debug_file = getenv('ICEMODEL_DEBUG_ICEEBSOLVE_FILE');
   cleanup = onCleanup(@() restoreIceEbDebugEnv( ...
      old_debug_file, debug_file));
   setenv('ICEMODEL_DEBUG_ICEEBSOLVE_FILE', debug_file)
   opts = s.opts;
   opts.debug = true;

   % A one-iteration inner budget deterministically exercises the failure dump.
   [~, ~, ~, ~, ~, ok_seb, ok_ieb, ok_cpl] = ...
      icemodel.couplers.solve_surface_column_robin( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.Sc, s.Sp, s.dz, s.delz, s.fn, ...
      s.opts.dt, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, ...
      s.tppt, s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, ...
      s.H_e, s.hv_atm, s.br_coefs, s.liqflag, s.chi, 3, s.tol, 1, ...
      s.alpha, s.use_aitken, s.jumpmax, s.cpl_Ts_tol, s.cpl_seb_tol, ...
      s.cpl_maxiter, s.cpl_alpha, s.cpl_aitken, s.cpl_jumpmax, ...
      s.ro_sfc, s.snow_depth, s.opts.f_res_pore_ice, opts);

   % The public flags and persisted diagnostic must identify the same failure.
   testCase.verifyTrue(ok_seb);
   testCase.verifyFalse(ok_ieb);
   testCase.verifyFalse(ok_cpl);
   testCase.assertEqual(exist(debug_file, 'file'), 2);
   loaded = load(debug_file, 'debug_state');
   testCase.verifyEqual(loaded.debug_state.reason, "iceenbal_failed");
   testCase.verifyTrue(loaded.debug_state.ok_seb);
   testCase.verifyFalse(loaded.debug_state.ok_ieb);
   testCase.verifyFalse(loaded.debug_state.ok_cpl);
end

function test_robin_coupler_supports_monin_obukhov_on_synthetic_column(testCase)
   % The Robin coupler should accept the bulk-MO scheme and converge on the
   % synthetic ice state used by the shared solver tests.

   workspace = testCase.TestData.workspace;
   s = icemodel.test.fixtures.makeSyntheticColumnState(workspace, ...
      'icemodel', solver=3, seb_solver=2, turbulent_flux_scheme='monin_obukhov', ...
      z0_ice=0.02, testname='ice_kernel_robin_bulk_mo');

   % Solve the ice column model using the fully coupled solver with robin bc
   [Ts, T_rob, f_ice_rob, f_liq_rob, k_eff_rob, ~, ok_rob, ~, n_iters_rob] = ...
      icemodel.couplers.solve_surface_column_robin( ...
      s.Ts, s.T, s.f_ice, s.f_liq, s.Sc, s.Sp, s.dz, s.delz, s.fn, ...
      s.opts.dt, s.tair, s.swd, s.lwd, s.albedo, s.wspd, s.ppt, ...
      s.tppt, s.psfc, s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, ...
      s.H_e, s.hv_atm, s.br_coefs, s.liqflag, s.chi, s.opts.solver, ...
      s.tol, s.maxiter, s.alpha, s.use_aitken, s.jumpmax, s.cpl_Ts_tol, ...
      s.cpl_seb_tol, s.cpl_maxiter, s.cpl_alpha, s.cpl_aitken, ...
      s.cpl_jumpmax, s.ro_sfc, s.snow_depth, ...
      s.opts.f_res_pore_ice, s.opts);

   % Compute the residual
   residual = icemodel.surface.surface_energy_balance_residual(Ts, s.tair, ...
      s.swd, s.lwd, s.albedo, s.wspd, s.ppt, s.tppt, s.psfc, ...
      s.ea_atm, s.ro_atm, s.cv_atm, s.nu_air, s.H_h, s.H_e, s.hv_atm, ...
      s.br_coefs, s.liqflag, s.chi, T_rob, k_eff_rob, ...
      s.dz, s.ro_sfc, s.snow_depth, s.opts);

   % Verify the solution is valid
   testCase.verifyTrue(ok_rob);
   testCase.verifyGreaterThan(n_iters_rob, 0);
   testCase.verifyTrue(isreal(Ts));
   testCase.verifyTrue(all(isfinite([Ts; T_rob; k_eff_rob; residual])));
   testCase.verifyLessThanOrEqual(max(f_ice_rob + f_liq_rob * ...
      s.ro_liq / s.ro_ice), 1 + 1e-9);
   testCase.verifyLessThan(abs(residual), 1.0);
end

function restoreIceEbDebugEnv(old_debug_file, debug_file)
   %RESTOREICEEBDEBUGENV Restore the debug target and remove the test artifact.
   setenv('ICEMODEL_DEBUG_ICEEBSOLVE_FILE', old_debug_file)
   if exist(debug_file, 'file') == 2
      delete(debug_file)
   end
end
