function validate_test_suite(kwargs)
   %VALIDATE_TEST_SUITE Exercise the formal test-suite entrypoints end to end.
   %
   %  validate_test_suite()
   %  validate_test_suite(benchmark_sampling_profile="fast")
   %
   % Use this tool to validate the full test-suite surface without mutating
   % managed baselines. The validation pass checks signatures, Code Analyzer
   % cleanliness, top-level runner selector variants, per-file discovery, and
   % the build/snapshot tools against temporary output files.

   arguments

      kwargs.benchmark_sampling_profile (1, 1) string ...
         {icemodel.validators.mustBeBenchmarkSamplingProfileName( ...
         kwargs.benchmark_sampling_profile)} ...
         = "fast"

      kwargs.include_runoff_reference (1, 1) logical ...
         = true
   end

   benchmark_sampling_profile = kwargs.benchmark_sampling_profile;
   include_runoff_reference = kwargs.include_runoff_reference;

   % Start from the repo root and a clean function cache so the validation
   % pass sees the same code that normal CLI runs would resolve.
   rootdir = icemodel.internal.fullpath();
   testdir = icemodel.getpath('test');
   cd(rootdir)
   clear functions %#ok<CLFUNC>
   rehash toolboxcache

   % Install the canonical formal-suite paths and config for the duration of
   % the validation run.
   [~, ~, ~, ~, suite_cleanup] = ...
      icemodel.test.helpers.bootstrapTestEnvironment(); %#ok<ASGLU>

   % Validate both signature manifests before executing any runners.
   validateFunctionSignaturesJSON(fullfile(rootdir, 'icemodel', ...
      'functionSignatures.json'));
   validateFunctionSignaturesJSON(fullfile(testdir, ...
      'functionSignatures.json'));

   % Keep Code Analyzer clean across both the test tree and shared test
   % support namespaces before running behavioral validation.
   runCheckcode(testdir);
   runCheckcode(fullfile(rootdir, 'icemodel', '+icemodel', '+test'));

   % Isolate temporary tool outputs under test/artifacts so the validation
   % pass does not touch managed baselines or leave persistent clutter.
   tmpdir = tempname(fullfile(testdir, 'artifacts'));
   mkdir(tmpdir);
   validation_run_name = "validate_suite_" + string(char(java.util.UUID.randomUUID));
   cleanup = onCleanup(@() cleanupTemp(tmpdir, validation_run_name));

   failures = strings(0, 1);

   % Exercise the unit runner through its major selector syntaxes first.
   runCase("unit/full", @() checkUnit(run_unit_suite()));
   runCase("unit/file-noext", ...
      @() checkUnit(run_unit_suite(selector="test_met_contracts")));
   runCase("unit/file-ext", ...
      @() checkUnit(run_unit_suite(selector="test_met_contracts.m")));
   runCase("unit/file-abs", @() checkUnit(run_unit_suite(selector=fullfile( ...
      testdir, 'unit', 'test_met_contracts.m'))));
   runCase("unit/folder-abs", ...
      @() checkUnit(run_unit_suite(selector=fullfile(testdir, 'unit'))));

   % Run each named unit file individually so discovery and per-file
   % selection stay aligned.
   unitfiles = string(icemodel.namelists.unittest());
   for i = 1:numel(unitfiles)
      runCase("unit/each/" + unitfiles(i), ...
         @() checkUnit(run_unit_suite(selector=unitfiles(i))));
   end

   % Exercise the benchmark runner through suite, file, and folder selectors.
   runCase("bench/full", ...
      @() checkBench(run_benchmark_suite( ...
      sampling_profile=benchmark_sampling_profile, show_summary=false)));
   runCase("bench/file-noext", ...
      @() checkBench(run_benchmark_suite( ...
      testname="SebKernelPerfTest", ...
      sampling_profile=benchmark_sampling_profile, show_summary=false)));
   runCase("bench/file-ext", ...
      @() checkBench(run_benchmark_suite( ...
      testname="SebKernelPerfTest.m", ...
      sampling_profile=benchmark_sampling_profile, show_summary=false)));
   runCase("bench/file-abs", @() checkBench(run_benchmark_suite( ...
      testname=fullfile(testdir, 'benchmarks', 'SebKernelPerfTest.m'), ...
      sampling_profile=benchmark_sampling_profile, show_summary=false)));
   runCase("bench/micro-folder", @() checkBench(run_benchmark_suite( ...
      testname="micro", include_subfolders=true, ...
      sampling_profile=benchmark_sampling_profile, show_summary=false)));
   runCase("bench/micro-abs-folder", @() checkBench(run_benchmark_suite( ...
      testname=fullfile(testdir, 'benchmarks', 'micro'), ...
      include_subfolders=true, ...
      sampling_profile=benchmark_sampling_profile, show_summary=false)));

   % Run each formal top-level benchmark file on its own selector path.
   benchfiles = string(icemodel.namelists.benchmark());
   for i = 1:numel(benchfiles)
      runCase("bench/each/" + benchfiles(i), ...
         @() checkBench(run_benchmark_suite( ...
         testname=benchfiles(i), ...
         sampling_profile=benchmark_sampling_profile, show_summary=false)));
   end

   % Cover the main regression and perf runner selector combinations without
   % requiring the current outputs to numerically match the baselines.
   runCase("reg/smoke-all-rolling", @() checkRegression( ...
      run_regression_suite(tier="smoke", smbmodel="all", baseline="rolling", ...
      run_name=validation_run_name)));
   runCase("reg/full-skin-rolling", @() checkRegression( ...
      run_regression_suite(tier="full", smbmodel="skinmodel", ...
      baseline="rolling", run_name=validation_run_name)));
   runCase("reg/all-ice-vector-solver", @() checkRegression( ...
      run_regression_suite(tier="all", smbmodel="icemodel", solver=[1 3], ...
      baseline="rolling", run_name=validation_run_name)));
   runCase("reg/smoke-ice-release", @() checkRegression( ...
      run_regression_suite(tier="smoke", smbmodel="icemodel", solver=2, ...
      baseline="v1.1", run_name=validation_run_name)));

   % Perf validation requires artifacts and case summaries, but baseline
   % timing deltas are allowed because this pass is about execution health.
   runCase("perf/smoke-skin-rolling", @() checkPerf(run_perf_suite( ...
      tier="smoke", smbmodel="skinmodel", n_runs=1, include_benchmarks=false, ...
      baseline="rolling", run_name=validation_run_name)));
   runCase("perf/smoke-skin-rolling-bench", @() checkPerf(run_perf_suite( ...
      tier="smoke", smbmodel="skinmodel", n_runs=1, include_benchmarks=true, ...
      benchmark_sampling_profile=benchmark_sampling_profile, ...
      baseline="rolling", run_name=validation_run_name)));
   runCase("perf/smoke-skin-release", @() checkPerf(run_perf_suite( ...
      tier="smoke", smbmodel="skinmodel", n_runs=1, include_benchmarks=false, ...
      baseline="v1.1", run_name=validation_run_name)));
   runCase("perf/all-skin-rolling", @() checkPerf(run_perf_suite( ...
      tier="all", smbmodel="skinmodel", n_runs=1, include_benchmarks=false, ...
      baseline="rolling", run_name=validation_run_name)));
   runCase("perf/smoke-ice-rolling", @() checkPerf(run_perf_suite( ...
      tier="smoke", smbmodel="icemodel", solver=2, n_runs=1, ...
      include_benchmarks=false, baseline="rolling", ...
      run_name=validation_run_name)));

   % Exercise the build/snapshot tools against temporary outputs so their
   % orchestration code paths stay live without mutating managed baselines.
   runCase("tool/build-reg-rolling-temp", @() checkFile( ...
      build_regression_baseline(baseline="rolling", tier="smoke", ...
      smbmodel="skinmodel", include_profile_artifacts=false, ...
      output_file=fullfile(tmpdir, 'reg_build_rolling.mat')), ...
      fullfile(tmpdir, 'reg_build_rolling.mat')));
   runCase("tool/build-reg-release-temp", @() checkFile( ...
      build_regression_baseline(baseline_tag="codex_docpass", tier="smoke", ...
      smbmodel="skinmodel", include_profile_artifacts=true, ...
      output_file=fullfile(tmpdir, 'reg_build_release.mat')), ...
      fullfile(tmpdir, 'reg_build_release.mat')));
   runCase("tool/snapshot-reg-temp", @() checkFile( ...
      snapshot_regression_baseline(baseline_tag="codex_docpass", ...
      smbmodel="skinmodel", overwrite=true, ...
      output_file=fullfile(tmpdir, 'reg_snapshot.mat')), ...
      fullfile(tmpdir, 'reg_snapshot.mat')));
   runCase("tool/build-perf-rolling-temp", @() checkFile( ...
      build_perf_baseline(baseline="rolling", tier="smoke", ...
      smbmodel="skinmodel", n_runs=1, include_benchmarks=false, ...
      include_profile_artifacts=false, ...
      output_file=fullfile(tmpdir, 'perf_build_rolling.mat')), ...
      fullfile(tmpdir, 'perf_build_rolling.mat')));
   runCase("tool/build-perf-release-temp", @() checkFile( ...
      build_perf_baseline(baseline_tag="codex_docpass", tier="smoke", ...
      smbmodel="skinmodel", n_runs=1, include_benchmarks=true, ...
      benchmark_sampling_profile=benchmark_sampling_profile, ...
      include_profile_artifacts=true, ...
      output_file=fullfile(tmpdir, 'perf_build_release.mat')), ...
      fullfile(tmpdir, 'perf_build_release.mat')));
   runCase("tool/snapshot-perf-temp", @() checkFile( ...
      snapshot_perf_baseline(baseline_tag="codex_docpass", ...
      smbmodel="skinmodel", overwrite=true, ...
      output_file=fullfile(tmpdir, 'perf_snapshot.mat')), ...
      fullfile(tmpdir, 'perf_snapshot.mat')));

   % Validate the sibling-runoff reference builder when that dependency is
   % available and the caller has not explicitly skipped it.
   if include_runoff_reference
      runCase("tool/build-runoff-ref-temp", @() checkFile( ...
         build_runoff_reference(simyear=2016, ...
         output_file=fullfile(tmpdir, 'runoff_reference_2016.mat')), ...
         fullfile(tmpdir, 'runoff_reference_2016.mat')));
   end

   % Fail once at the end so the console log captures all broken cases.
   if ~isempty(failures)
      disp('VALIDATION FAILURES:');
      disp(failures);
      error('icemodel suite validation failed')
   end

   disp('VALIDATION_OK');

   function runCase(name, fh)
      %RUNCASE Execute one validation case and retain any failure report.

      fprintf('=== %s\n', name);
      try
         fh();
         fprintf('PASS %s\n', name);
      catch ME
         failures(end+1, 1) = string(name + ": " + ...
            getReport(ME, 'extended', 'hyperlinks', 'off'));
         fprintf('FAIL %s\n', name);
      end
   end

   function checkUnit(results)
      %CHECKUNIT Require the unit runner to return no failures or incompletes.

      assert(nnz([results.Failed]) == 0, 'unit failures detected');
      assert(nnz([results.Incomplete]) == 0, 'unit incomplete tests detected');
   end

   function checkBench(results)
      %CHECKBENCH Require every benchmark case to remain valid.

      assert(nnz(~[results.Valid]) == 0, 'invalid benchmark cases detected');
   end

   function checkRegression(results)
      %CHECKREGRESSION Require regression execution to complete cleanly.

      assert(nnz([results.Incomplete]) == 0, ...
         'regression incomplete tests detected');
   end

   function checkPerf(results)
      %CHECKPERF Require perf runs to emit their normal report artifacts.

      assert(isfield(results, 'artifact_file') && ...
         exist(char(results.artifact_file), 'file') == 2, ...
         'perf artifact was not created');
      assert(isfield(results, 'case_summary') && istable(results.case_summary) ...
         && ~isempty(results.case_summary), ...
         'perf case summary was not populated');
   end

   function checkFile(~, pathname)
      %CHECKFILE Require a tool run to create its requested output file.

      assert(exist(char(pathname), 'file') == 2, ...
         'expected output file was not created');
   end
end

function runCheckcode(rootdir)
   %RUNCHECKCODE Require Code Analyzer cleanliness under one tree.

   % Walk every MATLAB source file under the requested tree.
   files = dir(fullfile(rootdir, '**', '*.m'));
   for i = 1:numel(files)
      pathname = fullfile(files(i).folder, files(i).name);

      % Treat any remaining analyzer message as a validation failure.
      messages = checkcode(pathname, '-id');
      assert(isempty(messages), ...
         'checkcode messages remain in %s', pathname);
   end
end

function cleanupTemp(tmpdir, validation_run_name)
   %CLEANUPTEMP Remove validation scratch outputs after the run completes.

   testdir = icemodel.getpath('test');

   % Remove the temp artifact tree that held direct tool output files.
   if exist(tmpdir, 'dir') == 7
      rmdir(tmpdir, 's');
   end

   % Remove the shared compare-artifact folder produced by runner checks.
   artifact_dir = fullfile(testdir, 'artifacts', ...
      char(validation_run_name));
   if exist(artifact_dir, 'dir') == 7
      rmdir(artifact_dir, 's');
   end

   % Remove profiler sidecars created by temporary baseline build/snapshot
   % targets so validation does not leave stale generated folders behind.
   profile_dirs = [ ...
      string(fullfile(testdir, 'baselines', 'profiler', ...
      'reg_build_release')); ...
      string(fullfile(testdir, 'baselines', 'profiler', ...
      'perf_build_release')); ...
      string(fullfile(testdir, 'baselines', 'profiler', ...
      'perf_snapshot'))];
   for i = 1:numel(profile_dirs)
      if exist(profile_dirs(i), 'dir') == 7
         rmdir(profile_dirs(i), 's');
      end
   end
end
